Repository scylladb/scylladb, pull requests merged in 2022-11, with the labels that each got.

#11896 doc: improve the documentation landing page
  docs/index.rst
Labels: Documentation

#11975 doc: add the "Scylladb Enterprise" label to the Enterprise-only fearues
  docs/cql/compaction.rst
  docs/operating-scylla/security/auditing.rst
  docs/operating-scylla/security/ldap-authentication.rst
  docs/operating-scylla/security/ldap-authorization.rst
  docs/rst_include/enterprise-only-note.rst
  docs/using-scylla/in-memory.rst
  docs/using-scylla/workload-prioritization.rst
Labels: Documentation

#11226 doc: update ScyllaDB requirements - supported CPUs and AWS i4g instances
  docs/getting-started/system-requirements.rst
Labels: Documentation

#11984 doc: document user defined functions (UDFs)
  docs/cql/functions.rst
Labels: Documentation

#12031 cql3: don't ignore other restrictions when a multi column restriction is present during filtering
  cql3/selection/selection.cc
  test/boost/restrictions_test.cc
  test/cql-pytest/test_scan.py
Labels: bug, CQL, Backport candidate

#12061 [branch 5.1 backport] doc: remove the Operator documentation pages from the core ScyllaDB docs
  docs/_utils/redirects.yaml
Labels: Documentation

#12079 [branch 5.1 backport] doc: add ScyllaDB image upgrade guides for patch releases
  docs/upgrade/_common/upgrade-guide-v2022-patch-ubuntu-and-debian-p1.rst
  docs/upgrade/_common/upgrade-guide-v2022-patch-ubuntu-and-debian-p2.rst
  docs/upgrade/_common/upgrade-guide-v2022-patch-ubuntu-and-debian.rst
  docs/upgrade/_common/upgrade-guide-v5-patch-ubuntu-and-debian-p1.rst
  docs/upgrade/_common/upgrade-guide-v5-patch-ubuntu-and-debian-p2.rst
  docs/upgrade/_common/upgrade-guide-v5-patch-ubuntu-and-debian.rst
  docs/upgrade/_common/upgrade-image-enterprise.rst
  docs/upgrade/_common/upgrade-image-opensource.rst
  docs/upgrade/_common/upgrade-image.rst
  docs/upgrade/upgrade-enterprise/upgrade-guide-from-2021.1-to-2022.1/index.rst
  docs/upgrade/upgrade-enterprise/upgrade-guide-from-2021.1-to-2022.1/upgrade-guide-from-2021.1-to-2022.1-image.rst
  docs/upgrade/upgrade-enterprise/upgrade-guide-from-2022.x.y-to-2022.x.z/index.rst
  docs/upgrade/upgrade-enterprise/upgrade-guide-from-2022.x.y-to-2022.x.z/upgrade-guide-from-2022.x.y-to-2022.x.z-image.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-4.6-to-5.0/upgrade-guide-from-4.6-to-5.0-image.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.x.y-to-5.x.z/index.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.x.y-to-5.x.z/upgrade-guide-from-5.x.y-to-5.x.z-image.rst
Labels: Documentation

#11997 doc: document the Alternator TTL feature as GA
  docs/alternator/compatibility.md
Labels: Documentation

#12070 doc: add the links to the per-partition rate limit extension
  docs/cql/ddl.rst
Labels: Documentation

#12052 cql3: expr: make it possible to evaluate expr::binary_operator
  cql3/expr/expression.cc
  test/boost/expr_test.cc
  test/cql-pytest/cassandra_tests/validation/entities/collections_test.py
  test/cql-pytest/cassandra_tests/validation/operations/select_single_column_relation_test.py
  test/cql-pytest/cassandra_tests/validation/operations/select_test.py
  test/cql-pytest/test_scan.py
Labels: CQL
