Repository scylladb/scylladb, pull requests merged in 2023-09, with the labels that each got.

#15325 docs: improve command line samples in unified-installer.rst
  docs/getting-started/installation-common/unified-installer.rst
Labels: Documentation

#15364 Gossiper: replace seastar threads with coroutines
  gms/gossiper.cc
  gms/gossiper.hh
Labels: gossip

#15489 doc: add a note that counters do not support TTL
  docs/cql/types.rst
  docs/using-scylla/counters.rst
Labels: Documentation

#15526 cql3/prepare_context: fix generating pk_indexes for duplicate named bind variables
  cql3/Cql.g
  cql3/prepare_context.cc
  cql3/prepare_context.hh
  test/cql-pytest/test_prepare.py
Labels: CQL

#15552 build: extract code fragments into functions
  configure.py
Labels: Build

#15562 doc: replace the link to Cassandra compatibility information
  docs/faq.rst
  docs/using-scylla/cassandra-compatibility.rst
Labels: Documentation
