Repository scylladb/scylladb, pull requests merged in 2023-08, with the labels that each got.

#14890 De-static system_keyspace's [gs]et_scylla_local_param(_as)?
  db/system_keyspace.cc
  db/system_keyspace.hh
Labels: code cleanup

#14997 s3/client: check for available port before starting minio server
  test.py
  test/object_store/conftest.py
  test/pylib/minio_server.py
Labels: test, object storage

#15085 build: cmake: support Coverage and Sanitize build modes
  CMakeLists.txt
  cmake/mode.COVERAGE.cmake
  cmake/mode.SANITIZE.cmake
Labels: Build
