Repository scylladb/scylladb, pull requests merged in 2023-10, with the labels that each got.

#15582 doc: update the Cassandra compatibility information
  docs/using-scylla/cassandra-compatibility.rst
Labels: Documentation

#15740 doc: doc: remove recommended image upgrade with OS from previous releases
  docs/upgrade/_common/upgrade-guide-v5-patch-ubuntu-and-debian-p1.rst
  docs/upgrade/_common/upgrade-guide-v5-patch-ubuntu-and-debian-p2.rst
  docs/upgrade/_common/upgrade-guide-v5-patch-ubuntu-and-debian.rst
  docs/upgrade/_common/upgrade-image-opensource.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-4.6-to-5.0/upgrade-guide-from-4.6-to-5.0-image.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.0-to-5.1/upgrade-guide-from-5.0-to-5.1-generic.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.x.y-to-5.x.z/upgrade-guide-from-5.x.y-to-5.x.z-image.rst
Labels: Documentation

#15667 build: cmake: pass -dynamic-linker to ld
  CMakeLists.txt
  cmake/mode.common.cmake
Labels: Build

#15668 build: extract code fragments into functions
  configure.py
Labels: Build

#15769 [5.1 backport] doc: remove recommended image upgrade with OS from previous releases
  docs/upgrade/_common/upgrade-guide-v5-patch-ubuntu-and-debian-p1.rst
  docs/upgrade/_common/upgrade-guide-v5-patch-ubuntu-and-debian-p2.rst
  docs/upgrade/_common/upgrade-guide-v5-patch-ubuntu-and-debian.rst
  docs/upgrade/_common/upgrade-image-opensource.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-4.6-to-5.0/upgrade-guide-from-4.6-to-5.0-image.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.0-to-5.1/upgrade-guide-from-5.0-to-5.1-generic.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.x.y-to-5.x.z/upgrade-guide-from-5.x.y-to-5.x.z-image.rst
Labels: Documentation

#15768 [5.2 backport] doc: remove recommended image upgrade with OS from previous releases
  docs/upgrade/_common/upgrade-guide-v5-patch-ubuntu-and-debian-p1.rst
  docs/upgrade/_common/upgrade-guide-v5-patch-ubuntu-and-debian-p2.rst
  docs/upgrade/_common/upgrade-guide-v5-patch-ubuntu-and-debian.rst
  docs/upgrade/_common/upgrade-image-opensource.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-4.6-to-5.0/upgrade-guide-from-4.6-to-5.0-image.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.0-to-5.1/upgrade-guide-from-5.0-to-5.1-generic.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.x.y-to-5.x.z/upgrade-guide-from-5.x.y-to-5.x.z-image.rst
Labels: Documentation

#15628 doc: improve the docs for handling failures
  docs/architecture/raft.rst
  docs/cql/ddl.rst
  docs/operating-scylla/procedures/cluster-management/add-node-to-cluster.rst
  docs/operating-scylla/procedures/cluster-management/remove-node.rst
  docs/operating-scylla/procedures/cluster-management/replace-dead-node-or-more.rst
  docs/operating-scylla/procedures/cluster-management/replace-dead-node.rst
  docs/operating-scylla/procedures/cluster-management/replace-running-node.rst
  docs/troubleshooting/cluster/index.rst
  docs/troubleshooting/failed-add-remove-replace.rst
  docs/troubleshooting/failed-update-schema.rst
  docs/troubleshooting/handling-node-failures.rst
  docs/troubleshooting/modeling/index.rst
Labels: Documentation

#15796 test/pylib: extract the env variable related functions out
  test/pylib/minio_server.py
Labels: code cleanup

#15819 build: cmake: avoid using large amount stack of when compiling parser
  cql3/CMakeLists.txt
Labels: Build

#15818 build: extract code fragments into functions
  configure.py
Labels: Build

#15636 Nodetools docs improvements 1/N
  docs/operating-scylla/nodetool-commands/compact.rst
  docs/operating-scylla/nodetool-commands/stop.rst
  docs/operating-scylla/nodetool.rst
Labels: Documentation

#15615 scylla-sstable/tools: Use semi-properly initiated db::config + extensions to allow encrypted sstables
  tools/scylla-sstable.cc
  tools/utils.cc
  tools/utils.hh
Labels: P1
