Repository scylladb/scylladb, pull requests merged in 2023-04, with the labels that each got.

#11987 Topology: introduce nodes
  api/endpoint_snitch.cc
  db/hints/host_filter.cc
  locator/network_topology_strategy.cc
  locator/token_metadata.cc
  locator/token_metadata.hh
  locator/topology.cc
  locator/topology.hh
  locator/types.hh
  main.cc
  repair/repair.cc
  service/storage_proxy.cc
  service/storage_service.cc
  test/boost/network_topology_strategy_test.cc
  test/boost/storage_proxy_test.cc
  test/lib/cql_test_env.cc
Labels: topology changes

#12422 Cleanup sstables in resharding and other compaction types
  compaction/compaction.cc
  compaction/compaction_descriptor.hh
  compaction/compaction_fwd.hh
  compaction/compaction_manager.cc
  compaction/compaction_manager.hh
  compaction/compaction_state.hh
  compaction/compaction_strategy_impl.hh
  compaction/strategy_control.hh
  replica/compaction_group.hh
  replica/database.hh
  replica/distributed_loader.cc
  replica/distributed_loader.hh
  replica/table.cc
  sstables/shared_sstable.hh
  sstables/sstable_set.cc
  sstables/sstable_set.hh
  sstables/sstable_set_impl.hh
  sstables/sstables.cc
  test/boost/sstable_compaction_test.cc
Labels: Eng-2

#12418 doc: extend the information about the recommended RF on the Tracing page
  docs/using-scylla/tracing.rst
Labels: Documentation

#13691 Adding MindsDB integration to Docs
  docs/using-scylla/integrations/index.rst
  docs/using-scylla/integrations/integration-mindsdb.rst
Labels: Documentation

#13480 cql3/expr: remove expr::token
  cql3/Cql.g
  cql3/expr/expression.cc
  cql3/expr/expression.hh
  cql3/expr/prepare_expr.cc
  cql3/expr/restrictions.cc
  cql3/functions/functions.cc
  cql3/functions/functions.hh
  cql3/restrictions/statement_restrictions.cc
  cql3/restrictions/statement_restrictions.hh
  cql3/selection/selectable.cc
  cql3/statements/modification_statement.cc
  cql3/statements/select_statement.cc
  test/boost/expr_test.cc
  test/boost/statement_restrictions_test.cc
  test/cql-pytest/test_filtering.py
Labels: CQL
