Repository scylladb/scylladb, pull requests merged in 2023-12, with the labels that each got.

#15916 build: add an option to create building system with CMake
  CMakeLists.txt
  configure.py
Labels: Build

#16386 sstables, utils: do not include unused header
  sstables/writer.hh
  utils/bit_cast.hh
Labels: code cleanup

#16399 scripts/coverage.py: cleanups
  scripts/coverage.py
Labels: code cleanup

#16158 Add support to tablet storage splitting
  compaction/compaction.cc
  compaction/compaction_descriptor.hh
  compaction/compaction_manager.cc
  compaction/compaction_manager.hh
  compaction/time_window_compaction_strategy.cc
  configure.py
  locator/tablets.cc
  locator/tablets.hh
  mutation_writer/CMakeLists.txt
  mutation_writer/token_group_based_splitting_writer.cc
  mutation_writer/token_group_based_splitting_writer.hh
  readers/flat_mutation_reader_v2.hh
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  scylla-gdb.py
  test/boost/CMakeLists.txt
  test/boost/compaction_group_test.cc
  test/boost/mutation_writer_test.cc
  test/boost/sstable_compaction_test.cc
  test/boost/tablets_test.cc
Labels: tablets

#16324 Handle S3 partial read overflows
  test/boost/s3_test.cc
  utils/s3/client.cc
Labels: object storage

#16479 build: cmake: map 'release' to 'RelWithDebInfo'
  CMakeLists.txt
  cmake/mode.RelWithDebInfo.cmake
  configure.py
Labels: Build

#16532 build: cmake: add "mode_list" target
  CMakeLists.txt
  cmake/mode.Coverage.cmake
  cmake/mode.Debug.cmake
  cmake/mode.Dev.cmake
  cmake/mode.RelWithDebInfo.cmake
  cmake/mode.Sanitize.cmake
Labels: Build

#16556 select statement: verify EXECUTE permissions only for non native functions
  cql3/statements/select_statement.cc
  test/cql-pytest/test_permissions.py
Labels: Requires-Backport-to-5.4
