Repository scylladb/scylladb, pull requests merged in 2023-11, with the labels that each got.

#15946 test/object_store: PEP8 compliant cleanups
  test/object_store/test_basic.py
Labels: test, code cleanup, object storage

#15933 build: cmake: configure all available config types
  CMakeLists.txt
  cmake/mode.Coverage.cmake
  cmake/mode.Debug.cmake
  cmake/mode.Dev.cmake
  cmake/mode.Release.cmake
  cmake/mode.Sanitize.cmake
  cmake/mode.common.cmake
  cql3/CMakeLists.txt
Labels: Build

#15880 doc: add the upgrade guide from 5.2 to 5.4
  docs/cql/wasm.rst
  docs/upgrade/scylladb-versioning.rst
  docs/upgrade/upgrade-opensource/index.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.1-to-5.2/upgrade-guide-from-5.1-to-5.2-generic.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.2-to-5.3/index.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.2-to-5.3/metric-update-5.2-to-5.3.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.2-to-5.3/upgrade-guide-from-5.2-to-5.3-generic.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.2-to-5.4/index.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.2-to-5.4/metric-update-5.2-to-5.4.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.2-to-5.4/upgrade-guide-from-5.2-to-5.4-generic.rst
  docs/upgrade/upgrade-to-enterprise/upgrade-guide-from-5.2-to-2023.1/upgrade-guide-from-5.2-to-2023.1-generic.rst
Labels: Documentation

#15855 doc: add CQL Reference for Materialized Views and remove irrelevant version information
  docs/cql/mv.rst
  docs/using-scylla/materialized-views.rst
Labels: Documentation

#16030 [Backport 5.4]: docs: render options with role
  docs/_ext/scylladb_cc_properties.py
  docs/_static/css/custom.css
  docs/_templates/db_config.tmpl
  docs/_templates/db_option.tmpl
  docs/reference/configuration-parameters.rst
Labels: Documentation

#16003 mutation_query: properly send range tombstones in reverse queries
  mutation/mutation_partition.cc
  mutation_query.hh
  test/boost/mutation_query_test.cc
Labels: P1, Requires-Backport-to-5.2, Requires-Backport-to-5.1, Requires-Backport-to-5.4

#16074 test/sstable_compaction_test: check every sstable replaced sstable
  test/boost/sstable_compaction_test.cc
Labels: test, unitest, compaction
