Repository scylladb/scylladb, pull requests merged in 2024-03, with the labels that each got.

#17648 build: cmake: use scylla build mode for rust profile name
  CMakeLists.txt
  cmake/mode.Coverage.cmake
  cmake/mode.Debug.cmake
  cmake/mode.Dev.cmake
  cmake/mode.RelWithDebInfo.cmake
  cmake/mode.Sanitize.cmake
  rust/CMakeLists.txt
Labels: area/build

#17365 Automation of ScyllaDB backports - Phase #1: Master → OSS backports
  .github/mergify.yml
  .github/scripts/label_promoted_commits.py
  .github/workflows/add-label-when-promoted.yaml
  .github/workflows/pr-require-backport-label.yaml
Labels: backport/none

#17281 docs: trigger the docs-pages workflow on release branches
  .github/workflows/docs-pages.yaml
Labels: type/documentation

#17668 scylla-gdb.py: fixes warnings raised by flake8
  scylla-gdb.py
Labels: type/code cleanup, backport/none

#17450 Handle tablet migration failure in barrier stages
  replica/tablets.cc
  replica/tablets.hh
  service/storage_service.cc
  service/topology_coordinator.cc
  test/topology_custom/test_tablets_migration.py
Labels: backport/none

#17474 test: rest_api: fix tests to work with tablets
  repair/repair.cc
  test/rest_api/conftest.py
  test/rest_api/run
  test/rest_api/suite.yaml
  test/rest_api/test_compaction_task.py
  test/rest_api/test_storage_service.py
Labels: area/test, area/tablets

#17541 tools/scylla-nodetool: listsnapshot: make it compatible with origin
  test/nodetool/test_snapshot.py
  tools/scylla-nodetool.cc
Labels: area/nodetool, backport/none

#17553 tools/scylla-nodetool: print hostname if --resolve-ip is passed to "ring"
  test/nodetool/test_ring.py
  tools/scylla-nodetool.cc
Labels: area/nodetool, backport/none

#17024 gossiper: do_status_check: allow evicting dead nodes from membership with no host_id
  gms/endpoint_state.cc
  gms/endpoint_state.hh
  gms/gossiper.cc
Labels: backport/none

#17405 storage_service/ownership: handle requests when tablets are enabled
  api/api-doc/storage_service.json
  api/storage_service.cc
  locator/abstract_replication_strategy.hh
  locator/tablets.cc
  locator/tablets.hh
  service/storage_service.cc
  service/storage_service.hh
  test/pylib/rest_client.py
  test/rest_api/test_storage_service.py
  test/topology_experimental_raft/test_tablets.py
Labels: backport/none

#17684 Handle tablet migration failure in wrapping-up stages
  service/storage_service.cc
  test/topology_custom/test_tablets_migration.py
Labels: area/tablets, backport/none

#17710 utils: add fmt::formatter for utils types
  test/boost/flat_mutation_reader_test.cc
  test/boost/network_topology_strategy_test.cc
  test/lib/test_utils.cc
  test/lib/test_utils.hh
  utils/exception_container.hh
  utils/human_readable.cc
  utils/human_readable.hh
  utils/to_string.cc
  utils/to_string.hh
Labels: backport/none

#17721 Extend test.py's ability to select test cases
  docs/dev/testing.md
  test.py
Labels: backport/none

#17651 tools/scylla-nodetool: implement the last batch of commands
  test/nodetool/test_netstats.py
  test/nodetool/test_proxyhistograms.py
  test/nodetool/test_tablehistograms.py
  tools/scylla-nodetool.cc
  utils/estimated_histogram.hh
Labels: area/nodetool, backport/none

#17769 mutation: add fmt::formatter for mutation types
  mutation/frozen_mutation.cc
  mutation/frozen_mutation.hh
  mutation/mutation.cc
  mutation/mutation.hh
  mutation/mutation_partition_v2.cc
  mutation/mutation_partition_v2.hh
  mutation/partition_version.cc
  schema_mutations.cc
Labels: backport/none

#17757 remove_rpc_client_with_ignored_topology: recreate rpc client earlier
  service/storage_service.cc
  service/storage_service.hh
  test/topology_custom/test_remove_rpc_client_with_pending_requests.py
Labels: backport/none

#17796 Do not try to balance tablets on nodes which are known to be down
  service/tablet_allocator.cc
  service/tablet_allocator.hh
  service/topology_coordinator.cc
  test/boost/tablets_test.cc
Labels: area/tablets, backport/none

#17547 tools/scylla-nodetool: implement the status command
  test/nodetool/conftest.py
  test/nodetool/rest_api_mock.py
  test/nodetool/test_repair.py
  test/nodetool/test_status.py
  tools/scylla-nodetool.cc
Labels: area/nodetool, P1, backport/none

#17773 Drop tablets of dropped views and indices
  db/schema_tables.cc
  service/migration_manager.cc
  service/tablet_allocator.cc
  test/cql-pytest/test_tablets.py
  test/cql-pytest/util.py
Labels: area/tablets, backport/none

#17842 schema_tables: unfreeze frozen_mutation:s gently
  db/schema_tables.cc
  mutation/frozen_mutation.cc
  mutation/frozen_mutation.hh
Labels: area/schema changes, symptom/stalls, backport/none

#17388 Fix node replace with tablets for RF=N
  api/api-doc/raft.json
  api/raft.cc
  db/system_keyspace.cc
  db/system_keyspace.hh
  db/view/view.cc
  docs/dev/topology-over-raft.md
  locator/abstract_replication_strategy.cc
  locator/abstract_replication_strategy.hh
  locator/tablets.cc
  locator/tablets.hh
  locator/topology.cc
  replica/tablets.cc
  replica/tablets.hh
  service/storage_service.cc
  service/storage_service.hh
  service/tablet_allocator.cc
  service/topology_coordinator.cc
  service/topology_state_machine.cc
  service/topology_state_machine.hh
  test/boost/locator_topology_test.cc
  test/boost/tablets_test.cc
  test/perf/perf_tablets.cc
  test/pylib/rest_client.py
  test/topology/util.py
  test/topology_experimental_raft/test_mv_tablets_replace.py
  test/topology_experimental_raft/test_tablets_removenode.py
Labels: area/tablets, backport/none

#17848 build: cmake: put server deb packages under build/dist/$<CONFIG>/debian
  cmake/build_submodule.cmake
  dist/CMakeLists.txt
Labels: area/build, backport/none

#17919 cdc: should_propose_first_generation: get my_host_id from caller
  cdc/generation.cc
  cdc/generation.hh
  service/storage_service.cc
  service/storage_service.hh
Labels: backport/none

#17351 db/virtual_tables: make token_ring_table tablet aware
  db/virtual_tables.cc
  service/storage_service.cc
  test/cql-pytest/test_describe.py
  test/cql-pytest/test_virtual_tables.py
Labels: area/tablets, backport/none

#17884 test: randomized_nemesis_test: add fmt::formatter for some types
  raft/raft.hh
  test/raft/generator.hh
  test/raft/randomized_nemesis_test.cc
Labels: backport/none

#17168 scylla-nodetool: make command-line parsing fully compatible with the legacy nodetool
  test/nodetool/test_nodetool.py
  tools/scylla-nodetool.cc
  tools/utils.cc
  tools/utils.hh
Labels: area/nodetool, status/release blocker, area/tablets, backport/none

#17632 storage_service::merge_topology_snapshot: handle big mutations
  mutation/mutation.cc
  mutation/mutation.hh
  service/storage_service.cc
  test/boost/mutation_test.cc
  test/topology_experimental_raft/test_cdc_generation_data.py
Labels: area/tablets, backport/none

#17944 treewide: add fmt::formatter for exception types
  cdc/generation.hh
  data_dictionary/data_dictionary.hh
  exceptions/exceptions.hh
  sstables/exceptions.hh
  utils/exception_container.hh
Labels: backport/none

#17934 topology_coordinator: do not clear unpublished CDC generation's data
  service/topology_coordinator.cc
  test/boost/error_injection_test.cc
  test/topology_experimental_raft/test_cdc_generation_clearing.py
  test/topology_experimental_raft/test_cdc_generation_publishing.py
  utils/error_injection.hh
Labels: backport/none

#17965 test/lib: sstable::test_env consolidate and reduce header footprint
  test/lib/sstable_test_env.hh
  test/lib/sstable_utils.cc
  test/lib/test_services.cc
Labels: area/test, tests/unitest, backport/none

#17971 github: sync-labels: use more descriptive name for workflow
  .github/workflows/sync-labels.yaml
Labels: area/build, backport/none

#17590 raft timeouts: better handling of lost quorum
  api/api.cc
  auth/common.cc
  auth/common.hh
  auth/default_authorizer.cc
  auth/password_authenticator.cc
  auth/service.cc
  auth/standard_role_manager.cc
  db/config.cc
  db/config.hh
  main.cc
  service/migration_manager.cc
  service/raft/raft_group0.cc
  service/raft/raft_group0.hh
  service/raft/raft_group0_client.cc
  service/raft/raft_group0_client.hh
  service/raft/raft_group_registry.cc
  service/raft/raft_group_registry.hh
  service/storage_service.cc
  service/storage_service.hh
  service/topology_coordinator.cc
  test/pylib/manager_client.py
  test/pylib/scylla_cluster.py
  test/topology/conftest.py
  test/topology_custom/test_raft_no_quorum.py
  utils/composite_abort_source.hh
  utils/error_injection.hh
Labels: backport/none

#17318 tablets: add warning on CREATE KEYSPACE
  cql3/statements/create_keyspace_statement.cc
  test/cql-pytest/test_guardrail_replication_strategy.py
  test/cql-pytest/test_keyspace.py
Labels: area/tablets, backport/none

#17979 tools/scylla-nodetool: implement the getsstables and sstableinfo commands
  test/nodetool/conftest.py
  test/nodetool/rest_api_mock.py
  test/nodetool/test_nodetool.py
  test/nodetool/test_sstable.py
  tools/scylla-nodetool.cc
Labels: area/nodetool, backport/none

#17562 test/cql-pytest: test_select_from_mutation_fragments.py: move away from memtables
  cql3/statements/select_statement.cc
  test/cql-pytest/test_select_from_mutation_fragments.py
Labels: symptom/ci stability

#17976 compaction: implement unchecked_tombstone_compaction
  compaction/compaction_strategy.cc
  compaction/compaction_strategy.hh
  compaction/compaction_strategy_impl.hh
  docs/cql/compaction.rst
  docs/troubleshooting/pointless-compactions.rst
  test/boost/sstable_compaction_test.cc
  test/cql-pytest/test_compaction_strategy_validation.py
Labels: area/compaction, backport/none

#18036 alternator: reduce stall for Query and Scan with large pages
  alternator/executor.cc
  cql3/result_set.hh
  test/alternator/test_query.py
Labels: backport/none

#18051 storage_service: keep subscription to raft topology feature alive
  gms/feature.hh
  service/storage_service.cc
Labels: backport/none

#17846 network_topology_strategy: reallocate_tablets: support for rf changes
  locator/load_sketch.hh
  locator/network_topology_strategy.cc
  locator/network_topology_strategy.hh
  locator/tablet_replication_strategy.hh
  locator/topology.hh
  test/boost/network_topology_strategy_test.cc
Labels: area/tablets, backport/none

#18054 test: changes to prepare for dropping FMT_DEPRECATED_OSTREAM
  test/boost/database_test.cc
  test/lib/cql_assertions.cc
  test/unit/radix_tree_stress_test.cc
Labels: backport/none

#17678 tools/scylla-nodetool: repair: abort on first failed repair
  test/nodetool/conftest.py
  test/nodetool/rest_api_mock.py
  test/nodetool/test_backup.py
  test/nodetool/test_binary.py
  test/nodetool/test_compact.py
  test/nodetool/test_compactionhistory.py
  test/nodetool/test_compactionstats.py
  test/nodetool/test_describecluster.py
  test/nodetool/test_describering.py
  test/nodetool/test_getendpoints.py
  test/nodetool/test_gossip.py
  test/nodetool/test_gossipinfo.py
  test/nodetool/test_help.py
  test/nodetool/test_info.py
  test/nodetool/test_logging.py
  test/nodetool/test_netstats.py
  test/nodetool/test_nodeops.py
  test/nodetool/test_proxyhistograms.py
  test/nodetool/test_repair.py
  test/nodetool/test_ring.py
  test/nodetool/test_snapshot.py
  test/nodetool/test_sstable.py
  test/nodetool/test_status.py
  test/nodetool/test_stop.py
  test/nodetool/test_tablehistograms.py
  test/nodetool/test_tablestats.py
  test/nodetool/test_toppartitions.py
  test/nodetool/test_traceprobability.py
  test/nodetool/test_version.py
  test/nodetool/test_viewbuildstatus.py
  test/nodetool/utils.py
  tools/scylla-nodetool.cc
Labels: area/nodetool, area/tablets, backport/none, promoted-to-master

#18040 main: reload service levels data accessor after join_cluster
  main.cc
  service/qos/service_level_controller.cc
  service/qos/service_level_controller.hh
Labels: backport/none

#17998 test.py: test_topology_upgrade_basic: make ring_delay_ms nonzero
  test/topology/util.py
  test/topology_experimental_raft/test_topology_upgrade.py
Labels: backport/none
