Repository scylladb/scylladb, pull requests merged in 2024-11, with the labels that each got.

#21144 Collect and report backup progress
  db/snapshot/backup_task.cc
  db/snapshot/backup_task.hh
  test/object_store/test_backup.py
  utils/s3/client.cc
  utils/s3/client.hh
  utils/s3/client_fwd.hh
Labels: backport/none

#20260 repair: Reduce hints and batchlog flush
  db/batchlog_manager.cc
  db/batchlog_manager.hh
  db/config.cc
  db/config.hh
  idl/partition_checksum.idl.hh
  main.cc
  repair/repair.cc
  repair/repair.hh
  repair/row_level.cc
  repair/row_level.hh
  repair/task_manager_module.hh
  service/storage_service.cc
  test/boost/batchlog_manager_test.cc
  test/topology_custom/test_repair.py
Labels: backport/none

#20769 tasks: improve task_manager::lookup_virtual_task
  node_ops/task_manager_module.cc
  node_ops/task_manager_module.hh
  tasks/task_manager.cc
  tasks/task_manager.hh
Labels: backport/none, status/merge candidate

#21399 utils: chunked_vector: various constructor improvements
  test/boost/chunked_vector_test.cc
  utils/chunked_vector.hh
Labels: backport/none

#21398 api: Remove foreach_column_family() helper
  api/column_family.cc
  api/column_family.hh
Labels: backport/none

#20897 sstables/index_reader: avoid unnecessary index page reads in single-partition reads
  sstables/index_reader.hh
Labels: P1, backport/none

#21228 cql3: Allow for describing CDC log tables
  cql3/statements/describe_statement.cc
  docs/dev/describe_schema.md
  test/cql-pytest/test_describe.py
Labels: backport/none, area/backup and restore, status/merge candidate

#21411 treewide: trade boost's any_of and all_of for std's any_of and all_of
  alternator/conditions.cc
  alternator/executor.cc
  alternator/expressions.cc
  auth/password_authenticator.cc
  auth/roles-metadata.cc
  compaction/compaction.cc
  compaction/compaction_manager.cc
  compaction/compaction_strategy.cc
  compaction/size_tiered_compaction_strategy.hh
  cql3/functions/as_json_function.hh
  cql3/restrictions/statement_restrictions.cc
  cql3/selection/selection.cc
  cql3/statements/batch_statement.cc
  cql3/statements/delete_statement.cc
  cql3/statements/select_statement.cc
  cql3/user_types.cc
  db/view/view.cc
  db/virtual_tables.cc
  index/secondary_index_manager.cc
  partition_snapshot_row_cursor.hh
  redis/keyspace_utils.cc
  repair/repair.cc
  replica/database.cc
  streaming/stream_session.cc
  test/boost/dynamic_bitset_test.cc
  test/boost/partitioner_test.cc
  test/boost/row_cache_test.cc
  test/boost/sstable_compaction_test.cc
  test/boost/sstable_datafile_test.cc
Labels: type/code cleanup, backport/none

#21437 lang, .github: remove unused includes, add more directories to CLEANER_DIR
  .github/workflows/iwyu.yaml
  cql3/statements/describe_statement.cc
  lang/wasm.hh
Labels: area/build, backport/none

#21450 bytes_ostream: replace boost ranges with std ranges
  bytes_ostream.hh
Labels: type/code cleanup, backport/none

#21471 main,cql_test_env: start group0_service before view_builder
  api/raft.cc
  main.cc
  service/raft/raft_group_registry.cc
  test/boost/secondary_index_test.cc
  test/lib/cql_test_env.cc
Labels: P0, backport/6.2

#20815 repair: introduce and use buffer size hint for mixed-shard multishard reader
  db/config.cc
  db/config.hh
  readers/multishard.cc
  readers/multishard.hh
  repair/row_level.cc
  replica/database.cc
  replica/database.hh
  test/boost/mutation_reader_test.cc
Labels: area/repair, area/repair-based operations, backport/none

#21054 Add retries to the S3 client
  configure.py
  test.py
  test/boost/aws_error_injection_test.cc
  test/boost/aws_errors_test.cc
  test/boost/s3_test.cc
  test/pylib/s3_proxy.py
  test/pylib/s3_server_mock.py
  test/pylib/start_s3_proxy.py
  utils/CMakeLists.txt
  utils/s3/aws_error.cc
  utils/s3/aws_error.hh
  utils/s3/client.cc
  utils/s3/client.hh
  utils/s3/retry_strategy.cc
  utils/s3/retry_strategy.hh
Labels: area/test, tests/unitest, area/object storage, backport/none, area/backup and restore

#20908 compaction: use better partition estimate for split compaction
  compaction/compaction.cc
  compaction/table_state.hh
  locator/tablets.cc
  locator/tablets.hh
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  test/boost/compaction_group_test.cc
  test/lib/test_services.cc
  tools/scylla-sstable.cc
Labels: symptom/performance, P2, area/tablets, backport/none

#21560 message: do not include unused headers
  .github/workflows/iwyu.yaml
  message/messaging_service.hh
  message/messaging_service_fwd.hh
Labels: type/code cleanup, backport/none

#21153 compaction: Perform integrity checks on compacting SSTables
  compaction/compaction.cc
  sstables/checksummed_data_source.cc
  sstables/compress.cc
  sstables/data_source_types.hh
  sstables/kl/reader.cc
  sstables/kl/reader.hh
  sstables/mx/reader.cc
  sstables/mx/reader.hh
  sstables/sstable_mutation_reader.hh
  sstables/sstable_set.cc
  sstables/sstable_set.hh
  sstables/sstables.cc
  sstables/sstables.hh
  sstables/types_fwd.hh
  test/boost/sstable_compaction_test.cc
Labels: backport/none

#21601 mutation: switch from boost ranges to std ranges
  cql3/statements/prune_materialized_view_statement.cc
  mutation/mutation_partition.cc
  mutation/mutation_partition.hh
  mutation/mutation_partition_v2.cc
  mutation/mutation_partition_v2.hh
  partition_snapshot_reader.hh
  partition_snapshot_row_cursor.hh
  test/boost/row_cache_test.cc
Labels: type/code cleanup, backport/none

#21617 code cleanup: remove "sstring_view" and replace its usages by std::string_view
  alternator/executor.cc
  alternator/server.cc
  bytes.cc
  bytes.hh
  cdc/log.cc
  cdc/log.hh
  concrete_types.hh
  cql3/error_collector.hh
  cql3/expr/prepare_expr.cc
  cql3/query_options.cc
  cql3/query_options.hh
  cql3/query_processor.cc
  cql3/restrictions/statement_restrictions.cc
  cql3/statements/select_statement.cc
  cql3/util.cc
  cql3/util.hh
  data_dictionary/data_dictionary.cc
  data_dictionary/data_dictionary.hh
  db/hints/sync_point.cc
  db/hints/sync_point.hh
  db/marshal/type_parser.cc
  db/marshal/type_parser.hh
  db/view/view.cc
  db/virtual_tables.cc
  lang/lua.cc
  locator/network_topology_strategy.cc
  schema/schema.cc
  service/mapreduce_service.cc
  sstables/column_translation.hh
  sstables/mx/reader.cc
  sstables/sstable_mutation_reader.cc
  sstables/sstables.cc
  test/boost/UUID_test.cc
  test/boost/commitlog_test.cc
  test/boost/cql_query_test.cc
  test/boost/hint_test.cc
  test/boost/query_processor_test.cc
  test/boost/restrictions_test.cc
  test/boost/sstable_3_x_test.cc
  test/boost/statement_restrictions_test.cc
  test/boost/transport_test.cc
  test/lib/cql_assertions.cc
  test/lib/cql_assertions.hh
  test/lib/cql_test_env.cc
  test/lib/cql_test_env.hh
  test/lib/expr_test_utils.cc
  test/lib/expr_test_utils.hh
  tools/scylla-types.cc
  tracing/trace_keyspace_helper.cc
  tracing/trace_state.cc
  tracing/trace_state.hh
  transport/request.hh
  types/types.cc
  types/types.hh
  utils/UUID.hh
  utils/UUID_gen.cc
  utils/UUID_gen.hh
  utils/big_decimal.cc
  utils/big_decimal.hh
  utils/uuid.cc
Labels: area/internals, type/code cleanup, backport/none

#21632 test/boost/view_schema_test.cc: Wait for views to build in test_view_update_generating_writetime
  test/boost/view_schema_test.cc
Labels: area/test, area/materialized views, symptom/ci stability, backport/6.1, backport/6.2, status/merge candidate

#21616 repair: fix task_manager_module::abort_all_repairs
  repair/repair.cc
  repair/task_manager_module.hh
  test/topology_custom/test_repair.py
Labels: area/repair, backport/6.1, backport/6.2

#21125 cql3: respect PER PARTITION LIMIT for aggregate queries
  cql3/selection/selection.cc
  cql3/selection/selection.hh
  cql3/statements/select_statement.cc
  cql3/statements/select_statement.hh
  test/cqlpy/cassandra_tests/validation/operations/compact_storage_test.py
  test/cqlpy/cassandra_tests/validation/operations/select_group_by_test.py
  test/cqlpy/test_group_by.py
Labels: backport/none

#21495 treewide: replace boost::find_if with std::ranges::find_if
  alternator/executor.cc
  combine.hh
  counters.hh
  cql3/restrictions/statement_restrictions.cc
  db/size_estimates_virtual_reader.cc
  db/view/view.cc
  index/secondary_index.cc
  locator/util.cc
  replica/database.cc
  service/storage_service.cc
  service/topology_state_machine.hh
  sstables/compress.cc
  test/boost/sstable_compaction_test.cc
  test/boost/sstable_datafile_test.cc
  test/lib/data_model.cc
  test/manual/enormous_table_scan_test.cc
  tools/schema_loader.cc
  tools/scylla-nodetool.cc
  tools/scylla-sstable.cc
Labels: type/code cleanup, backport/none

#21088 Add tablet repair scheduler support
  api/api-doc/storage_service.json
  api/storage_service.cc
  db/system_keyspace.cc
  docs/dev/system_keyspace.md
  docs/dev/topology-over-raft.md
  gms/feature_service.hh
  idl/storage_service.idl.hh
  locator/network_topology_strategy.cc
  locator/tablets.cc
  locator/tablets.hh
  message/messaging_service.cc
  message/messaging_service.hh
  repair/repair.cc
  repair/row_level.hh
  replica/tablet_mutation_builder.hh
  replica/tablets.cc
  replica/tablets.hh
  service/storage_service.cc
  service/storage_service.hh
  service/tablet_allocator.cc
  service/tablet_allocator.hh
  service/topology_coordinator.cc
  test/pylib/repair.py
  test/pylib/rest_client.py
  test/topology_experimental_raft/test_tablet_repair_scheduler.py
Labels: area/repair, P1, area/tablets, backport/none

#21543 Alternator measuring RCU and WCU
  alternator/CMakeLists.txt
  alternator/consumed_capacity.cc
  alternator/consumed_capacity.hh
  alternator/executor.cc
  alternator/executor.hh
  alternator/rmw_operation.hh
  alternator/stats.cc
  alternator/stats.hh
  alternator/streams.cc
  configure.py
  test/alternator/test_metrics.py
  test/alternator/test_returnconsumedcapacity.py
Labels: backport/none

#21602 Automatically compute schema version of system tables
  db/schema_tables.cc
  db/system_distributed_keyspace.cc
  db/system_keyspace.cc
  db/system_keyspace.hh
  db/virtual_tables.cc
  docs/dev/cdc.md
  redis/keyspace_utils.cc
  replica/tablets.cc
  schema/schema.cc
  schema/schema.hh
  schema/schema_builder.hh
  test/boost/schema_change_test.cc
  test/boost/virtual_table_test.cc
  utils/hashing.hh
Labels: enhancement, backport/none

#21643 readers: migrate to std::ranges
  readers/combined.cc
  readers/multishard.cc
  readers/mutation_reader.cc
Labels: type/code cleanup, backport/none

#21207 repair: Enable small table optimization for RBNO bootstrap and decommission
  db/config.cc
  db/config.hh
  repair/repair.cc
  repair/row_level.cc
  repair/row_level.hh
  repair/task_manager_module.hh
Labels: backport/none

#21421 locator: token_metadata: replace boost range with std range
  locator/token_metadata.cc
  locator/token_metadata.hh
Labels: type/code cleanup, backport/none

#21579 test/boost/view_schema_test: Improve test_view_update_generating_writetime
  test/boost/view_schema_test.cc
Labels: area/test, backport/none

#21522 docs: update admin-tools docs with deprecation and removal notice for java tools
  docs/operating-scylla/_common/tools_index.rst
  docs/operating-scylla/admin-tools/sstabledump.rst
  docs/operating-scylla/admin-tools/sstableloader.rst
  docs/operating-scylla/admin-tools/sstablemetadata.rst
Labels: documentation, backport/6.2, status/merge candidate

#21505 tasks: add api_task_ttl for tasks started with API
  api/api-doc/task_manager.json
  api/api-doc/task_manager_test.json
  api/storage_service.cc
  api/task_manager.cc
  api/task_manager_test.cc
  api/tasks.cc
  compaction/task_manager_module.cc
  compaction/task_manager_module.hh
  conf/scylla.yaml
  db/config.cc
  db/config.hh
  db/snapshot/backup_task.cc
  db/snapshot/backup_task.hh
  docs/dev/task_manager.md
  docs/operating-scylla/admin-tools/task-manager.rst
  docs/operating-scylla/nodetool-commands/backup.rst
  docs/operating-scylla/nodetool-commands/restore.rst
  docs/operating-scylla/nodetool-commands/tasks/index.rst
  docs/operating-scylla/nodetool-commands/tasks/user-ttl.rst
  main.cc
  node_ops/task_manager_module.cc
  repair/repair.cc
  repair/task_manager_module.hh
  service/storage_service.cc
  sstables_loader.cc
  tasks/task_manager.cc
  tasks/task_manager.hh
  tasks/test_module.hh
  test/nodetool/test_tasks.py
  test/rest_api/rest_util.py
  test/rest_api/test_task_manager.py
  test/topology_tasks/task_manager_client.py
  test/topology_tasks/test_node_ops_tasks.py
  tools/scylla-nodetool.cc
Labels: backport/none, area/task-manager

#21562 replica,sstables: track download progress of download_task_impl
  sstables_loader.cc
  sstables_loader.hh
  test/object_store/suite.yaml
  test/object_store/test_backup.py
Labels: area/object storage, backport/none, area/backup and restore
