Repository scylladb/scylladb, pull requests merged in 2024-08, with the labels that each got.

#19779 tablets: load_balancer: Improve per-table balance
  locator/load_sketch.hh
  service/tablet_allocator.cc
  service/tablet_allocator.hh
  test/perf/tablet_load_balancing.cc
Labels: symptom/performance, status/regression, status/release blocker, area/tablets, backport/none

#19338 mv: delete a partition in a single operation when applicable
  db/view/view.cc
  db/view/view.hh
  test/cql-pytest/test_materialized_view.py
  test/cql-pytest/test_shedding.py
  test/cql-pytest/util.py
  view_info.hh
Labels: backport/none

#19866 Drop datadir from keyspace::config
  replica/database.cc
  replica/database.hh
  sstables/sstables_manager.cc
  sstables/storage.cc
  sstables/storage.hh
Labels: backport/none

#19982 db: coroutinize do_apply_counter_update
  replica/database.cc
  test/cql-pytest/test_counter.py
Labels: backport/none

#19983 doc: add the 6.0-to-6.1 upgrade guide
  docs/alternator/compatibility.md
  docs/architecture/_common/consistent-topology-with-raft-upgrade-info.rst
  docs/architecture/raft.rst
  docs/operating-scylla/procedures/cluster-management/_common/membership-change-failures-note.rst
  docs/operating-scylla/procedures/cluster-management/_common/system-auth-alter-info.rst
  docs/operating-scylla/procedures/cluster-management/_common/upgrade-note-add-new-dc.rst
  docs/operating-scylla/procedures/cluster-management/_common/upgrade-note-add-new-node.rst
  docs/operating-scylla/procedures/cluster-management/_common/upgrade-note-remove-node.rst
  docs/operating-scylla/procedures/cluster-management/_common/upgrade-note-replace-node.rst
  docs/operating-scylla/procedures/cluster-management/_common/upgrade-warning-add-new-node-or-dc.rst
  docs/operating-scylla/procedures/cluster-management/_common/upgrade-warning-remove-node.rst
  docs/operating-scylla/procedures/cluster-management/_common/upgrade-warning-replace-node.rst
  docs/operating-scylla/procedures/cluster-management/add-dc-to-existing-dc.rst
  docs/operating-scylla/procedures/cluster-management/add-node-to-cluster.rst
  docs/operating-scylla/procedures/cluster-management/remove-node.rst
  docs/operating-scylla/procedures/cluster-management/replace-dead-node.rst
  docs/operating-scylla/procedures/cluster-management/update-topology-strategy-from-simple-to-network.rst
  docs/operating-scylla/security/_common/upgrade-note-authentication.rst
  docs/operating-scylla/security/_common/upgrade-note-runtime-authentication.rst
  docs/operating-scylla/security/_common/upgrade-warning-authentication.rst
  docs/operating-scylla/security/_common/upgrade-warning-runtime-authentication.rst
  docs/operating-scylla/security/authentication.rst
  docs/operating-scylla/security/runtime-authentication.rst
  docs/troubleshooting/_common/enable-consistent-topology.rst
  docs/troubleshooting/_common/enabling-consistent-topology-failure.rst
  docs/troubleshooting/_common/system-auth-name-info.rst
  docs/troubleshooting/password-reset.rst
  docs/upgrade/upgrade-opensource/index.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/enable-consistent-topology.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/index.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/metric-update-5.4-to-6.0.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-6.0-to-6.1/index.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-6.0-to-6.1/metric-update-6.0-to-6.1.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-6.0-to-6.1/upgrade-guide-from-6.0-to-6.1-generic.rst
Labels: documentation, area/upgrade, backport/6.1

#20058 Coroutinize view_builder::start()
  db/view/view.cc
  db/view/view_builder.hh
Labels: backport/none

#20011 convert the rest of `test/boost/sstable_test.cc` to co-routines and seastar::thread
  test/boost/sstable_test.cc
Labels: backport/none

#18997 querier: include cell stats in page stats
  collection_mutation.cc
  collection_mutation.hh
  mutation/compact_and_expire_result.hh
  mutation/mutation_compactor.hh
  mutation/mutation_partition.cc
  mutation/mutation_partition.hh
  querier.cc
  querier.hh
  test/boost/mutation_test.cc
Labels: area/diagnostics, backport/none

#19085 service levels: update connections parameters automatically
  api/CMakeLists.txt
  api/api-doc/cql_server_test.json
  api/api.cc
  api/api_init.hh
  api/cql_server_test.cc
  api/cql_server_test.hh
  auth/maintenance_socket_role_manager.cc
  auth/maintenance_socket_role_manager.hh
  auth/role_manager.hh
  auth/standard_role_manager.cc
  auth/standard_role_manager.hh
  configure.py
  cql3/statements/list_effective_service_level_statement.cc
  generic_server.cc
  generic_server.hh
  main.cc
  service/client_state.cc
  service/qos/qos_common.cc
  service/qos/qos_common.hh
  service/qos/qos_configuration_change_subscriber.hh
  service/qos/service_level_controller.cc
  service/qos/service_level_controller.hh
  service/raft/group0_state_machine.cc
  service/raft/group0_state_machine.hh
  service/storage_service.cc
  service/storage_service.hh
  service/topology_coordinator.cc
  test/auth_cluster/test_auth_v2_migration.py
  test/auth_cluster/test_raft_service_levels.py
  test/boost/service_level_controller_test.cc
  transport/controller.cc
  transport/controller.hh
  transport/event_notifier.cc
  transport/server.cc
  transport/server.hh
  utils/sorting.hh
Labels: backport/none, area/service levels

#19995 compaction: drop compaction executors' possibility to bypass task manager
  compaction/compaction_manager.cc
  compaction/compaction_manager.hh
  compaction/task_manager_module.cc
  replica/database.hh
  replica/table.cc
  test/boost/compaction_group_test.cc
  test/boost/cql_query_large_test.cc
  test/boost/database_test.cc
  test/boost/memtable_test.cc
  test/boost/sstable_compaction_test.cc
  test/boost/view_complex_test.cc
  test/perf/perf_fast_forward.cc
Labels: backport/none

#15541 tablets: reload only changed metadata
  auth/service.cc
  cql3/query_processor.cc
  cql3/query_processor.hh
  db/schema_tables.cc
  locator/load_sketch.hh
  locator/tablets.cc
  locator/tablets.hh
  locator/token_metadata.cc
  main.cc
  mutation/canonical_mutation.cc
  mutation/canonical_mutation.hh
  replica/tablets.cc
  replica/tablets.hh
  service/migration_listener.hh
  service/migration_manager.cc
  service/raft/group0_state_machine.cc
  service/storage_service.cc
  service/storage_service.hh
  service/tablet_allocator.cc
  service/topology_coordinator.cc
  test/boost/schema_change_test.cc
  test/boost/tablets_test.cc
  test/perf/perf_tablets.cc
  test/perf/tablet_load_balancing.cc
  transport/event_notifier.cc
  transport/server.hh
Labels: enhancement, area/tablets, backport/none

#19910 cell_locker: maybe_rehash: ignore allocation failures
  cell_locking.hh
  counters.cc
Labels: backport/none

#19666 Prevent ALTERing non-existing KS with tablets
  service/topology_coordinator.cc
  test/topology_custom/test_tablets_cql.py
Labels: area/schema changes, area/tablets, backport/6.0, backport/6.1

#18842 cql: process LIMIT for GROUP BY select queries
  cql3/selection/selection.cc
  cql3/selection/selection.hh
  cql3/statements/select_statement.cc
  cql3/statements/select_statement.hh
  test/cql-pytest/test_distinct.py
  test/cql-pytest/test_group_by.py
Labels: backport/6.0, backport/6.1

#18864 Native reverse pages over RPC
  clustering_key_filter.hh
  conf/scylla.yaml
  cql3/statements/select_statement.cc
  cql3/statements/select_statement.hh
  db/config.cc
  db/config.hh
  db/virtual_table.cc
  docs/dev/reverse-reads.md
  gms/feature_service.hh
  multishard_mutation_query.cc
  mutation/frozen_mutation.cc
  mutation/frozen_mutation.hh
  mutation/mutation_partition.cc
  mutation/mutation_partition.hh
  mutation_query.cc
  mutation_query.hh
  partition_snapshot_reader.hh
  query-request.hh
  query.cc
  read_context.hh
  readers/multishard.cc
  readers/mutation_readers.cc
  readers/mutation_source.hh
  readers/reversing_v2.hh
  replica/database.cc
  replica/database.hh
  replica/memtable.cc
  replica/memtable.hh
  replica/table.cc
  row_cache.cc
  service/pager/query_pager.hh
  service/pager/query_pagers.cc
  service/storage_proxy.cc
  sstables/kl/reader.cc
  sstables/kl/reader.hh
  sstables/mx/reader.cc
  sstables/mx/reader.hh
  sstables/sstables.cc
  sstables/sstables.hh
  test/boost/counter_test.cc
  test/boost/multishard_mutation_query_test.cc
  test/boost/mutation_query_test.cc
  test/boost/mutation_reader_another_test.cc
  test/boost/mutation_reader_test.cc
  test/boost/mutation_test.cc
  test/boost/row_cache_test.cc
  test/boost/sstable_conforms_to_mutation_source_test.cc
  test/lib/mutation_source_test.cc
  utils/value_or_reference.hh
Labels: enhancement, symptom/performance, P3, area/reverse queries, backport/none, technical debt

#20119 test/nodetool: enable running nodetool tests under test/nodetool
  test/nodetool/conftest.py
Labels: area/nodetool, area/test, backport/none

#20115 replica: fix copy constructor of tablet_sstable_set
  replica/tablets.cc
  test/boost/sstable_set_test.cc
  test/boost/sstable_test.hh
Labels: bug, P2, area/tablets, backport/6.0, backport/6.1

#19427 tablets: Fix race between repair and split
  compaction/compaction_manager.cc
  compaction/compaction_manager.hh
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  service/topology_coordinator.cc
  test/boost/sstable_compaction_test.cc
  test/topology_experimental_raft/test_tablets.py
Labels: P1, backport/6.0, backport/6.1

#20135 Add CQL-based RBAC support to Alternator
  alternator/executor.cc
  alternator/server.cc
  alternator/server.hh
  alternator/streams.cc
  alternator/ttl.cc
  docs/alternator/compatibility.md
  docs/alternator/getting-started.md
  test/alternator/test_batch.py
  test/alternator/test_cql_rbac.py
  test/cql-pytest/run.py
  test/pylib/manager_client.py
  test/topology_experimental_raft/test_alternator.py
Labels: enhancement, area/security, area/alternator, type/epic, P1, backport/none

#20159 utils/tagged_integer: remove conversion to underlying integer
  db/system_keyspace.cc
  db/system_keyspace.hh
  gms/gossiper.cc
  gms/gossiper.hh
  raft/fsm.cc
  raft/log.cc
  raft/log.hh
  raft/server.cc
  raft/tracker.cc
  service/raft/raft_sys_table_storage.cc
  service/storage_service.cc
  test/raft/etcd_test.cc
  test/raft/fsm_test.cc
  test/raft/helpers.cc
  test/raft/helpers.hh
  test/raft/randomized_nemesis_test.cc
  test/raft/replication.cc
  test/raft/replication.hh
  utils/tagged_integer.hh
Labels: backport/none

#20169 test.py: use XPath for iterating in "TestSuite/TestSuite"
  test.py
Labels: type/code cleanup, tests/test.py, backport/none

#20002 tools: Enhance scylla sstable shard-of to support tablets
  configure.py
  docs/operating-scylla/admin-tools/scylla-sstable.rst
  replica/tablets.cc
  replica/tablets.hh
  test/cql-pytest/test_tools.py
  tools/CMakeLists.txt
  tools/load_system_tablets.cc
  tools/load_system_tablets.hh
  tools/read_mutation.cc
  tools/read_mutation.hh
  tools/schema_loader.cc
  tools/scylla-sstable.cc
Labels: area/scylla tools, backport/none

#20172 Coroutinize sstable_directory registry garbage collecting method
  sstables/sstable_directory.cc
Labels: backport/none

#16827 repair: do_rebuild_replace_with_repair: use source_dc only when safe
  api/api-doc/storage_service.json
  api/storage_service.cc
  docs/operating-scylla/nodetool-commands/rebuild.rst
  repair/repair.cc
  repair/repair.hh
  repair/row_level.hh
  service/storage_service.cc
  service/storage_service.hh
  test/nodetool/test_rebuild.py
  tools/scylla-nodetool.cc
  utils/to_string.cc
  utils/user_provided_param.hh
Labels: P1, backport/6.0, backport/6.1

#20120 Add ability to list S3 bucket contents
  test/boost/s3_test.cc
  utils/s3/client.cc
  utils/s3/client.hh
Labels: area/object storage, backport/none

#20194 table_helper: complete coroutinization
  table_helper.cc
  table_helper.hh
Labels: backport/none

#19758 abstract_replication_strategy: make get_ranges async
  alternator/ttl.cc
  compaction/task_manager_module.cc
  locator/abstract_replication_strategy.cc
  locator/abstract_replication_strategy.hh
  locator/tablets.cc
  repair/repair.cc
  replica/database.cc
  replica/database.hh
  replica/distributed_loader.cc
  service/storage_service.cc
  service/storage_service.hh
  test/boost/database_test.cc
  test/boost/network_topology_strategy_test.cc
  test/boost/sstable_compaction_test.cc
  test/boost/sstable_directory_test.cc
Labels: symptom/stalls, backport/6.0, backport/6.1

#20136 update CODEOWNERS
  .github/CODEOWNERS
Labels: backport/none

#20257 Make Summary support histogram with infinite bucket vlaues
  test/boost/estimated_histogram_test.cc
  utils/histogram.hh
Labels: backport/6.0, backport/6.1

#18334 mv: reject user requests by coordinator when a replica is overloaded by MVs
  db/view/node_view_update_backlog.hh
  db/view/view_update_backlog.hh
  exceptions/coordinator_result.hh
  service/storage_proxy.cc
  service/storage_proxy.hh
  test/topology_custom/test_mv_admission_control.py
  test/topology_custom/test_mv_backlog.py
Labels: backport/none

#20267 tools/testing: update dist-check to use rockylinux and adapt to cmake
  tools/testing/dist-check/dist-check.sh
  tools/testing/dist-check/docker.io/rockylinux-9.sh
  tools/testing/dist-check/docker.io/util.sh
Labels: enhancement, area/test, backport/none

#20109 select from mutation_fragments() + tablets: handle reads for non-owned partitions
  cql3/statements/select_statement.cc
  cql3/statements/select_statement.hh
  replica/mutation_dump.cc
  replica/mutation_dump.hh
  test/topology_custom/test_tablets.py
Labels: symptom/ci stability, area/tablets, symptom/crash, backport/6.0, tests/longevity-tier1, backport/6.1

#20205 alternator/executor: Use native reversed format
  alternator/executor.cc
  test/alternator/test_query.py
Labels: status/regression, area/alternator, P1, symptom/ci stability, area/reverse queries, backport/none

#20261 build: add --no-use-cmake option to configure.py
  configure.py
Labels: area/build, backport/none

#19684 add support for zero-token nodes
  cdc/generation_service.hh
  db/config.cc
  db/system_keyspace.cc
  db/virtual_tables.cc
  dht/boot_strapper.cc
  dht/range_streamer.cc
  docs/architecture/raft.rst
  gms/endpoint_state.cc
  gms/feature_service.hh
  gms/gossiper.cc
  gms/gossiper.hh
  locator/abstract_replication_strategy.cc
  locator/everywhere_replication_strategy.cc
  locator/network_topology_strategy.cc
  locator/network_topology_strategy.hh
  locator/token_metadata.cc
  locator/token_metadata.hh
  locator/topology.cc
  locator/topology.hh
  main.cc
  node_ops/node_ops_ctl.cc
  repair/repair.cc
  service/migration_manager.cc
  service/storage_proxy.cc
  service/storage_service.cc
  service/storage_service.hh
  service/tablet_allocator.cc
  service/topology_coordinator.cc
  service/topology_state_machine.cc
  service/topology_state_machine.hh
  test/boost/locator_topology_test.cc
  test/boost/network_topology_strategy_test.cc
  test/boost/storage_proxy_test.cc
  test/boost/tablets_test.cc
  test/boost/token_metadata_test.cc
  test/perf/tablet_load_balancing.cc
  test/topology/util.py
  test/topology_custom/suite.yaml
  test/topology_custom/test_tablets.py
  test/topology_custom/test_zero_token_nodes_topology_ops.py
  test/topology_experimental_raft/test_not_enough_token_owners.py
  test/topology_experimental_raft/test_topology_ops.py
  test/topology_experimental_raft/test_topology_recovery_basic.py
  test/topology_experimental_raft/test_topology_recovery_majority_loss.py
  test/topology_experimental_raft/test_zero_token_nodes_multidc.py
  test/topology_experimental_raft/test_zero_token_nodes_no_replication.py
Labels: backport/none

#20212 generic_server: convert connection tracking to seastar::gate
  configure.py
  generic_server.cc
  generic_server.hh
  test/boost/CMakeLists.txt
  test/boost/generic_server_test.cc
Labels: area/cql, backport/6.0, backport/6.1

#20305 Integrated restore
  api/api-doc/storage_service.json
  api/storage_service.cc
  dist/common/nodetool-completion
  docs/operating-scylla/nodetool-commands/restore.rst
  docs/operating-scylla/nodetool.rst
  main.cc
  replica/distributed_loader.cc
  replica/distributed_loader.hh
  sstables/sstable_directory.cc
  sstables/sstable_directory.hh
  sstables/storage.cc
  sstables_loader.cc
  sstables_loader.hh
  test/boost/s3_test.cc
  test/nodetool/test_restore.py
  test/object_store/test_backup.py
  test/pylib/rest_client.py
  tools/scylla-nodetool.cc
  utils/lister.hh
  utils/s3/client.cc
  utils/s3/client.hh
Labels: area/object storage, backport/none

#19614 nodetool: tasks: add nodetool commands to track task manager tasks
  api/api-doc/task_manager.json
  api/task_manager.cc
  docs/dev/task_manager.md
  docs/operating-scylla/nodetool-commands/tasks/abort.rst
  docs/operating-scylla/nodetool-commands/tasks/index.rst
  docs/operating-scylla/nodetool-commands/tasks/list.rst
  docs/operating-scylla/nodetool-commands/tasks/modules.rst
  docs/operating-scylla/nodetool-commands/tasks/status.rst
  docs/operating-scylla/nodetool-commands/tasks/tree.rst
  docs/operating-scylla/nodetool-commands/tasks/ttl.rst
  docs/operating-scylla/nodetool-commands/tasks/wait.rst
  docs/operating-scylla/nodetool.rst
  tasks/task_handler.cc
  tasks/task_handler.hh
  test/nodetool/conftest.py
  test/nodetool/test_help.py
  test/nodetool/test_tasks.py
  test/rest_api/test_task_manager.py
  test/topology_tasks/test_node_ops_tasks.py
  tools/scylla-nodetool.cc
  tools/utils.cc
  tools/utils.hh
Labels: backport/none

#20258 db/hints: Move the code for writing hints to a separate function
  db/hints/internal/hint_endpoint_manager.cc
  db/hints/internal/hint_endpoint_manager.hh
Labels: type/code cleanup, area/hinted handoff, backport/none

#20251 repair: throw if batchlog manager isn't initialized
  repair/row_level.cc
  test/topology_custom/test_repair.py
Labels: backport/6.0, backport/6.1

#20290 Fix node replace with inter-dc encryption enabled.
  .gitignore
  service/storage_service.cc
  test.py
  test/pylib/manager_client.py
  test/pylib/resources/scylla.crt
  test/pylib/resources/scylla.key
  test/pylib/scylla_cluster.py
  test/topology_custom/test_replace_with_encryption.py
Labels: backport/6.0, backport/6.1

#20292 Ignore seed name resolution errors during the restart of a cluster member node.
  init.cc
  init.hh
  main.cc
  test/topology/test_start_bootstrapped_with_invalid_seed.py
Labels: backport/none
