Repository scylladb/scylladb, pull requests merged in 2024-06, with the labels that each got.

#18784 repair: Introduce new primary replica selection algorithm for tablets
  locator/tablets.cc
  locator/tablets.hh
  repair/repair.cc
  service/storage_service.cc
Labels: area/repair, status/release blocker, area/tablets, backport/6.0

#18764 db/hints: Use host ID to IP mappings to choose the ep manager to drain when node is leaving
  db/hints/manager.cc
  db/hints/manager.hh
  service/storage_proxy.cc
Labels: area/hinted handoff, backport/6.0

#18927 Fail bootstrap if ip mapping is missing during double write stage
  db/schema_tables.cc
  service/storage_service.cc
  test/topology_custom/test_ip_mappings.py
Labels: backport/6.0

#19095 [Backport 6.0] storage_service: Fix race between tablet split and stats retrieval
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  service/storage_service.cc
  service/topology_coordinator.cc
  test/topology_experimental_raft/test_tablets.py
Labels: status/release blocker, backport/6.0

#18663 mv: gossip the same backlog if a different backlog was sent in a response
  db/view/node_view_update_backlog.hh
  db/view/view.cc
  service/misc_services.cc
  service/storage_proxy.cc
  service/storage_proxy.hh
  test/boost/view_schema_test.cc
Labels: area/materialized views, backport/none

#19166 Encapsulate wasm and lua management in lang::manager service
  configure.py
  cql3/query_processor.cc
  cql3/query_processor.hh
  cql3/statements/alter_keyspace_statement.cc
  cql3/statements/create_function_statement.cc
  cql3/statements/describe_statement.cc
  cql3/statements/modification_statement.cc
  db/batchlog_manager.cc
  db/schema_tables.cc
  lang/CMakeLists.txt
  lang/lua.cc
  lang/lua.hh
  lang/manager.cc
  lang/manager.hh
  lang/wasm.cc
  lang/wasm.hh
  main.cc
  replica/database.cc
  replica/database.hh
  test/lib/cql_test_env.cc
Labels: backport/none

#18729 alternator: keep TTL work in the maintenance scheduling group
  main.cc
  test/topology_experimental_raft/test_alternator.py
  test/topology_experimental_raft/test_mv_tablets.py
Labels: area/internals, P1, backport/5.4, backport/6.0

#18705 make enable_compacting_data_for_streaming_and_repair truly live-update
  api/api-doc/error_injection.json
  api/error_injection.cc
  replica/database.cc
  replica/table.cc
  test/pylib/rest_client.py
  test/topology_custom/test_repair.py
  utils/error_injection.hh
Labels: backport/5.4, backport/6.0

#19155 .github: change severity to error in clang-include-cleaner
  .github/clang-include-cleaner.json
  .github/workflows/iwyu.yaml
  alternator/executor.hh
  alternator/stats.hh
  exceptions/unrecognized_entity_exception.hh
Labels: area/build, type/code cleanup, backport/none

#19252 test: memtable_test: increase unspooled_dirty_soft_limit
  test/boost/memtable_test.cc
Labels: triage/oss, P2, symptom/ci stability, backport/5.4, tests/flaky, backport/6.0

#19230 Improve handling of outdated --experimental-features
  db/config.cc
  main.cc
  utils/enum_option.hh
Labels: backport/6.0

#19164 .github: add workflow to build with clang nightly
  .github/clang-matcher.json
  .github/workflows/clang-nightly.yaml
  .github/workflows/clang-tidy.yaml
Labels: area/build, backport/none

#19208 Register API endpoints next to corresponding services
  main.cc
Labels: backport/none

#19134 hinted handoff: migrate sync point to host ID
  db/hints/manager.cc
  db/hints/sync_point.cc
  db/hints/sync_point.hh
  idl/hinted_handoff.idl.hh
  test/boost/hint_test.cc
Labels: area/hinted handoff, backport/none, technical debt

#19169 scylla-sstable: add method to load the schema from the sstable itself
  sstables/sstables.cc
  sstables/sstables.hh
  test/boost/schema_loader_test.cc
  test/cql-pytest/test_tools.py
  test/lib/random_schema.cc
  tools/schema_loader.cc
  tools/schema_loader.hh
  tools/scylla-sstable.cc
Labels: symptom/ci stability, area/scylla tools, backport/none

#19260 Some cleanups for replica table
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
Labels: type/code cleanup, backport/none

#19269 api: do not include unused headers
  .github/workflows/iwyu.yaml
  api/authorization_cache.hh
  api/cache_service.cc
  api/cache_service.hh
  api/column_family.hh
  api/error_injection.cc
  api/raft.cc
  api/system.hh
  api/task_manager_test.hh
  api/tasks.hh
  api/token_metadata.hh
Labels: type/code cleanup, backport/none

#19255 test: servers_add: fix the expected_error parameter
  test/pylib/manager_client.py
  test/pylib/scylla_cluster.py
Labels: backport/none

#19290 build: cmake: use path to be compatible with CI
  dist/CMakeLists.txt
Labels: area/build, backport/none

#18819 cql3: always return created event in create keyspace statement
  cql3/query_processor.cc
  cql3/statements/create_keyspace_statement.cc
  cql3/statements/create_keyspace_statement.hh
  cql3/statements/create_table_statement.cc
  cql3/statements/create_table_statement.hh
  cql3/statements/create_type_statement.cc
  cql3/statements/create_type_statement.hh
  cql3/statements/create_view_statement.cc
  cql3/statements/create_view_statement.hh
  cql3/statements/schema_altering_statement.cc
  cql3/statements/schema_altering_statement.hh
  service/raft/raft_group0_client.cc
  service/raft/raft_group0_client.hh
  test/boost/cql_query_test.cc
  transport/messages/result_message.hh
  transport/messages/result_message_base.hh
Labels: area/schema changes, area/authentication, backport/none

#19337 schema: Make "describe" use extensions to string
  db/paxos_grace_seconds_extension.hh
  schema/schema.cc
  schema/schema.hh
Labels: backport/5.4, backport/6.0

#19340 doc: add 6.x.y to 6.x.z and remove 5.x.y to 5.x.z upgrade guide
  docs/upgrade/_common/upgrade-guide-from-5.x.y-to-5.x.z-ubuntu-and-debian.rst
  docs/upgrade/upgrade-opensource/index.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.x.y-to-5.x.z/index.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.x.y-to-5.x.z/upgrade-guide-from-5.x.y-to-5.x.z-debian.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.x.y-to-5.x.z/upgrade-guide-from-5.x.y-to-5.x.z-image.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.x.y-to-5.x.z/upgrade-guide-from-5.x.y-to-5.x.z-rpm.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-5.x.y-to-5.x.z/upgrade-guide-from-5.x.y-to-5.x.z-ubuntu.rst
  docs/upgrade/upgrade-opensource/upgrade-guide-from-6.x.y-to-6.x.z.rst
Labels: documentation, P1, backport/6.0

#19248 configurable maintenance (streaming) semaphore count resource limit
  db/config.cc
  db/config.hh
  reader_concurrency_semaphore.cc
  reader_concurrency_semaphore.hh
  replica/database.cc
  test/boost/reader_concurrency_semaphore_test.cc
Labels: backport/none

#19115 [test.py] Fix several issues in log gathering
  test.py
  test/object_store/conftest.py
  test/pylib/manager_client.py
  test/pylib/scylla_cluster.py
  test/topology/conftest.py
Labels: area/test, tests/test.py, backport/none

#19300 auth: reuse roles select query during cache population
  auth/service.cc
  auth/service.hh
Labels: backport/5.4, backport/6.0

#19361 utils/large_bitset: replace reserve_partial with utils::reserve_gently
  test/boost/stall_free_test.cc
  utils/chunked_vector.hh
  utils/large_bitset.cc
  utils/lsa/chunked_managed_vector.hh
  utils/stall_free.hh
Labels: backport/none

#19247 mv: fix value of the gossiped view update backlog
  db/view/view.cc
  db/view/view_update_backlog.hh
  idl/view.idl.hh
  replica/database.cc
  service/misc_services.cc
  service/storage_proxy.cc
Labels: area/materialized views, backport/none

#19305 tasks: fix tasks abort
  api/task_manager.cc
  compaction/compaction_manager.cc
  compaction/compaction_manager.hh
  repair/repair.cc
  repair/task_manager_module.hh
  tasks/task_manager.cc
  tasks/task_manager.hh
  test/rest_api/test_task_manager.py
Labels: backport/5.4, area/task-manager, backport/6.0

#19346 treewide: remove unused operator<<
  dht/decorated_key.hh
  dht/i_partitioner.cc
  gms/application_state.cc
  gms/application_state.hh
  gms/endpoint_state.cc
  gms/endpoint_state.hh
  gms/gossiper.cc
  gms/gossiper.hh
  gms/inet_address.cc
  gms/inet_address.hh
  gms/versioned_value.hh
  lang/wasm_instance_cache.cc
  node_ops/node_ops_ctl.hh
  test/boost/cdc_test.cc
  test/boost/network_topology_strategy_test.cc
  test/boost/serialization_test.cc
  test/boost/types_test.cc
  types/types.cc
  types/types.hh
Labels: type/code cleanup, backport/none

#19390 Sanitize load_meter API handlers management
  api/api.cc
  api/api_init.hh
  api/storage_service.cc
  api/storage_service.hh
  main.cc
Labels: backport/none

#18137 Reduce TWCS off-strategy space overhead
  compaction/compaction_manager.cc
  compaction/compaction_strategy.cc
  compaction/compaction_strategy.hh
  compaction/compaction_strategy_impl.hh
  compaction/compaction_strategy_type.hh
  compaction/leveled_compaction_strategy.cc
  compaction/leveled_compaction_strategy.hh
  compaction/size_tiered_compaction_strategy.cc
  compaction/size_tiered_compaction_strategy.hh
  compaction/task_manager_module.cc
  compaction/task_manager_module.hh
  compaction/time_window_compaction_strategy.cc
  compaction/time_window_compaction_strategy.hh
  replica/database.hh
  sstables/storage.cc
  sstables/storage.hh
  test/boost/sstable_compaction_test.cc
  test/boost/sstable_datafile_test.cc
Labels: area/compaction-twcs, Field-Tier1, area/compaction, backport/5.4, backport/6.0

#19350 cql3/statement/select_statement: do not parallelize single-partition aggregations
  cql3/statements/select_statement.cc
  test/boost/cql_query_test.cc
Labels: backport/5.4, backport/6.0

#19387 join_token_ring, gossip topology: recalculate sync nodes in wait_alive
  gms/gossiper.cc
  gms/gossiper.hh
  service/storage_service.cc
Labels: backport/5.4, backport/6.0

#19410 cdc: do not include unused headers
  .github/workflows/iwyu.yaml
  cdc/cdc_extension.hh
  cdc/metadata.cc
  cdc/stats.hh
Labels: type/code cleanup, backport/none

#19425 Sanitize gossiper API endpoints management
  api/api.cc
  api/api_init.hh
  api/failure_detector.cc
  api/failure_detector.hh
  api/gossiper.cc
  api/gossiper.hh
  main.cc
Labels: backport/none

#19190 Rebuild bloom filters that have bad partition estimates
  configure.py
  sstables/mx/writer.cc
  sstables/sstables.cc
  sstables/sstables.hh
  test/boost/CMakeLists.txt
  test/boost/bloom_filter_test.cc
  test/boost/sstable_datafile_test.cc
  test/lib/sstable_utils.hh
  utils/bloom_filter.cc
  utils/bloom_filter.hh
  utils/i_filter.cc
  utils/i_filter.hh
Labels: Field-Tier1, P1, backport/5.4, backport/6.0, area/bloom filter

#19377 batchlog replay: bypass tombstones generated by past replays
  cql3/query_processor.cc
  cql3/query_processor.hh
  db/batchlog_manager.cc
Labels: backport/5.4, backport/6.0

#19417 Move some /storage_proxy API endpoints to config.cc
  api/api.cc
  api/api_init.hh
  api/config.cc
  api/config.hh
  api/storage_proxy.cc
  main.cc
Labels: backport/none

#19487 [Backport 5.4] schema: Make "describe" use extensions to string #19358
  db/paxos_grace_seconds_extension.hh
  schema/schema.cc
  schema/schema.hh
  test/boost/cql_query_test.cc
Labels: backport/none

#19484 test: auth: add random tag to resources in test_auth_v2_migration
  test/auth_cluster/test_auth_v2_migration.py
  test/pylib/util.py
Labels: backport/none

#19509 [test.py] add --extra-scylla-cmdline-options argument for test.py
  test.py
  test/pylib/scylla_cluster.py
Labels: backport/none

#19528 build: update C++ standard to C++23
  CMakeLists.txt
  compaction/compaction_manager.cc
  configure.py
  main.cc
  readers/reversing_v2.hh
  replica/compaction_group.hh
  replica/table.cc
  test/lib/test_services.cc
  utils/config_file.cc
  utils/config_file.hh
Labels: area/build, backport/none

#19541 Close output_stream in get_snapshot_details() API handler
  api/storage_service.cc
Labels: backport/5.4, backport/6.0

#19542 Close output stream in task manager's API get_tasks handler
  api/task_manager.cc
Labels: backport/5.4, backport/6.0
