Repository scylladb/scylladb, pull requests merged in 2024-12, with the labels that each got.

#21582 compaction: update maintenance sstable set on scrub compaction completion
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  test/boost/sstable_compaction_test.cc
Labels: area/compaction, backport/6.1, backport/6.2, status/merge candidate

#21624 tasks: add tablet repair virtual task
  api/task_manager_test.cc
  configure.py
  node_ops/task_manager_module.cc
  node_ops/task_manager_module.hh
  service/CMakeLists.txt
  service/storage_service.cc
  service/storage_service.hh
  service/task_manager_module.cc
  service/task_manager_module.hh
  tasks/task_handler.cc
  tasks/task_manager.cc
  tasks/task_manager.hh
  tasks/virtual_task_hint.hh
  test/topology_tasks/suite.yaml
  test/topology_tasks/test_tablet_tasks.py
Labels: backport/none, status/merge candidate

#21713 topology_coordinator: introduce reload_count in topology state and use it to prevent race
  service/storage_service.cc
  service/topology_state_machine.hh
Labels: backport/6.1, backport/6.2

#21749 auth/passwords: Clean up prefix_for_scheme()
  auth/passwords.cc
  auth/passwords.hh
Labels: type/code cleanup, backport/none

#21709 Alternator add WCU for delelte item
  alternator/consumed_capacity.hh
  alternator/executor.cc
  alternator/executor.hh
  alternator/rmw_operation.hh
  alternator/stats.cc
  alternator/stats.hh
  test/alternator/test_metrics.py
  test/alternator/test_returnconsumedcapacity.py
Labels: enhancement, area/alternator, backport/none

#21761 transport/server: revert using async function in `for_each_gently()`
  generic_server.cc
  generic_server.hh
  service/client_state.cc
  service/client_state.hh
  service/qos/service_level_controller.cc
  service/qos/service_level_controller.hh
  transport/server.cc
Labels: backport/6.2

#21708 service/topology_coordinator: migrate view builder only if all nodes are up
  service/storage_service.cc
  service/topology_coordinator.cc
  test/topology_custom/test_view_build_status.py
Labels: backport/6.2

#20572 Add tablet merge support
  docs/dev/topology-over-raft.md
  gms/feature_service.hh
  locator/tablets.cc
  locator/tablets.hh
  replica/compaction_group.hh
  replica/table.cc
  scripts/tablet-mon.py
  service/storage_service.cc
  service/tablet_allocator.cc
  service/tablet_allocator.hh
  service/topology_coordinator.cc
  service/topology_state_machine.cc
  service/topology_state_machine.hh
  test/boost/tablets_test.cc
  test/topology_experimental_raft/test_tablets.py
  test/topology_experimental_raft/test_tablets_merge.py
Labels: P1, area/tablets, backport/none, area/elastic cloud

#21527 Reserve IOCBs for tool applications
  CMakeLists.txt
  configure.py
  main.cc
  tools/utils.cc
Labels: area/nodetool, backport/none, ci/requires artifact tests

#21722 truncate: commit log replay positions are not saved correctly
  replica/database.cc
  test/boost/database_test.cc
Labels: Backport candidate, area/tablets

#19789 truncate: make TRUNCATE TABLE safe with tablets
  db/system_keyspace.cc
  db/system_keyspace.hh
  docs/dev/topology-over-raft.md
  gms/feature_service.hh
  idl/storage_proxy.idl.hh
  main.cc
  message/messaging_service.cc
  message/messaging_service.hh
  service/storage_proxy.cc
  service/storage_proxy.hh
  service/storage_service.cc
  service/topology_coordinator.cc
  service/topology_mutation.cc
  service/topology_mutation.hh
  service/topology_state_machine.cc
  service/topology_state_machine.hh
  test/lib/cql_test_env.cc
  test/topology_custom/test_truncate_with_tablets.py
Labels: P2, area/tablets, backport/none

#21729 tasks: add tablet migration virtual task
  gms/feature_service.hh
  locator/tablets.cc
  locator/tablets.hh
  replica/tablet_mutation_builder.hh
  replica/tablets.cc
  service/storage_service.cc
  service/tablet_allocator.cc
  service/task_manager_module.cc
  service/task_manager_module.hh
  service/topology_coordinator.cc
  tasks/task_manager.cc
  tasks/virtual_task_hint.hh
  test/boost/tablets_test.cc
  test/topology_tasks/test_tablet_tasks.py
Labels: area/tablets, backport/none, type/task, area/task-manager

#21647 materialized view: make flow-control maximum delay configurable
  db/config.cc
  db/config.hh
  db/view/view.cc
  db/view/view_update_backlog.hh
  db/view/view_update_generator.cc
  service/misc_services.cc
  service/storage_proxy.cc
  test/topology_custom/test_mv_backlog.py
Labels: area/stability, area/materialized views, Field-Tier1, P1, backport/none

#21835 db,auth,locator: Remove unused member variables
  auth/default_authorizer.cc
  auth/default_authorizer.hh
  db/hints/resource_manager.hh
  locator/ec2_multi_region_snitch.hh
Labels: type/code cleanup, backport/none

#21948 cache_algorithm_test: fix flaky failures
  test/boost/cache_algorithm_test.cc
Labels: symptom/ci stability, backport/6.1, backport/6.2

#21927 More Python tests for materialized view and Alternator GSI feature
  test/alternator/test_cql_rbac.py
  test/alternator/test_gsi.py
  test/alternator/test_gsi_updatetable.py
  test/alternator/test_lsi.py
  test/alternator/test_metrics.py
  test/cqlpy/test_materialized_view.py
Labels: area/test, area/materialized views, backport/none

#21567 Make restore task abortable
  data_dictionary/storage_options.hh
  replica/distributed_loader.cc
  replica/distributed_loader.hh
  sstables/storage.cc
  sstables_loader.cc
  test/object_store/test_backup.py
  utils/s3/client.cc
  utils/s3/client.hh
Labels: backport/none, area/backup and restore

#21956 Do not reset quarantine list in non raft mode
  gms/gossiper.cc
  gms/gossiper.hh
Labels: area/gossip, area/topology changes, triage/master, symptom/ci stability, backport/6.1, backport/6.2

#21895 sstables_manager: do not reclaim unlinked sstables
  sstables/sstables.cc
  sstables/sstables.hh
  sstables/sstables_manager.cc
  sstables/sstables_manager.hh
  test/boost/bloom_filter_test.cc
  test/lib/sstable_test_env.hh
Labels: area/bloom filter, backport/6.1, backport/6.2, status/merge candidate

#21976 Retire topology::sort_by_proximity and compare_endpoints flavors using gms::inet_address
  locator/topology.cc
  locator/topology.hh
  test/boost/network_topology_strategy_test.cc
Labels: backport/none, status/merge candidate

#21958 Sort by proximity: shuffle equal-distance replicas
  configure.py
  locator/token_metadata.cc
  locator/token_metadata.hh
  locator/topology.cc
  locator/topology.hh
  service/storage_proxy.cc
  test/boost/network_topology_strategy_test.cc
  test/perf/CMakeLists.txt
  test/perf/perf_sort_by_proximity.cc
  utils/small_vector.hh
Labels: backport/none

#21814 Make get_built_indexes REST API endpoint be consistent with system."IndexInfo" table
  api/column_family.cc
  index/built_indexes_virtual_reader.hh
  test/cqlpy/test_materialized_view.py
  test/cqlpy/test_secondary_index.py
Labels: backport/none

#22044 topology_random_failures: deselect more cases which can cause #21534
  test/topology_random_failures/cluster_events.py
  test/topology_random_failures/error_injections.py
  test/topology_random_failures/test_random_failures.py
Labels: area/raft, tests/test.py, symptom/ci stability, backport/none

#22069 test.py: only access combined_tests executable if it is built
  test.py
Labels: backport/none

#21781 table: make update_effective_replication_map sync again
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  service/storage_service.cc
  test/topology_custom/test_mv_topology_change.py
Labels: area/materialized views, area/tablets, backport/6.1, backport/6.2

#22039 build: add support for LTO and PGO to the building system
  .gitattributes
  CMakeLists.txt
  cmake/enable_lto.cmake
  cmake/mode.common.cmake
  configure.py
  pgo/CMakeLists.txt
  pgo/conf/cassandra-rackdc.properties
  pgo/conf/clustering.yaml
  pgo/conf/counters.yaml
  pgo/conf/lwt.yaml
  pgo/conf/repair.yaml
  pgo/conf/scylla.yaml
  pgo/conf/si.yaml
  pgo/pgo.py
  pgo/train
  scripts/refresh-pgo-profiles.sh
  test/CMakeLists.txt
Labels: area/build, backport/none, status/merge candidate, area/source available

#22032 message: port advanced rpc compression from scylla-enterprise.git to scylladb.git
  CMakeLists.txt
  cmake/Findlz4.cmake
  cmake/Findzstd.cmake
  conf/scylla.yaml
  configure.py
  db/config.cc
  db/config.hh
  db/system_keyspace.cc
  db/system_keyspace.hh
  docs/dev/advanced_rpc_compression.md
  docs/dev/advanced_rpc_compression_negotiation.tla
  docs/operating-scylla/procedures/config-change/advanced-internode-compression.rst
  docs/operating-scylla/procedures/config-change/index.rst
  gms/feature_service.hh
  main.cc
  message/CMakeLists.txt
  message/dictionary_service.cc
  message/dictionary_service.hh
  message/messaging_service.cc
  message/messaging_service.hh
  service/raft/group0_state_machine.cc
  service/raft/group0_state_machine.hh
  service/raft/raft_group0.cc
  service/raft/raft_group0.hh
  service/storage_service.cc
  service/storage_service.hh
  test/boost/CMakeLists.txt
  test/boost/advanced_rpc_compressor_test.cc
  test/boost/dict_trainer_test.cc
  test/boost/reservoir_sampling_test.cc
  test/boost/stream_compressor_test.cc
  test/lib/cql_test_env.cc
  test/manual/gossip.cc
  test/manual/message.cc
  test/topology_custom/test_rpc_compression.py
  utils/CMakeLists.txt
  utils/advanced_rpc_compressor.cc
  utils/advanced_rpc_compressor.hh
  utils/advanced_rpc_compressor_protocol.hh
  utils/alien_worker.cc
  utils/alien_worker.hh
  utils/dict_trainer.cc
  utils/dict_trainer.hh
  utils/refcounted.hh
  utils/reservoir_sampling.hh
  utils/shared_dict.hh
  utils/stream_compressor.cc
  utils/stream_compressor.hh
Labels: backport/none, area/source available
