Repository scylladb/scylladb, pull requests merged in 2024-05, with the labels that each got.

#18441 Relax the way view builder code checks if a table exists
  db/view/view.cc
Labels: backport/none

#18290 Unstall merge topology snapshot
  collection_mutation.cc
  configure.py
  db/schema_tables.cc
  idl-compiler.py
  mutation/async_utils.cc
  mutation/async_utils.hh
  mutation/canonical_mutation.hh
  mutation/frozen_mutation.cc
  mutation/frozen_mutation.hh
  mutation/mutation_partition.cc
  mutation/mutation_partition.hh
  mutation/mutation_partition_serializer.cc
  mutation/mutation_partition_serializer.hh
  replica/database.cc
  replica/tablets.cc
  service/raft/group0_state_machine.cc
  service/storage_proxy.cc
  service/storage_proxy.hh
  service/storage_service.cc
  test/boost/canonical_mutation_test.cc
  test/boost/frozen_mutation_test.cc
  test/boost/mutation_test.cc
  test/perf/perf.cc
  test/perf/perf.hh
  test/perf/perf_commitlog.cc
  test/perf/perf_simple_query.cc
  utils/logalloc.cc
  utils/logalloc.hh
Labels: backport/6.0

#18261 topology_coordinator: compute cluster size correctly during upgrade
  service/topology_coordinator.cc
  test/topology_experimental_raft/test_topology_upgrade_not_stuck_after_recent_removal.py
Labels: backport/none

#18497 topology_coordinator: clear obsolete generations earlier
  service/topology_coordinator.cc
  test/topology_custom/test_raft_snapshot_request.py
  test/topology_experimental_raft/test_cdc_generation_clearing.py
Labels: backport/none

#17939 auth: don't run legacy migrations in auth-v2 mode
  auth/common.cc
  auth/common.hh
  auth/default_authorizer.cc
  auth/default_authorizer.hh
  auth/password_authenticator.cc
  auth/service.cc
  auth/service.hh
  auth/standard_role_manager.cc
  auth/standard_role_manager.hh
  test/auth_cluster/test_auth_v2_migration.py
Labels: backport/none

#18510 Coroutinize generic_server's listen() method
  generic_server.cc
Labels: backport/none

#18286 alternator: fix REST API access to an Alternator LSI
  api/api.cc
  api/collectd.cc
  api/column_family.cc
  api/compaction_manager.cc
  api/config.cc
  api/error_injection.cc
  api/failure_detector.cc
  api/gossiper.cc
  api/messaging_service.cc
  api/raft.cc
  api/storage_service.cc
  api/storage_service.hh
  api/stream_manager.cc
  api/system.cc
  api/task_manager.cc
  api/task_manager_test.cc
  api/tasks.cc
  api/token_metadata.cc
  test/alternator/test_lsi.py
Labels: type/bug, area/alternator, backport/5.2, backport/5.4

#18379 test: {auth,topology}: use manager.rolling_restart
  test/auth_cluster/test_auth_v2_migration.py
  test/auth_cluster/test_raft_service_levels.py
  test/pylib/manager_client.py
  test/pylib/scylla_cluster.py
  test/topology/util.py
  test/topology_custom/test_group0_schema_versioning.py
  test/topology_custom/test_raft_fix_broken_snapshot.py
  test/topology_custom/test_raft_recovery_basic.py
  test/topology_custom/test_raft_recovery_majority_loss.py
  test/topology_custom/test_raft_recovery_stuck.py
  test/topology_experimental_raft/test_topology_recovery_basic.py
  test/topology_experimental_raft/test_topology_recovery_majority_loss.py
Labels: backport/none

#18408 Drain view_builder in generic drain (again)
  db/view/view.cc
  db/view/view_builder.hh
  db/view/view_update_generator.cc
  db/view/view_update_generator.hh
  main.cc
  service/storage_proxy.cc
  service/storage_proxy.hh
  service/storage_service.cc
  service/storage_service.hh
  test/lib/cql_test_env.cc
Labels: backport/none

#18458 sstables: add dead row count when issuing warning to system.large_partitions
  db/large_data_handler.cc
  db/large_data_handler.hh
  db/system_keyspace.cc
  docs/dev/system_keyspace.md
  docs/troubleshooting/large-partition-table.rst
  gms/feature_service.hh
  sstables/metadata_collector.hh
  sstables/mx/writer.cc
  test/boost/sstable_3_x_test.cc
  test/lib/simple_schema.hh
Labels: scale/large partitions, area/sstable, backport/none

#18186 Reload reclaimed bloom filters when memory is available
  scylla-gdb.py
  sstables/sstables.cc
  sstables/sstables.hh
  sstables/sstables_manager.cc
  sstables/sstables_manager.hh
  test/boost/sstable_datafile_test.cc
  test/boost/sstable_directory_test.cc
  test/lib/sstable_test_env.hh
  test/lib/sstable_utils.hh
  utils/error_injection.hh
Labels: backport/5.2, backport/5.4

#18518 repair: tablet_repair: make best effort in spite of errors
  repair/repair.cc
Labels: area/repair, status/release blocker, area/tablets, backport/6.0

#18621 build: cmake build dist-unified by default and put tarballs under per-config paths
  cmake/build_submodule.cmake
  dist/CMakeLists.txt
Labels: area/build, backport/none

#17664 replica: allocate storage groups dynamically
  compaction/task_manager_module.cc
  compaction/task_manager_module.hh
  docs/dev/topology-over-raft.md
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  replica/tablets.cc
  service/topology_coordinator.cc
  test/boost/commitlog_cleanup_test.cc
  test/boost/cql_query_large_test.cc
  test/boost/sstable_3_x_test.cc
  test/boost/sstable_compaction_test.cc
  test/boost/sstable_test.hh
  test/boost/view_complex_test.cc
  test/lib/test_services.cc
  test/perf/perf_fast_forward.cc
  test/perf/perf_sstable.hh
  test/topology_custom/test_tablets_migration.py
Labels: status/release blocker, area/tablets, backport/none

#18616 Some sstable set related improvements
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  replica/tablets.cc
Labels: area/sstable, backport/none

#18476 scylla-nodetool: make documentation links product and version dependant
  cmake/add_version_library.cmake
  configure.py
  release.cc
  release.hh
  tools/scylla-nodetool.cc
Labels: area/nodetool, backport/6.0

#18467 cql/describe: hide cdc log tables
  cql3/statements/describe_statement.cc
  schema/schema.cc
  schema/schema.hh
  test/cql-pytest/test_describe.py
Labels: area/cdc, status/release blocker, backport/none, area/backup and restore

#18636 utils: chunked_vector: fill ctor: make exception safe
  test/boost/chunked_vector_test.cc
  utils/chunked_vector.hh
Labels: backport/5.2, backport/5.4

#18650 hinted handoff: Prevent segmentation fault when initializing endpoint managers
  db/hints/manager.cc
  db/hints/manager.hh
Labels: type/bug, area/hinted handoff, backport/none

#18608 scylla-nodetool: add tablet support for ring command
  api/api-doc/storage_service.json
  api/storage_service.cc
  locator/tablets.cc
  locator/tablets.hh
  service/storage_service.cc
  service/storage_service.hh
  test/nodetool/test_ring.py
  test/nodetool/test_status.py
  test/nodetool/test_tablehistograms.py
  test/nodetool/test_toppartitions.py
  tools/scylla-nodetool.cc
Labels: area/nodetool, tests/dtest, status/release blocker, area/tablets, backport/6.0

#18672 Simplify access to topology::my_address()
  main.cc
  service/qos/service_level_controller.cc
  service/qos/service_level_controller.hh
  service/storage_proxy.cc
  test/boost/service_level_controller_test.cc
  test/lib/cql_test_env.cc
  tracing/trace_keyspace_helper.cc
Labels: backport/none

#18677 repair: Don't get topology via database
  repair/row_level.cc
  repair/row_level.hh
Labels: backport/none

#16819 mv: throttle view update generation for large queries
  db/view/view.cc
  db/view/view_update_backlog.hh
  db/view/view_update_generator.cc
  db/view/view_update_generator.hh
  exceptions/exceptions.cc
  exceptions/exceptions.hh
  replica/database.hh
  replica/table.cc
  service/storage_proxy.cc
  service/storage_proxy.hh
  test/topology_custom/test_mv_delete_partitions.py
Labels: backport/none

#18695 Fix stalls in forward_service::dispatch() with large tablet count
  service/forward_service.cc
Labels: backport/none

#18667 mutation_fragment_stream_validating_filter: respect validating_level::none
  mutation/mutation_fragment_stream_validator.cc
  mutation/mutation_fragment_stream_validator.hh
  test/boost/mutation_fragment_test.cc
Labels: backport/5.2, backport/5.4, backport/6.0

#18236 fix test teardown race with ongoing test operation
  test/pylib/manager_client.py
  test/pylib/scylla_cluster.py
  test/topology/conftest.py
Labels: backport/none

#18302 Sort user-defined types in describe statements
  configure.py
  cql3/statements/describe_statement.cc
  db/cql_type_parser.cc
  db/cql_type_parser.hh
  db/schema_tables.cc
  db/schema_tables.hh
  replica/database.cc
  test/boost/CMakeLists.txt
  test/boost/sorting_test.cc
  test/cql-pytest/test_describe.py
  tools/schema_loader.cc
  types/types.cc
  types/user.hh
  utils/sorting.hh
Labels: backport/none

#18703 Improve modularity of some per-table API endpoints
  api/column_family.cc
  api/storage_service.cc
  api/storage_service.hh
  replica/database.hh
Labels: backport/none

#18721 sstables_manager: use maintenance scheduling group to run components reload fiber
  replica/database.cc
  sstables/sstables_manager.cc
  sstables/sstables_manager.hh
  test/lib/test_services.cc
Labels: backport/5.2, backport/5.4, backport/6.0

#18749 docs: update isolation.md
  docs/dev/isolation.md
Labels: type/documentation, backport/none

#18788 Coroutinize some auth and service levels related functions
  auth/service.cc
  cql3/statements/alter_service_level_statement.cc
  cql3/statements/attach_service_level_statement.cc
  cql3/statements/create_keyspace_statement.cc
  cql3/statements/create_service_level_statement.cc
  cql3/statements/create_table_statement.cc
  cql3/statements/detach_service_level_statement.cc
  cql3/statements/drop_service_level_statement.cc
  cql3/statements/grant_statement.cc
  cql3/statements/revoke_statement.cc
  cql3/statements/role-management-statements.cc
  cql3/statements/schema_altering_statement.cc
Labels: backport/none

#18866 build, test: disable operator<< for vector and unordered_map
  CMakeLists.txt
  configure.py
  db/config.cc
  db/config.hh
  db/heat_load_balance.hh
  mutation/mutation.cc
  mutation/mutation.hh
  test/boost/commitlog_test.cc
  test/boost/compound_test.cc
  test/boost/config_test.cc
  test/boost/expr_test.cc
  test/boost/flat_mutation_reader_test.cc
  test/boost/hint_test.cc
  test/boost/idl_test.cc
  test/boost/mutation_query_test.cc
  test/boost/mutation_reader_test.cc
  test/boost/mutation_test.cc
  test/boost/mutation_writer_test.cc
  test/boost/nonwrapping_interval_test.cc
  test/boost/query_processor_test.cc
  test/boost/service_level_controller_test.cc
  test/boost/sstable_resharding_test.cc
  test/boost/statement_restrictions_test.cc
  test/boost/top_k_test.cc
  test/boost/transport_test.cc
  test/boost/user_function_test.cc
  test/boost/view_build_test.cc
  test/boost/wrapping_interval_test.cc
  test/lib/test_utils.hh
  test/perf/perf_fast_forward.cc
  tools/scylla-sstable.cc
  tools/scylla-types.cc
Labels: backport/none

#18287 storage_service: Fix race between tablet split and stats retrieval
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  service/storage_service.cc
  service/topology_coordinator.cc
  test/topology_experimental_raft/test_tablets.py
Labels: symptom/ci stability, area/tablets, backport/6.0

#18706 Rework view services and system-distributed-keyspace dependencies
  db/view/view.cc
  db/view/view_builder.hh
  db/view/view_update_checks.hh
  main.cc
  repair/repair.hh
  repair/row_level.cc
  repair/row_level.hh
  replica/distributed_loader.cc
  replica/distributed_loader.hh
  sstables_loader.cc
  sstables_loader.hh
  streaming/consumer.cc
  streaming/consumer.hh
  streaming/stream_manager.cc
  streaming/stream_manager.hh
  streaming/stream_session.cc
  test/lib/cql_test_env.cc
Labels: backport/none

#18799 Do not export statement scheduling group from database
  alternator/controller.cc
  alternator/controller.hh
  api/storage_service.cc
  main.cc
  protocol_server.hh
  redis/controller.cc
  redis/controller.hh
  replica/database.hh
  test/boost/cql_query_test.cc
  test/manual/sstable_scan_footprint_test.cc
  thrift/controller.cc
  thrift/controller.hh
  transport/controller.cc
  transport/controller.hh
Labels: backport/none

#18841 qos/raft_service_level_distributed_data_accessor: print correct error message when trying to modify a service level in recovery mode
  service/qos/raft_service_level_distributed_data_accessor.cc
  test/auth_cluster/test_raft_service_levels.py
Labels: symptom/ux, area/service levels, backport/6.0

#18872 Mark prepare_statement as immutable
  cql3/statements/prepared_statement.hh
  tracing/trace_state.hh
Labels: type/code cleanup, backport/none

#18899 Fix parsing of initial tablets by ALTER
  cql3/statements/ks_prop_defs.cc
  test/cql-pytest/test_tablets.py
Labels: backport/6.0

#18890 Harden the repair_service shutdown path
  repair/row_level.cc
Labels: backport/6.0

#18928 Run sstables loader in scheduling group
  main.cc
  replica/distributed_loader.cc
  sstables_loader.cc
  sstables_loader.hh
Labels: backport/none
