Repository scylladb/scylladb, pull requests merged in 2024-02, with the labels that each got.

#17091 replica, tablet_allocator: do not compare unsigned with signed
  replica/table.cc
  service/tablet_allocator.cc
Labels: code cleanup

#17150 doc: remove the OSS and Enterprise Features pages
  docs/using-scylla/features-ent.rst
  docs/using-scylla/features-open-source.rst
  docs/using-scylla/features.rst
  docs/using-scylla/index.rst
Labels: type/documentation

#16991 types/types.cc: move stringstream content instead of copying it
  concrete_types.hh
  lang/lua.cc
  types/types.cc
Labels: type/code cleanup

#17132 Sanitize replication factor parsing by strategies
  cql3/statements/ks_prop_defs.cc
  locator/abstract_replication_strategy.cc
  locator/abstract_replication_strategy.hh
  locator/network_topology_strategy.cc
  locator/simple_strategy.cc
Labels: type/code cleanup

#17177 types: use {fmt} to format time and boolean
  types/types.cc
Labels: type/code cleanup

#17123 [Backport 5.4] Raft snapshot fixes
  api/api-doc/raft.json
  api/api.cc
  api/api_init.hh
  api/raft.cc
  api/raft.hh
  configure.py
  main.cc
  raft/fsm.cc
  raft/fsm.hh
  raft/server.cc
  raft/server.hh
  service/raft/raft_group0.cc
  service/raft/raft_sys_table_storage.cc
  test/boost/group0_cmd_merge_test.cc
  test/raft/etcd_test.cc
  test/raft/fsm_test.cc
  test/raft/helpers.cc
  test/raft/helpers.hh
  test/topology_custom/test_raft_fix_broken_snapshot.py
  test/topology_custom/test_raft_snapshot_request.py
Labels: Field-Tier1, area/raft

#17118 storage_service: Add describe_ring support for tablet table
  api/api-doc/storage_service.json
  api/storage_service.cc
  locator/load_sketch.hh
  locator/tablets.cc
  locator/tablets.hh
  repair/repair.cc
  service/storage_service.cc
  service/storage_service.hh
  service/tablet_allocator.cc
  test/boost/tablets_test.cc
Labels: area/rest api

#17163 scylla-nodetool: implement the describering command
  test/nodetool/test_describering.py
  test/nodetool/test_nodetool.py
  test/nodetool/utils.py
  tools/scylla-nodetool.cc
Labels: area/tablets

#14263 utils: managed_bytes: optimize memory usage for small buffers
  bytes_ostream.hh
  scylla-gdb.py
  sstables/index_reader.hh
  utils/managed_bytes.cc
  utils/managed_bytes.hh
  utils/mutable_view.hh
Labels: feature/enhancement

#17316 api: storage_service/natural_endpoints: add tablets support
  cql3/statements/describe_statement.cc
  db/view/view.cc
  replica/database.hh
  service/storage_service.cc
  service/storage_service.hh
  test/rest_api/test_storage_service.py
Labels: area/tablets

#17344 tools/scylla-nodetool: implement compactionstats and viewbuildstatus
  test/nodetool/test_compactionstats.py
  test/nodetool/test_viewbuildstatus.py
  tools/scylla-nodetool.cc
Labels: area/nodetool

#17417 test/nodetool: parameterize test_ring
  test/nodetool/conftest.py
  test/nodetool/test_ring.py
Labels: area/nodetool, area/test

#16927 repair: accelerate repair load_history time
  repair/row_level.cc
  repair/row_level.hh
Labels: feature/enhancement, area/repair

#17387 tools/scylla-nodetool: implement tablestats
  test/nodetool/test_tablestats.py
  tools/scylla-nodetool.cc
  utils/rjson.hh
Labels: area/nodetool

#17486 tools/scylla-nodetool: fixes to address test failures with dtest
  test/nodetool/test_toppartitions.py
  tools/scylla-nodetool.cc
Labels: area/nodetool

#17231 repair: streaming: handle no_such_column_family from remote node
  configure.py
  repair/repair.cc
  repair/table_check.cc
  repair/table_check.hh
  service/migration_manager.hh
  streaming/stream_manager.hh
  streaming/stream_session.cc
  streaming/stream_transfer_task.cc
  test/topology_custom/test_table_drop.py
Labels: Backport candidate, backport/5.4

#17437 tools/scylla-nodetool: extract and use {yaml,json}_writers
  tools/format_printers.hh
  tools/scylla-nodetool.cc
Labels: area/nodetool, type/code cleanup

#17529 test/topology_custom: test_read_repair.py: reduce run-time
  db/config.cc
  db/config.hh
  multishard_mutation_query.cc
  query-request.hh
  replica/database.cc
  replica/database.hh
  replica/mutation_dump.cc
  service/storage_proxy.cc
  test/boost/database_test.cc
  test/topology_custom/test_read_repair.py
Labels: symptom/ci stability
