Repository scylladb/scylladb, pull requests merged in 2024-09, with the labels that each got.

#20186 perf/perf_sstable: add {crawling,partitioned}_streaming modes
  test/perf/perf_sstable.cc
  test/perf/perf_sstable.hh
Labels: backport/none, tests/perf

#20334 scylla-gdb.py: lazy-evaluate the constants
  scylla-gdb.py
  test/scylla_gdb/conftest.py
  test/scylla_gdb/pytest.ini
  test/scylla_gdb/run
  test/scylla_gdb/test_misc.py
Labels: enhancement, backport/none

#19493 cql3: add option to not unify bind variables with the same name
  auth/common.cc
  cql3/Cql.g
  cql3/cql3_type.cc
  cql3/dialect.hh
  cql3/prepared_statements_cache.hh
  cql3/query_processor.cc
  cql3/query_processor.hh
  cql3/statements/alter_table_statement.cc
  cql3/statements/select_statement.cc
  cql3/util.cc
  cql3/util.hh
  db/config.cc
  db/config.hh
  db/cql_type_parser.cc
  db/schema_tables.cc
  docs/cql/cql-extensions.md
  table_helper.cc
  table_helper.hh
  test/boost/cql_auth_syntax_test.cc
  test/boost/cql_query_test.cc
  test/boost/expr_test.cc
  test/boost/statement_restrictions_test.cc
  test/cql-pytest/test_prepare.py
  test/lib/cql_test_env.cc
  tools/schema_loader.cc
  transport/server.cc
  transport/server.hh
Labels: area/cql, area/cassandra 4.x compatibility, P4, backport/6.0, backport/6.1

#20374 [Backport 6.1] Fix node replace with inter-dc encryption enabled.
  .gitignore
  service/storage_service.cc
  test.py
  test/pylib/manager_client.py
  test/pylib/resources/scylla.crt
  test/pylib/resources/scylla.key
  test/pylib/scylla_cluster.py
  test/topology_custom/test_replace_with_encryption.py
Labels: backport/6.0

#20371 tools/nodetool: improve backup and restore commands
  test/nodetool/test_backup.py
  test/nodetool/test_restore.py
  tools/scylla-nodetool.cc
Labels: enhancement, area/nodetool, backport/none

#20283 repair: row_level: coroutinize some slow-path functions
  repair/row_level.cc
Labels: backport/none

#20420 Reuse sstable::test_env::reusable_sst() helper for pre-exsting sstables
  test/boost/sstable_mutation_test.cc
  test/lib/sstable_test_env.hh
  test/lib/test_services.cc
Labels: type/code cleanup, tests/unitest, backport/none

#16223 test: randomized failure injection for Raft-based topology
  gms/gossiper.cc
  main.cc
  service/raft/raft_group0.cc
  service/storage_service.cc
  service/topology_coordinator.cc
  test/pylib/internal_types.py
  test/pylib/manager_client.py
  test/pylib/random_tables.py
  test/pylib/scylla_cluster.py
  test/topology/util.py
  test/topology_random_failures/__init__.py
  test/topology_random_failures/cluster_events.py
  test/topology_random_failures/conftest.py
  test/topology_random_failures/error_injections.py
  test/topology_random_failures/pytest.ini
  test/topology_random_failures/suite.yaml
  test/topology_random_failures/test_random_failures.py
Labels: area/test, area/raft, tests/test.py, backport/none

#20452 service/qos: remove unused marked_for_deletion field from service_level struct
  service/qos/service_level_controller.cc
  service/qos/service_level_controller.hh
Labels: backport/none

#20460 Coroutinize sstable::read_summary() method
  sstables/sstables.cc
Labels: backport/none

#19942 [test.py] Enable allure for python test
  test.py
  test/pylib/report_plugin.py
Labels: backport/none

#20114 Use yielding directory lister in sstable_directory
  sstables/sstable_directory.cc
  utils/lister.hh
Labels: backport/none

#20398 docs/dev/docker-hub.md: refresh aio-max-nr calculation
  docs/dev/docker-hub.md
Labels: documentation, backport/none

#20031 major compaction: check only sstables being compacted for tombstone garbage collection
  api/api-doc/column_family.json
  api/api-doc/storage_service.json
  api/column_family.cc
  api/storage_service.cc
  compaction/compaction.cc
  compaction/compaction_descriptor.hh
  compaction/compaction_manager.cc
  compaction/compaction_manager.hh
  compaction/task_manager_module.cc
  compaction/task_manager_module.hh
  replica/database.hh
  replica/table.cc
  test/pylib/rest_client.py
  test/topology_custom/test_major_compaction.py
  tombstone_gc.hh
  tools/scylla-nodetool.cc
Labels: area/compaction, P1, backport/none

#20488 hints: send hints with CL=ALL if target is leaving
  db/hints/internal/hint_sender.cc
  db/hints/internal/hint_sender.hh
  service/topology_coordinator.cc
  test/topology/util.py
  test/topology_custom/test_hints.py
  test/topology_experimental_raft/test_mv_tablets_replace.py
Labels: backport/6.0, backport/6.1

#19472 commitlog: Handle oversized entries
  db/commitlog/commitlog.cc
  db/commitlog/commitlog.hh
  db/commitlog/commitlog_entry.hh
  db/commitlog/commitlog_replayer.cc
  db/config.cc
  db/config.hh
  docs/dev/commitlog-file-format.md
  gms/feature_service.cc
  gms/feature_service.hh
  replica/database.cc
  test/boost/commitlog_test.cc
Labels: backport/none

#20383 Alternator: tests and other preparation towards allowing adding a GSI to an existing table
  alternator/executor.cc
  alternator/serialization.cc
  db/view/view.cc
  test/alternator/test_batch.py
  test/alternator/test_gsi.py
  test/alternator/test_item.py
  test/alternator/util.py
Labels: backport/none

#20456 Sanitize open_sstables() helper in compaction test
  test/boost/sstable_compaction_test.cc
Labels: type/code cleanup, tests/unitest, backport/none

#19745 view: move view_build_status to group0
  db/system_distributed_keyspace.cc
  db/system_keyspace.cc
  db/system_keyspace.hh
  db/view/view.cc
  db/view/view_builder.hh
  gms/feature_service.hh
  main.cc
  replica/database.cc
  replica/database.hh
  service/storage_service.cc
  service/topology_coordinator.cc
  service/topology_coordinator.hh
  test/lib/cql_test_env.cc
  test/pylib/util.py
  test/topology_custom/test_view_build_status.py
Labels: area/materialized views, area/topology changes, area/raft, P2, backport/none

#20464 repair: row_level: coroutinize more functions
  repair/row_level.cc
Labels: backport/none

#20565 doc: move Alternator in the page tree and remove it's redundant ToC
  docs/alternator/alternator.md
  docs/index.rst
Labels: documentation, area/alternator, backport/none

#20446 Improve timestamp heuristics for tombstone garbage collection
  cache_mutation_reader.hh
  collection_mutation.cc
  collection_mutation.hh
  compaction/compaction.cc
  compaction/compaction_garbage_collector.hh
  compaction/table_state.hh
  docs/dev/sstable-scylla-format.md
  docs/operating-scylla/admin-tools/scylla-sstable.rst
  mutation/atomic_cell.hh
  mutation/mutation_compactor.hh
  mutation/mutation_fragment.hh
  mutation/mutation_partition.cc
  mutation/mutation_partition.hh
  mutation/tombstone.hh
  readers/compacting.hh
  readers/mutation_readers.cc
  replica/compaction_group.hh
  replica/database.hh
  replica/memtable.cc
  replica/memtable.hh
  replica/table.cc
  sstables/disk_types.hh
  sstables/metadata_collector.hh
  sstables/mx/writer.cc
  sstables/sstables.cc
  sstables/sstables.hh
  sstables/types.hh
  test/boost/compaction_group_test.cc
  test/boost/memtable_test.cc
  test/boost/mutation_reader_another_test.cc
  test/boost/mutation_reader_test.cc
  test/boost/mutation_test.cc
  test/boost/sstable_compaction_test.cc
  test/cql-pytest/nodetool.py
  test/cql-pytest/test_compaction_tombstone_gc.py
  test/lib/test_services.cc
  tools/scylla-sstable.cc
Labels: area/materialized views, area/compaction, backport/none

#20466 Remove make_shared_schema() helper
  schema/schema.cc
  schema/schema.hh
  test/boost/broken_sstable_test.cc
  test/boost/mutation_test.cc
  test/boost/sstable_compaction_test.cc
  test/boost/sstable_datafile_test.cc
  test/boost/sstable_directory_test.cc
  test/boost/sstable_mutation_test.cc
  test/boost/sstable_test.cc
  test/boost/sstable_test.hh
  test/boost/view_build_test.cc
  test/perf/perf_sstable.hh
Labels: backport/none

#20457 Make use of async() context in sstable_mutation_test
  test/boost/sstable_mutation_test.cc
Labels: tests/unitest, backport/none

#20584 replica: ignore cleanup of deallocated storage group
  replica/compaction_group.hh
  replica/table.cc
  test/boost/tablets_test.cc
Labels: backport/6.0, backport/6.1

#20599 sstable: s/crawling_sstable_mutation_reader/sstable_full_scan_reader
  compaction/compaction.cc
  sstables/kl/reader.cc
  sstables/kl/reader.hh
  sstables/mx/reader.cc
  sstables/mx/reader.hh
  sstables/sstable_set.cc
  sstables/sstable_set.hh
  sstables/sstables.cc
  sstables/sstables.hh
  test/boost/sstable_datafile_test.cc
  test/perf/perf_sstable.cc
  test/perf/perf_sstable.hh
  tools/scylla-sstable.cc
Labels: type/code cleanup, backport/none

#16522 readers/flat_mutation_reader_v2: call set_close_required() from consume*()
  mutation/mutation.cc
  readers/mutation_reader.hh
  test/boost/repair_test.cc
  test/boost/sstable_compaction_test.cc
Labels: backport/none

#20545 reader_concurrency_semaphore: improve the diagnostics dump
  docs/dev/reader-concurrency-semaphore.md
  reader_concurrency_semaphore.cc
  test/boost/reader_concurrency_semaphore_test.cc
Labels: backport/none

#20640 Alternator: a few RBAC fixes
  alternator/controller.cc
  alternator/executor.cc
  alternator/executor.hh
  alternator/server.cc
  alternator/server.hh
  alternator/streams.cc
  alternator/ttl.cc
  test/topology_experimental_raft/test_alternator.py
Labels: bug, area/alternator, backport/none

#20672 cql3: statement_restrictions: adapt to functional style
  cql3/restrictions/statement_restrictions.cc
  cql3/restrictions/statement_restrictions.hh
  cql3/statements/modification_statement.cc
  cql3/statements/select_statement.cc
  test/boost/statement_restrictions_test.cc
Labels: area/cql, backport/none

#20493 cql_server::connection: Process rebounce message in case of multiple shard migrations
  cql3/statements/modification_statement.cc
  test/topology_custom/test_query_rebounce.py
  transport/server.cc
  transport/server.hh
Labels: backport/none

#20523 cql3/statements/select_statement: `SELECT ... USING SERVICE LEVEL`
  cql3/Cql.g
  cql3/attributes.cc
  cql3/attributes.hh
  cql3/statements/select_statement.cc
  service/qos/service_level_controller.hh
  test/cql-pytest/test_using_service_level.py
Labels: enhancement, area/cql, backport/none, area/service levels

#20681 gms: inet_address: drop unused raw_addr method and modernize comperators
  gms/inet_address.hh
Labels: backport/none

#20479 Coroutinize sstable_directory::remove_unshared_sstables()
  sstables/sstable_directory.cc
Labels: type/code cleanup, backport/none

#20614 Put sstables::test class on a diet
  test/boost/sstable_datafile_test.cc
  test/boost/sstable_test.cc
  test/lib/sstable_utils.hh
Labels: tests/unitest, backport/none

#20168 cql3: Extend DESC SCHEMA by auth and service levels
  auth/authentication_options.hh
  auth/authenticator.hh
  auth/maintenance_socket_role_manager.cc
  auth/maintenance_socket_role_manager.hh
  auth/password_authenticator.cc
  auth/password_authenticator.hh
  auth/role_manager.hh
  auth/service.cc
  auth/service.hh
  auth/standard_role_manager.cc
  auth/standard_role_manager.hh
  auth/transitional.cc
  bytes.hh
  bytes_fwd.hh
  configure.py
  cql3/CMakeLists.txt
  cql3/Cql.g
  cql3/cql3_type.cc
  cql3/description.cc
  cql3/description.hh
  cql3/functions/aggregate_fcts.cc
  cql3/functions/user_aggregate.hh
  cql3/functions/user_function.cc
  cql3/functions/user_function.hh
  cql3/role_options.hh
  cql3/statements/describe_statement.cc
  cql3/statements/describe_statement.hh
  cql3/statements/raw/describe_statement.hh
  cql3/statements/role-management-statements.cc
  cql3/util.hh
  data_dictionary/data_dictionary.cc
  data_dictionary/keyspace_element.hh
  data_dictionary/keyspace_metadata.hh
  docs/cql/cql-extensions.md
  docs/cql/cqlsh.rst
  docs/cql/describe-schema.rst
  docs/cql/index.rst
  docs/cql/non-reserved-keywords.rst
  docs/dev/describe_schema.md
  docs/operating-scylla/procedures/backup-restore/backup.rst
  docs/operating-scylla/procedures/backup-restore/restore.rst
  replica/table.cc
  schema/schema.cc
  schema/schema.hh
  service/qos/service_level_controller.cc
  service/qos/service_level_controller.hh
  service/storage_service.cc
  service/tablet_allocator.cc
  test/boost/auth_test.cc
  test/boost/cql_auth_syntax_test.cc
  test/boost/cql_query_test.cc
  test/boost/user_types_test.cc
  test/cql-pytest/test_describe.py
  test/lib/random_schema.cc
  test/lib/simple_schema.hh
  tools/schema_loader.cc
  types/types.cc
  types/types.hh
  types/user.hh
Labels: enhancement, area/cql, status/release blocker, area/authentication, backport/none, area/service levels, area/backup and restore

#20737 tablet: Fix single-sstable split when attaching new unsplit sstables
  compaction/compaction_manager.cc
  replica/table.cc
  test/topology_experimental_raft/test_tablets.py
Labels: area/tablets, backport/6.0, backport/6.1

#20661 treewide: add "table" parameter to "backup" API
  api/api-doc/storage_service.json
  api/storage_service.cc
  db/snapshot-ctl.cc
  db/snapshot-ctl.hh
  db/snapshot/backup_task.cc
  db/snapshot/backup_task.hh
  docs/dev/object_storage.md
  docs/operating-scylla/nodetool-commands/backup.rst
  test/nodetool/test_backup.py
  test/object_store/test_backup.py
  test/pylib/rest_client.py
  tools/scylla-nodetool.cc
Labels: area/object storage, backport/none, area/backup and restore

#20056 Alternator store ProvisionedThroughput
  alternator/executor.cc
  docs/alternator/compatibility.md
  test/alternator/test_provisioned_throughput.py
  test/alternator/util.py
Labels: area/alternator, backport/none

#20743 mark node as being replaced earlier
  service/storage_service.cc
  service/topology_coordinator.cc
  test/topology_custom/test_replace.py
Labels: status/regression, area/topology changes, area/tablets, backport/6.0, tests/longevity-tier1, backport/6.1, backport/6.2

#20475 Move collections stress tests from unit/ to boost/
  configure.py
  test/boost/bptree_test.cc
  test/boost/bptree_validation.hh
  test/boost/btree_test.cc
  test/boost/btree_validation.hh
  test/boost/collection_stress.hh
  test/boost/radix_tree_printer.hh
  test/boost/radix_tree_test.cc
  test/boost/tree_test_key.hh
  test/unit/CMakeLists.txt
  test/unit/bptree_compaction_test.cc
  test/unit/bptree_stress_test.cc
  test/unit/btree_compaction_test.cc
  test/unit/btree_stress_test.cc
  test/unit/radix_tree_compaction_test.cc
  test/unit/radix_tree_stress_test.cc
  test/unit/suite.yaml
Labels: tests/unitest, backport/none

#20601 Populate raft address map from gossiper on raft configuration change
  service/raft/raft_group0.cc
  service/storage_service.cc
  test/topology_custom/test_long_join.py
Labels: backport/6.0, backport/6.1, backport/6.2

#20675 Remove datadir string from table::config
  data_dictionary/data_dictionary.cc
  data_dictionary/storage_options.hh
  replica/database.cc
  replica/database.hh
  replica/distributed_loader.cc
  replica/table.cc
  sstables/storage.cc
  test/boost/database_test.cc
  test/boost/mutation_test.cc
  test/lib/test_services.cc
Labels: backport/none

#20528 scylla_raid_setup: configure SELinux file context
  dist/common/scripts/scylla_coredump_setup
  dist/common/scripts/scylla_raid_setup
Labels: backport/6.0, backport/6.1
