Repository scylladb/scylladb, pull requests merged in 2024-04, with the labels that each got.

#18058 test/cql-pytest: match error message formated using {fmt}
  test/cql-pytest/test_compaction_strategy_validation.py
Labels: area/test, backport/none

#17771 Track and limit memory used by bloom filters
  db/config.cc
  db/config.hh
  sstables/sstables.cc
  sstables/sstables.hh
  sstables/sstables_manager.cc
  sstables/sstables_manager.hh
  test/boost/sstable_datafile_test.cc
  test/cql-pytest/test_bloom_filter.py
  test/lib/sstable_test_env.hh
  test/lib/sstable_utils.hh
  test/lib/test_services.cc
Labels: backport/5.2, backport/5.4

#17994 repair: Load repair history in background
  repair/row_level.cc
  repair/row_level.hh
Labels: backport/none

#18039 auth: keep auth version in scylla_local
  auth/common.cc
  auth/service.cc
  auth/service.hh
  cql3/query_processor.hh
  db/system_keyspace.cc
  db/system_keyspace.hh
  main.cc
  service/storage_service.cc
  service/topology_coordinator.cc
  test/auth_cluster/test_auth_v2_migration.py
  test/lib/cql_test_env.cc
Labels: backport/none

#18189 test/boost: add test for writing large partition notifications
  test/boost/cql_query_large_test.cc
Labels: area/test, backport/none

#17785 repair: fix memory counting in repair
  repair/row.hh
  repair/row_level.cc
  test/boost/repair_test.cc
Labels: backport/5.2, backport/5.4

#18203 Extend tablet_transition_kind::rebuild to remove replicas
  api/api-doc/storage_service.json
  api/storage_service.cc
  locator/tablets.cc
  locator/tablets.hh
  replica/tablets.cc
  service/storage_service.cc
  service/storage_service.hh
  service/topology_coordinator.cc
  test/pylib/rest_client.py
  test/topology_custom/test_tablets_migration.py
Labels: area/tablets, backport/none

#18184 gossiper: lock local endpoint when updating heart_beat
  gms/gossiper.cc
  test/topology_custom/test_gossip_boot.py
Labels: backport/5.4

#16558 Drain view_builder in generic drain
  db/view/view.cc
  db/view/view_builder.hh
  main.cc
  service/storage_service.cc
  service/storage_service.hh
  test/lib/cql_test_env.cc
Labels: backport/none

#18147 tools/scylla-nodetool: add doc link for getsstables and sstableinfo commands
  tools/scylla-nodetool.cc
Labels: area/nodetool, backport/none

#17196 toolchain: support building an optimized clang
  .gitignore
  configure.py
  install-dependencies.sh
  tools/toolchain/Dockerfile
  tools/toolchain/README.md
  tools/toolchain/optimized_clang.sh
  tools/toolchain/prepare
Labels: area/build, backport/none

#18281 Sanitize sstables::directory_semaphore usage
  replica/database.cc
  replica/database.hh
  replica/table.cc
  sstables/sstable_directory.cc
  sstables/sstable_directory.hh
Labels: backport/none

#18335 install-dependencies.sh: add more dependencies for debian
  install-dependencies.sh
Labels: area/build, backport/none

#18317 Cleanup the way snapshot details are propagated via API
  api/storage_service.cc
  db/snapshot-ctl.cc
  db/snapshot-ctl.hh
  replica/database.cc
  replica/database.hh
  test/boost/database_test.cc
Labels: backport/none

#18414 Getting per-table snapshot size is racy wrt creating new snapshots
  api/column_family.cc
  api/storage_service.cc
  db/snapshot-ctl.cc
  db/snapshot-ctl.hh
Labels: backport/none

#18346 sstable: large data handler needs to count range tombstones as rows
  db/large_data_handler.cc
  db/large_data_handler.hh
  db/system_keyspace.cc
  docs/dev/system_keyspace.md
  docs/troubleshooting/large-partition-table.rst
  sstables/metadata_collector.hh
  sstables/mx/writer.cc
  test/boost/sstable_3_x_test.cc
Labels: scale/large partitions, area/sstable, backport/none

#18013 cql3: statements: change default tombstone_gc mode for tablets
  cql3/statements/alter_table_statement.cc
  cql3/statements/alter_view_statement.cc
  cql3/statements/cf_prop_defs.cc
  cql3/statements/cf_prop_defs.hh
  cql3/statements/create_table_statement.cc
  cql3/statements/create_view_statement.cc
  data_dictionary/data_dictionary.cc
  data_dictionary/data_dictionary.hh
  data_dictionary/impl.hh
  db/config.cc
  db/config.hh
  docs/cql/ddl.rst
  docs/dev/topology-over-raft.md
  replica/data_dictionary_impl.hh
  test/lib/cql_test_env.cc
  test/lib/expr_test_utils.cc
  test/topology/test_mv.py
  test/topology/util.py
  test/topology_experimental_raft/test_tombstone_gc.py
  tombstone_gc.cc
  tombstone_gc.hh
  tools/schema_loader.cc
Labels: area/repair, status/release blocker, area/tablets, backport/none

#18275 [github] add PR template and action to verify PR tasks was completed
  .github/pull_request_template.md
  .github/workflows/pr-check-completed-tests.yaml
Labels: backport/none

#18378 Coroutinize view_builder::stop()
  db/view/view.cc
Labels: backport/none

#18421 Move some view updating methods from table to view_update_generator
  db/view/view.cc
  db/view/view_update_generator.cc
  db/view/view_update_generator.hh
  replica/database.cc
  replica/database.hh
  replica/table.cc
Labels: backport/none

#18087 treewide: remove {dclocal_,}read_repair_chance options
  cql3/statements/cf_prop_defs.cc
  cql3/statements/cf_prop_defs.hh
  db/legacy_schema_migrator.cc
  db/schema_tables.cc
  db/system_keyspace.cc
  docs/architecture/anti-entropy/5_read_repair.png
  docs/architecture/anti-entropy/7_Read_Path_with_Probabilistic_Read_Repair.png
  docs/architecture/anti-entropy/read-repair.rst
  docs/cql/ddl.rst
  docs/kb/compaction.rst
  docs/troubleshooting/large-rows-large-cells-tables.rst
  docs/using-scylla/cassandra-compatibility.rst
  schema/schema.cc
  schema/schema.hh
  schema/schema_builder.hh
  service/storage_proxy.cc
  service/storage_proxy.hh
  test/boost/config_test.cc
  test/boost/cql_query_test.cc
  test/cql-pytest/test_describe.py
  thrift/handler.cc
Labels: type/code cleanup, backport/none

#18285 db: config: move consistent-topology-changes out of experimental and make it the default for new clusters
  cdc/generation.cc
  cdc/generation_service.hh
  conf/scylla.yaml
  db/config.cc
  db/config.hh
  db/schema_tables.cc
  db/system_keyspace.cc
  docs/architecture/raft.rst
  gms/feature_service.cc
  gms/feature_service.hh
  main.cc
  service/storage_service.cc
  service/storage_service.hh
  test/auth_cluster/suite.yaml
  test/auth_cluster/test_auth_v2_migration.py
  test/auth_cluster/test_raft_service_levels.py
  test/boost/auth_test.cc
  test/boost/config_test.cc
  test/boost/cql_query_test.cc
  test/boost/schema_change_test.cc
  test/boost/tablets_test.cc
  test/cql-pytest/run.py
  test/cql-pytest/suite.yaml
  test/lib/cql_test_env.cc
  test/perf/perf_tablets.cc
  test/pylib/scylla_cluster.py
  test/rest_api/suite.yaml
  test/topology_custom/test_boot_after_ip_change.py
  test/topology_custom/test_different_group0_ids.py
  test/topology_custom/test_gossip_boot.py
  test/topology_custom/test_group0_schema_versioning.py
  test/topology_custom/test_raft_fix_broken_snapshot.py
  test/topology_custom/test_raft_recovery_basic.py
  test/topology_custom/test_raft_recovery_majority_loss.py
  test/topology_custom/test_raft_recovery_stuck.py
  test/topology_custom/test_replace_ignore_nodes.py
  test/topology_custom/test_table_drop.py
  test/topology_custom/test_tablets.py
  test/topology_custom/test_tablets_migration.py
  test/topology_custom/test_topology_failure_recovery.py
  test/topology_custom/test_topology_remove_garbage_group0.py
  test/topology_experimental_raft/suite.yaml
  test/topology_experimental_raft/test_tablets.py
  test/topology_experimental_raft/test_topology_ops.py
  test/topology_experimental_raft/test_topology_upgrade.py
  tools/schema_loader.cc
Labels: backport/none

#18389 api/storage_service: convert runtime_error from repair to http error
  api/storage_service.cc
  repair/repair.cc
Labels: backport/none

#18439 Fix population of non-normal sstables from registry
  sstables/sstable_directory.cc
  test/object_store/test_basic.py
Labels: area/object storage, backport/none
