Repository scylladb/scylladb, pull requests merged in 2024-10, with the labels that each got.

#20864 raft_group0_client: place on a #include diet
  alternator/executor.hh
  alternator/rmw_operation.hh
  auth/certificate_authenticator.hh
  auth/common.cc
  cql3/query_processor.hh
  cql3/sets.cc
  cql3/statements/batch_statement.cc
  cql3/statements/batch_statement.hh
  cql3/statements/update_statement.cc
  data_dictionary/data_dictionary.cc
  db/auth_version.hh
  db/system_keyspace.hh
  service/migration_manager.hh
  service/qos/service_level_controller.hh
  service/raft/raft_group0_client.cc
  service/raft/raft_group0_client.hh
  service/raft/raft_group_registry.hh
  service/raft/raft_timeout.hh
  test/boost/commitlog_cleanup_test.cc
  test/boost/cql_query_test.cc
  test/boost/database_test.cc
  test/boost/group0_cmd_merge_test.cc
  test/boost/transport_test.cc
Labels: area/raft, backport/none

#20837 sstables: Fix use-after-free on page cache buffer when parsing promoted index entries across pages
  db/hints/manager.hh
  sstables/consumer.hh
  sstables/kl/reader.cc
  sstables/mx/bsearch_clustered_cursor.hh
  sstables/mx/parsers.hh
  sstables/promoted_index_blocks_reader.hh
  test/boost/cached_file_test.cc
  test/boost/index_reader_test.cc
  utils/cached_file.hh
  utils/contiguous_shared_buffer.hh
  utils/fragmented_temporary_buffer.hh
Labels: bug, area/sstable, backport/6.0, backport/6.1, backport/6.2, status/merge candidate

#20875 directories: cleanups to silence clang-tidy false alarms
  utils/directories.cc
Labels: type/code cleanup, backport/none

#20854 fix regressions of building tests with cmake
  test/boost/CMakeLists.txt
Labels: bug, status/regression, area/build, backport/none

#20869 virtual_tables: snapshots: include all snapshots
  db/virtual_tables.cc
  test/cql-pytest/nodetool.py
  test/cql-pytest/test_virtual_tables.py
Labels: bug, area/virtual table, backport/none, status/merge candidate

#20773 cql3: Make creating MV respect ID option
  cql3/statements/create_view_statement.cc
  test/cql-pytest/test_describe.py
  test/cql-pytest/test_materialized_view.py
Labels: area/materialized views, backport/none, status/merge candidate

#20756 Node replace and remove operations: Add deprecate IP addresses usage warning.
  api/storage_service.cc
  db/config.cc
  db/config.hh
  locator/token_metadata.hh
  service/storage_service.cc
  service/storage_service.hh
  test/nodetool/test_nodeops.py
  tools/scylla-nodetool.cc
Labels: backport/6.2

#20858 test: update cql/ tests to work with tablets enabled by default
  test/cql/cdc_allow_dropping_manually_created_log_test.cql
  test/cql/cdc_allow_dropping_manually_created_log_test.result
  test/cql/cdc_batch_delete_postimage_test.cql
  test/cql/cdc_batch_delete_postimage_test.result
  test/cql/cdc_compact_storage_test.cql
  test/cql/cdc_compact_storage_test.result
  test/cql/cdc_delta_modes_test.cql
  test/cql/cdc_delta_modes_test.result
  test/cql/cdc_disallow_cdc_for_counters_test.cql
  test/cql/cdc_disallow_cdc_for_counters_test.result
  test/cql/cdc_disallow_materialized_view_for_cdc_log_test.cql
  test/cql/cdc_disallow_materialized_view_for_cdc_log_test.result
  test/cql/cdc_disallow_nested_cdc_logs_test.cql
  test/cql/cdc_disallow_nested_cdc_logs_test.result
  test/cql/cdc_enable_disable_test.cql
  test/cql/cdc_enable_disable_test.result
  test/cql/cdc_static_and_clustered_rows_test.cql
  test/cql/cdc_static_and_clustered_rows_test.result
  test/cql/cdc_too_short_stream_id_test.cql
  test/cql/cdc_too_short_stream_id_test.result
  test/cql/cdc_with_lwt_test.cql
  test/cql/cdc_with_lwt_test.result
  test/cql/counters_disallow_ttl_test.cql
  test/cql/counters_disallow_ttl_test.result
  test/cql/counters_test.cql
  test/cql/counters_test.result
  test/cql/lwt_batch_test.cql
  test/cql/lwt_batch_test.result
  test/cql/lwt_batch_validation_test.cql
  test/cql/lwt_batch_validation_test.result
  test/cql/lwt_like_test.cql
  test/cql/lwt_like_test.result
  test/cql/lwt_list_test.cql
  test/cql/lwt_list_test.result
  test/cql/lwt_test.cql
  test/cql/lwt_test.result
Labels: area/tablets, backport/none

#20939 replica: Fix tombstone GC during tablet split preparation
  compaction/compaction.cc
  compaction/compaction_manager.cc
  compaction/compaction_manager.hh
  compaction/table_state.hh
  replica/database.hh
  replica/table.cc
  service/storage_service.cc
  test/boost/compaction_group_test.cc
  test/lib/test_services.cc
  test/pylib/rest_client.py
  test/topology_experimental_raft/test_tablets.py
  tools/scylla-sstable.cc
Labels: symptom/data resurrection, P1, area/tablets, backport/6.0, backport/6.1, backport/6.2

#20685 treewide: accept list of sstables in "restore" API
  api/api-doc/storage_service.json
  api/storage_service.cc
  data_dictionary/data_dictionary.cc
  data_dictionary/storage_options.hh
  replica/distributed_loader.cc
  replica/distributed_loader.hh
  sstables/sstable_directory.cc
  sstables/sstable_directory.hh
  sstables_loader.cc
  sstables_loader.hh
  test/nodetool/rest_api_mock.py
  test/nodetool/test_restore.py
  test/object_store/test_backup.py
  test/pylib/rest_client.py
  tools/scylla-nodetool.cc
Labels: area/object storage, backport/none, area/backup and restore

#20947 Do not remove objects from backup storage after restore
  sstables_loader.cc
  sstables_loader.hh
  test/object_store/test_backup.py
Labels: backport/none

#20963 db: remove unused includes
  .github/workflows/iwyu.yaml
  db/batchlog_manager.hh
  db/chained_delegating_reader.hh
  db/commitlog/commitlog.hh
  db/commitlog/commitlog_extensions.hh
  db/commitlog/replay_position.hh
  db/config.hh
  db/consistency_level.hh
  db/cql_type_parser.hh
  db/data_listeners.hh
  db/extensions.hh
  db/functions/aggregate_function.hh
  db/functions/scalar_function.hh
  db/heat_load_balance.hh
  db/hints/internal/hint_endpoint_manager.hh
  db/hints/internal/hint_sender.hh
  db/hints/manager.hh
  db/hints/resource_manager.hh
  db/rate_limiter.hh
  db/system_keyspace_view_types.hh
  db/tags/utils.hh
  db/view/build_progress_virtual_reader.hh
  db/view/node_view_update_backlog.hh
  db/view/view_builder.hh
  db/view/view_update_generator.hh
  utils/hashers.hh
  utils/i_filter.hh
Labels: type/code cleanup, backport/none

#20946 Fix sstables registry mock
  test/lib/test_services.cc
Labels: backport/none

#20968 clang-format: adjustments to avoid unwanted refactors and better match the Seastar coding style
  .clang-format
Labels: backport/none

#20892 time_window_compaction_strategy: estimated_pending_compactions: reestimate compactions rather than using cached value
  compaction/time_window_compaction_strategy.cc
  compaction/time_window_compaction_strategy.hh
  test/cql-pytest/test_compaction.py
Labels: backport/none

#20208 cql: improve validating RF's change in ALTER tablets KS
  cql3/statements/alter_keyspace_statement.cc
  cql3/statements/ks_prop_defs.cc
  cql3/statements/ks_prop_defs.hh
  cql3/statements/property_definitions.hh
  test/cql-pytest/test_tablets.py
  test/topology_custom/test_tablets.py
Labels: backport/6.0, backport/6.1, backport/6.2

#20816 cql3: Print arguments and return type without frozen when describing UDF
  cql3/functions/user_function.cc
  test/cql-pytest/test_describe.py
Labels: area/udf, backport/6.0, area/backup and restore, backport/6.1, backport/6.2

#20891 Wait for all users of group0 server to complete before destroying it
  main.cc
  service/raft/raft_group0.cc
  service/raft/raft_group0.hh
  service/storage_service.cc
  service/storage_service.hh
  service/topology_coordinator.cc
Labels: backport/6.2

#20518 Make sure S3 upload completion parses possible error
  configure.py
  test.py
  test/boost/CMakeLists.txt
  test/boost/aws_error_injection_test.cc
  test/boost/aws_errors_test.cc
  test/pylib/s3_server_mock.py
  test/pylib/start_s3_mock.py
  utils/CMakeLists.txt
  utils/s3/aws_error.cc
  utils/s3/aws_error.hh
  utils/s3/client.cc
Labels: area/object storage, backport/none

#20720 sstables: Add digest checking in the validation path of the sstable layer
  compaction/compaction_manager.cc
  compaction/compaction_manager.hh
  sstables/checksummed_data_source.cc
  sstables/checksummed_data_source.hh
  sstables/compress.cc
  sstables/compress.hh
  sstables/data_source_types.hh
  sstables/shareable_components.hh
  sstables/sstables.cc
  sstables/sstables.hh
  test/boost/sstable_compaction_test.cc
  test/boost/sstable_test.cc
  test/resource/sstables/3.x/lz4/integrity_check/invalid_checksums/me-1-big-CompressionInfo.db
  test/resource/sstables/3.x/lz4/integrity_check/invalid_checksums/me-1-big-Data.db
  test/resource/sstables/3.x/lz4/integrity_check/invalid_checksums/me-1-big-Digest.crc32
  test/resource/sstables/3.x/lz4/integrity_check/invalid_checksums/me-1-big-Filter.db
  test/resource/sstables/3.x/lz4/integrity_check/invalid_checksums/me-1-big-Index.db
  test/resource/sstables/3.x/lz4/integrity_check/invalid_checksums/me-1-big-Statistics.db
  test/resource/sstables/3.x/lz4/integrity_check/invalid_checksums/me-1-big-Summary.db
  test/resource/sstables/3.x/lz4/integrity_check/invalid_checksums/me-1-big-TOC.txt
  test/resource/sstables/3.x/lz4/integrity_check/invalid_digest/me-1-big-CompressionInfo.db
  test/resource/sstables/3.x/lz4/integrity_check/invalid_digest/me-1-big-Data.db
  test/resource/sstables/3.x/lz4/integrity_check/invalid_digest/me-1-big-Digest.crc32
  test/resource/sstables/3.x/lz4/integrity_check/invalid_digest/me-1-big-Filter.db
  test/resource/sstables/3.x/lz4/integrity_check/invalid_digest/me-1-big-Index.db
  test/resource/sstables/3.x/lz4/integrity_check/invalid_digest/me-1-big-Statistics.db
  test/resource/sstables/3.x/lz4/integrity_check/invalid_digest/me-1-big-Summary.db
  test/resource/sstables/3.x/lz4/integrity_check/invalid_digest/me-1-big-TOC.txt
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_checksums/me-1-big-CRC.db
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_checksums/me-1-big-Data.db
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_checksums/me-1-big-Digest.crc32
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_checksums/me-1-big-Filter.db
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_checksums/me-1-big-Index.db
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_checksums/me-1-big-Statistics.db
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_checksums/me-1-big-Summary.db
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_checksums/me-1-big-TOC.txt
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_digest/me-1-big-CRC.db
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_digest/me-1-big-Data.db
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_digest/me-1-big-Digest.crc32
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_digest/me-1-big-Filter.db
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_digest/me-1-big-Index.db
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_digest/me-1-big-Statistics.db
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_digest/me-1-big-Summary.db
  test/resource/sstables/3.x/uncompressed/integrity_check/invalid_digest/me-1-big-TOC.txt
Labels: backport/none

#20788 compaction: fix potential data resurrection with file-based migration
  replica/compaction_group.hh
  replica/table.cc
  test/topology_experimental_raft/test_tablets.py
Labels: area/compaction, area/tablets, backport/6.0, backport/6.1, backport/6.2, status/merge candidate

#21017 repair: Fix stall in repair_get_row_diff_with_rpc_stream_process_op_slow_path
  repair/repair.hh
  repair/row_level.cc
Labels: backport/none

#20394 raft: fast tombstone GC for group0-managed tables
  compaction/compaction_manager.cc
  compaction/compaction_manager.hh
  configure.py
  db/config.cc
  db/config.hh
  db/schema_tables.cc
  db/system_keyspace.cc
  gms/application_state.cc
  gms/application_state.hh
  gms/endpoint_state.hh
  gms/gossiper.cc
  gms/gossiper.hh
  gms/versioned_value.cc
  gms/versioned_value.hh
  replica/database.cc
  replica/table.cc
  schema/schema.hh
  service/CMakeLists.txt
  service/raft/group0_state_id_handler.cc
  service/raft/group0_state_id_handler.hh
  service/raft/group0_state_machine.cc
  service/raft/group0_state_machine.hh
  service/raft/raft_group0.cc
  service/state_id.hh
  service/storage_service.cc
  test/boost/group0_test.cc
  test/topology/util.py
  test/topology_experimental_raft/test_tombstone_gc.py
  tombstone_gc.cc
  tombstone_gc.hh
Labels: backport/none

#20851 storage_proxy: Add conditions checking to avoid UB in speculating read executors.
  db/consistency_level.cc
  locator/abstract_replication_strategy.hh
  locator/everywhere_replication_strategy.cc
  locator/everywhere_replication_strategy.hh
  locator/local_strategy.cc
  locator/local_strategy.hh
  locator/network_topology_strategy.cc
  locator/network_topology_strategy.hh
  locator/simple_strategy.cc
  locator/simple_strategy.hh
  service/storage_proxy.cc
  test/topology_custom/test_change_replication_factor_1_to_0.py
  tools/build_info.hh
Labels: backport/6.0, backport/6.1, backport/6.2

#20998 Use table id as system.sstables partition key
  data_dictionary/data_dictionary.cc
  data_dictionary/storage_options.hh
  db/system_keyspace.cc
  db/system_keyspace.hh
  db/system_keyspace_sstables_registry.hh
  sstables/sstable_directory.cc
  sstables/sstable_directory.hh
  sstables/sstables.hh
  sstables/sstables_registry.hh
  sstables/storage.cc
  test/lib/test_services.cc
  test/object_store/test_basic.py
Labels: backport/none

#21020 Check system.tablets update before putting it into the table
  main.cc
  replica/tablets.cc
  replica/tablets.hh
  service/raft/raft_group0_client.cc
  service/raft/raft_group0_client.hh
  test/lib/cql_test_env.cc
Labels: P1, area/tablets, backport/6.0, backport/6.1, backport/6.2

#21061 [Backport 6.2] compaction: fix potential data resurrection with file-based migration
  replica/compaction_group.hh
  replica/table.cc
  test/topology_experimental_raft/test_tablets.py
Labels: backport/none

#20962 Sanitize compaction manager API endpoints
  api/api.cc
  api/api_init.hh
  api/compaction_manager.cc
  api/compaction_manager.hh
  api/storage_service.cc
  main.cc
Labels: backport/none

#20137 cql: create default superuser if it doesn't exist
  auth/maintenance_socket_role_manager.cc
  auth/maintenance_socket_role_manager.hh
  auth/role_manager.hh
  auth/service.cc
  auth/service.hh
  auth/standard_role_manager.cc
  auth/standard_role_manager.hh
  main.cc
  test/topology_experimental_raft/test_restart_cluster.py
Labels: backport/none

#21118 micro-updates to documentation development, on python-poetry
  docs/Makefile
  docs/README.md
Labels: backport/none

#21119 raft: consider the gossiper state then sending the group0 state id
  service/raft/group0_state_id_handler.cc
  test/topology_experimental_raft/test_tombstone_gc.py
Labels: backport/none

#21143 interval: replace boost ranges with std ranges
  db/size_estimates_virtual_reader.cc
  interval.hh
Labels: type/code cleanup, backport/none

#18939 Allow specifying TLS options with internode_encryption=none + add "transitional" mode
  docs/operating-scylla/security/node-node-encryption.rst
  main.cc
  message/messaging_service.cc
  message/messaging_service.hh
  test/topology/test_tls.py
Labels: documentation, type/epic, backport/none

#21053 Sanitize commitlog API endpoints
  api/api.cc
  api/api_init.hh
  api/commitlog.cc
  api/commitlog.hh
  api/storage_service.cc
  main.cc
Labels: backport/none

#21122 schema: convert from boost ranges to std ranges
  alternator/executor.cc
  alternator/streams.cc
  alternator/ttl.cc
  compound_compat.hh
  cql3/selection/selection.cc
  cql3/statements/alter_table_statement.cc
  cql3/statements/batch_statement.cc
  cql3/statements/create_view_statement.cc
  cql3/statements/select_statement.cc
  db/schema_tables.cc
  db/view/view.cc
  partition_slice_builder.cc
  replica/table.cc
  schema/schema.cc
  schema/schema.hh
  sstables/mx/writer.cc
  test/lib/random_schema.cc
Labels: type/code cleanup, backport/none

#21131 build: build seastar as an external project
  CMakeLists.txt
  api/CMakeLists.txt
  cmake/FindSeastar.cmake
  configure.py
  dist/CMakeLists.txt
  redis/CMakeLists.txt
  test/perf/CMakeLists.txt
  utils/CMakeLists.txt
Labels: area/build, backport/none

#21182 test/boost: stop using ranges::to()
  test/boost/mutation_reader_test.cc
  test/boost/view_build_test.cc
  utils/ranges.hh
Labels: type/code cleanup, backport/none

#19950 Update get_description.py script
  scripts/get_description.py
  scripts/metrics-config.yml
Labels: backport/none

#20887 mv: add a dedicated read concurrency semaphore for view update read before writes
  db/config.cc
  db/config.hh
  db/view/view.cc
  replica/database.cc
  replica/database.hh
  replica/table.cc
  scylla-gdb.py
  test/lib/cql_test_env.cc
  test/pylib/scylla_cluster.py
  test/topology_custom/test_mv_read_concurrency.py
Labels: area/materialized views, symptom/out of memory, symptom/overload, P1, backport/none

#21212 Remove all_datadirs vector of strings from table::config
  replica/database.cc
  replica/database.hh
  replica/distributed_loader.cc
  replica/table.cc
  sstables/sstables_manager.cc
  sstables/sstables_manager.hh
  sstables/storage.cc
  sstables/storage.hh
Labels: backport/none

#20985 replica/table: check memtable before discarding tombstone during read
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  test/pylib/rest_client.py
  test/topology_custom/test_compacting_reader_tombstone_gc.py
Labels: symptom/data resurrection, P1, backport/6.0, backport/6.1, backport/6.2, status/merge candidate

#21098 test.py: Add option to fail after number of failures
  test.py
  test/pylib/scylla_cluster.py
Labels: area/test, tests/test.py, backport/none, status/merge candidate

#21121 cql/tablets: fix retrying ALTER tablets KEYSPACE
  service/topology_coordinator.cc
  test/topology_custom/test_tablets_cql.py
Labels: backport/6.0, backport/6.1, backport/6.2

#21139 Do not leak S3 file-uploading parts on exceptions
  utils/s3/client.cc
Labels: backport/none

#21237 dht: remove unused #includes
  .github/workflows/iwyu.yaml
  dht/i_partitioner.hh
  dht/murmur3_partitioner.hh
  dht/token.hh
Labels: type/code cleanup, backport/none

#21256 [Backport 6.2] cql/tablets: fix retrying ALTER tablets KEYSPACE
  service/topology_coordinator.cc
  test/topology/util.py
  test/topology_custom/test_tablets_cql.py
Labels: bug, area/raft, symptom/ci stability

#20481 Report rows_merged in compaction_history rest api and nodetool
  api/compaction_manager.cc
  compaction/compaction.cc
  compaction/compaction.hh
  compaction/compaction_manager.cc
  readers/combined.cc
  readers/combined.hh
  readers/combined_reader_stats.hh
  sstables/sstable_set.cc
  sstables/sstable_set.hh
  test/boost/mutation_reader_test.cc
  test/nodetool/test_compactionhistory.py
  test/rest_api/test_compactionhistory.py
  tools/scylla-nodetool.cc
Labels: backport/none

#21255 Squash some sstables::test helpers
  test/boost/sstable_test.cc
  test/lib/sstable_utils.hh
Labels: type/code cleanup, tests/unitest, backport/none, status/merge candidate

#21000 docs/alternator: explain service discovery HTTP requests
  docs/alternator/alternator.md
  docs/alternator/new-apis.md
Labels: documentation, area/alternator, backport/none

#21252 repair: Fix finished ranges metrics for removenode
  repair/repair.cc
  test/topology_custom/test_node_ops_metrics.py
Labels: area/repair, area/repair-based operations, area/topology changes, backport/6.0, backport/6.1, backport/6.2

#20909 fix nodetool status to show zero-token nodes
  api/token_metadata.cc
  locator/token_metadata.cc
  locator/token_metadata.hh
  service/topology_coordinator.cc
  test/nodetool/test_status.py
  test/pylib/util.py
  test/topology/test_coordinator_queue_management.py
  test/topology/test_nodetool.py
  tools/scylla-nodetool.cc
Labels: backport/6.2

#21280 tasks: fix virtual tasks children
  tasks/task_manager.cc
Labels: area/task-manager, backport/6.2

#20729 Allow explicitly enabling or disabling tablets when creating a new keyspace
  alternator/executor.cc
  cql3/statements/create_keyspace_statement.cc
  cql3/statements/create_keyspace_statement.hh
  cql3/statements/ks_prop_defs.cc
  cql3/statements/ks_prop_defs.hh
  data_dictionary/data_dictionary.cc
  db/config.cc
  db/system_keyspace.cc
  docs/architecture/tablets.rst
  gms/feature_service.cc
  redis/keyspace_utils.cc
  service/migration_manager.cc
  service/storage_service.cc
  service/tablet_allocator.cc
  test/boost/tablets_test.cc
  test/topology_custom/test_tablets.py
  test/topology_experimental_raft/test_topology_upgrade.py
  test/topology_experimental_raft/test_topology_upgrade_not_stuck_after_recent_removal.py
  tools/schema_loader.cc
Labels: documentation, P1, area/tablets, backport/none, status/merge candidate

#21323 utils: cached_file: Mark permit as awaiting on page miss
  utils/cached_file.hh
Labels: symptom/performance, area/sstable, backport/6.0, backport/6.1, backport/6.2

#21374 gms: remove unused #includes
  .github/workflows/iwyu.yaml
  auth/standard_role_manager.hh
  gms/endpoint_state.cc
  gms/feature.hh
  gms/feature_service.hh
  gms/gossip_digest.hh
  gms/gossip_digest_ack.hh
  gms/gossip_digest_ack2.hh
  gms/gossip_digest_syn.hh
  gms/gossiper.cc
  gms/gossiper.hh
  gms/inet_address.hh
  service/load_broadcaster.hh
Labels: type/code cleanup, backport/none, status/merge candidate

#21382 compound_compat: replace use of boost ranges with std ranges
  api/column_family.cc
  compound_compat.hh
  db/view/view.cc
  gms/versioned_value.cc
  keys.cc
  mutation/mutation_partition.cc
  mutation/mutation_partition_v2.cc
  readers/mutation_reader.cc
  sstables/mx/parsers.hh
  sstables/sstable_set.cc
  sstables/sstables.cc
  sstables/writer.hh
  test/boost/compound_test.cc
  test/boost/counter_test.cc
  test/boost/schema_change_test.cc
  test/lib/data_model.cc
  test/perf/perf_commitlog.cc
  tracing/trace_state.cc
Labels: backport/none
