Repository scylladb/scylladb, pull requests merged in 2024-07, with the labels that each got.

#19557 Do not expire local addres in raft address map since the local node cannot disappear
  service/storage_service.cc
  test/topology_custom/test_long_join.py
Labels: backport/6.0

#19571 [Backport 5.4] Close output stream in task manager's API get_tasks handler
  api/task_manager.cc
Labels: backport/none

#19018 reader_concurrency_semaphore: make CPU concurrency configurable
  db/config.cc
  db/config.hh
  reader_concurrency_semaphore.cc
  reader_concurrency_semaphore.hh
  replica/database.cc
  test/boost/reader_concurrency_semaphore_test.cc
Labels: symptom/performance, area/internals, backport/5.4, backport/6.0

#19581 compaction: not include unused headers
  .github/workflows/iwyu.yaml
  compaction/compaction.cc
  compaction/compaction.hh
  compaction/compaction_backlog_manager.hh
  compaction/compaction_descriptor.hh
  compaction/compaction_manager.hh
  compaction/compaction_strategy.hh
  compaction/size_tiered_compaction_strategy.hh
  compaction/task_manager_module.hh
  replica/compaction_group.hh
  test/boost/sstable_compaction_test.cc
Labels: type/code cleanup, backport/none

#18976 service/storage_proxy: Add metrics keeping track of incoming hints
  db/hints/internal/common.hh
  db/hints/internal/hint_sender.cc
  db/hints/manager.cc
  service/storage_proxy.cc
  service/storage_proxy_stats.hh
  test/topology_experimental_raft/test_fencing.py
Labels: area/hinted handoff, backport/6.0

#19016 repair/streaming: enable toggling tombstone gc with a config item
  db/config.cc
  db/config.hh
  replica/database.cc
  replica/database.hh
  replica/table.cc
  test/topology_custom/test_repair.py
Labels: area/repair, P1, backport/none

#19597 Add API for read barrier
  api/api-doc/raft.json
  api/raft.cc
  service/raft/group0_state_machine.cc
  service/raft/raft_group_registry.cc
  service/raft/raft_group_registry.hh
  test/pylib/rest_client.py
  test/topology_custom/test_table_desc_read_barrier.py
Labels: backport/none

#19617 mutation_partition_v2: in apply_monotonically(), avoid bad_alloc on sentinel insertion
  mutation/mutation_partition_v2.cc
  test/boost/logalloc_test.cc
  utils/allocation_strategy.hh
  utils/logalloc.cc
Labels: symptom/out of memory, area/row cache, backport/5.4, backport/6.0

#19518 cql: forbid having counter columns in tablets tables
  cql3/statements/create_keyspace_statement.cc
  cql3/statements/create_table_statement.cc
  docs/alternator/alternator.md
  docs/using-scylla/cdc/index.rst
  docs/using-scylla/counters.rst
  docs/using-scylla/lwt.rst
  test/cql-pytest/cassandra_tests/batch_test.py
  test/cql-pytest/cassandra_tests/functions/cast_fcts_test.py
  test/cql-pytest/cassandra_tests/validation/entities/counters_test.py
  test/cql-pytest/cassandra_tests/validation/entities/secondary_index_test.py
  test/cql-pytest/cassandra_tests/validation/operations/compact_storage_test.py
  test/cql-pytest/cassandra_tests/validation/operations/select_test.py
  test/cql-pytest/test_cast_data.py
  test/cql-pytest/test_counter.py
  test/cql-pytest/test_describe.py
  test/cql-pytest/test_tools.py
  test/cql-pytest/test_unset.py
  test/cql-pytest/test_wasm.py
  test/topology_experimental_raft/test_fencing.py
  tools/schema_loader.cc
Labels: area/counters, area/tablets, backport/6.0

#19668 transport, service: move definition of destructors into .cc
  service/storage_service.cc
  service/storage_service.hh
  transport/server.cc
  transport/server.hh
Labels: type/code cleanup, backport/none

#18758 service_level_controller: update configuration on raft change
  main.cc
  service/qos/service_level_controller.cc
  service/qos/service_level_controller.hh
  service/raft/group0_state_machine.cc
  service/raft/group0_state_machine.hh
  service/storage_service.cc
  service/storage_service.hh
  test/cql-pytest/test_service_levels.py
  test/lib/cql_test_env.cc
  test/lib/unit_test_raft_service_levels_accessor.hh
  test/lib/unit_test_service_levels_accessor.hh
Labels: backport/none, area/service levels

#19469 replica: remove rwlock for protecting iteration over storage group map
  api/column_family.cc
  compaction/compaction_manager.cc
  db/virtual_tables.cc
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  scylla-gdb.py
  test/boost/commitlog_test.cc
  test/boost/memtable_test.cc
  test/boost/mutation_test.cc
  test/lib/sstable_utils.cc
  test/lib/sstable_utils.hh
  test/perf/perf_fast_forward.cc
  test/topology_experimental_raft/test_tablets.py
Labels: status/regression, area/topology changes, area/raft, backport/6.0

#19670 scylla-housekeeping: fix exception on parsing version string v2
  dist/common/scripts/scylla-housekeeping
Labels: backport/none

#19695 sstables: fix some mixups between the writer's schema and the sstable's schema
  sstables/mx/writer.cc
  sstables/sstables.cc
  test/boost/sstable_3_x_test.cc
Labels: Field-Tier2, area/compaction, P1, backport/5.4, backport/6.0, backport/6.1

#19766 Apply sstable io error handler to exceptions generated when opening file
  service/storage_service.cc
  service/storage_service.hh
  sstables/sstables.cc
  test/boost/memtable_test.cc
  test/lib/cql_test_env.cc
  test/lib/cql_test_env.hh
Labels: backport/none

#19699 Fix lwt semaphore guard accounting
  service/paxos/paxos_state.hh
  service/storage_proxy.cc
  test/topology_custom/test_lwt_semaphore.py
Labels: backport/5.4, backport/6.0, backport/6.1

#19453 sstables/index_reader: abort reading during shutdown
  configure.py
  main.cc
  replica/database.cc
  replica/database.hh
  sstables/index_reader.hh
  sstables/sstables.cc
  sstables/sstables_manager.cc
  sstables/sstables_manager.hh
  test/boost/CMakeLists.txt
  test/boost/index_reader_test.cc
  test/lib/cql_test_env.cc
  test/lib/sstable_test_env.hh
  test/lib/test_services.cc
  tools/schema_loader.cc
  tools/scylla-sstable.cc
Labels: backport/none

#19721 sstable::open_sstable: pass origin from the writer
  sstables/mx/writer.cc
  sstables/sstables.cc
  sstables/sstables.hh
  test/lib/sstable_utils.hh
Labels: backport/none

#19741 db/hints: Test `manager::too_many_in_flight_hints_for()`
  db/hints/internal/hint_endpoint_manager.cc
  db/hints/manager.cc
  db/hints/manager.hh
  test/topology_custom/test_hints.py
Labels: area/test, area/hinted handoff, backport/none

#19647 Improve constness of functions schema code
  cql3/functions/functions.cc
  cql3/functions/functions.hh
  test/lib/cql_test_env.cc
Labels: backport/none

#19771 test: raft: fix the flaky `test_raft_recovery_stuck`
  test/topology_custom/test_raft_recovery_stuck.py
Labels: backport/6.0, backport/6.1

#19624 keep table directory open for flushing
  sstables/storage.cc
  sstables/storage.hh
  test/boost/sstable_test.cc
  test/lib/sstable_utils.hh
Labels: backport/none, CI in progress

#19717 sstables: do not reload components of unlinked sstables
  sstables/sstables.cc
  sstables/sstables_manager.cc
  sstables/sstables_manager.hh
  test/boost/bloom_filter_test.cc
  test/boost/suite.yaml
  test/lib/sstable_test_env.hh
Labels: backport/5.4, backport/6.0, backport/6.1

#15971 commitlog: Add optional max lifetime parameter to cl instance
  db/commitlog/commitlog.cc
  db/commitlog/commitlog.hh
  db/config.cc
  db/config.hh
  replica/database.cc
  test/boost/commitlog_test.cc
Labels: backport/none

#19792 config: round-trip boolean configuration variables
  db/config.cc
  test/cql-pytest/test_virtual_tables.py
  utils/config_file_impl.hh
Labels: area/diagnostics, backport/none

#16387 s3/client: add client::upload_file()
  test/boost/s3_test.cc
  utils/s3/client.cc
  utils/s3/client.hh
Labels: area/object storage, backport/none

#16374 tasks: introduce virtual tasks
  CMakeLists.txt
  api/api-doc/task_manager.json
  api/task_manager.cc
  api/task_manager_test.cc
  configure.py
  db/system_keyspace.cc
  db/system_keyspace.hh
  docs/dev/task_manager.md
  gms/feature_service.hh
  main.cc
  message/messaging_service.cc
  message/messaging_service.hh
  node_ops/task_manager_module.cc
  node_ops/task_manager_module.hh
  repair/repair.cc
  service/storage_service.cc
  service/storage_service.hh
  service/topology_mutation.cc
  service/topology_mutation.hh
  tasks/task_handler.cc
  tasks/task_handler.hh
  tasks/task_manager.cc
  tasks/task_manager.hh
  test/lib/cql_test_env.cc
  test/pylib/rest_client.py
  test/rest_api/test_repair_task.py
  test/topology_tasks/__init__.py
  test/topology_tasks/conftest.py
  test/topology_tasks/pytest.ini
  test/topology_tasks/suite.yaml
  test/topology_tasks/task_manager_client.py
  test/topology_tasks/task_manager_types.py
  test/topology_tasks/test_node_ops_tasks.py
Labels: backport/none

#19913 mapreduce_service: complete coroutinization
  service/mapreduce_service.cc
Labels: backport/none

#19860 raft: fix the shutdown phase being stuck
  auth/common.cc
  auth/common.hh
  auth/password_authenticator.cc
  auth/service.cc
  auth/standard_role_manager.cc
  service/migration_manager.cc
  service/qos/service_level_controller.cc
  service/raft/raft_group0_client.cc
  service/raft/raft_group0_client.hh
  service/raft/raft_group_registry.cc
  service/raft/raft_group_registry.hh
  service/storage_service.cc
  service/topology_coordinator.cc
  test/boost/group0_test.cc
  test/lib/cql_test_env.cc
Labels: backport/5.4, backport/6.0, backport/6.1
