Repository scylladb/scylladb, pull requests merged in 2025-06, with the labels that each got.

#24306 test.py: fix metrics gathering
  test/pylib/resource_gather.py
Labels: tests/test.py, backport/none

#23802 test/boost: Adjust tests to RF-rack-valid keyspaces
  test/boost/tablets_test.cc
  test/lib/cql_test_env.cc
Labels: tests/test.py, area/tablets, backport/2025.1, backport/2025.2

#24307 test.py: refactor test facades for better error handling
  test/pylib/cpp/boost/boost_facade.py
  test/pylib/cpp/unit/unit_facade.py
Labels: tests/test.py, backport/none

#24034 [Backport 2025.1] Alternator WCU tracking in batch_write_item
  alternator/consumed_capacity.cc
  alternator/consumed_capacity.hh
  alternator/executor.cc
  alternator/stats.cc
  alternator/stats.hh
  test/alternator/test_metrics.py
  test/alternator/test_returnconsumedcapacity.py
Labels: backport/2025.1

#24046 Add Support for Per-Table Metrics in Alternator
  alternator/executor.cc
  alternator/executor.hh
  alternator/rmw_operation.hh
  alternator/stats.cc
  alternator/stats.hh
  replica/database.hh
  test/alternator/test_metrics.py
Labels: area/alternator, backport/none

#24231 test: dtest: move audit_test.py to test.py
  test/cluster/dtest/audit_test.py
  test/cluster/dtest/ccmlib/scylla_cluster.py
  test/cluster/dtest/tools/cluster.py
  test/cluster/dtest/tools/data.py
  test/cluster/suite.yaml
Labels: backport/none, status/merge candidate

#24494 [backport 2025.1] alternator: fix schema "concurrent modification" errors
  alternator/executor.cc
  db/tags/utils.cc
  test/topology_custom/test_alternator.py
Labels: backport/none

#22894 test.py: Integrate pytest c++ test execution to test.py
  test.py
  test/boost/CMakeLists.txt
  test/boost/test_config.yaml
  test/ldap/CMakeLists.txt
  test/ldap/test_config.yaml
  test/pylib/cpp/common_cpp_conftest.py
  test/pylib/cpp/ldap/__init__.py
  test/pylib/suite/__init__.py
  test/pylib/suite/boost.py
  test/pylib/suite/ldap.py
  test/pylib/suite/unit.py
  test/raft/CMakeLists.txt
  test/raft/test_config.yaml
  test/unit/CMakeLists.txt
  test/unit/test_config.yaml
Labels: area/test, tests/test.py, backport/none

#24312 s3_client: Refactor `range` class for state validation
  test/boost/s3_test.cc
  utils/s3/client.cc
  utils/s3/client.hh
Labels: area/object storage, backport/none

#23538 test: introduce upgrade tests to test.py, add a SSTable dict compression upgrade test
  test.py
  test/cluster/conftest.py
  test/cluster/test_sstable_compression_dictionaries_upgrade.py
  test/pylib/manager_client.py
  test/pylib/scylla_cluster.py
  test/pylib/suite/python.py
  test/pylib/suite/topology.py
  tools/toolchain/dbuild
Labels: status/merge candidate, backport/2025.2

#24527 main: don't start maintenance auth service if not enabled
  main.cc
  test/cluster/test_config_live_updates.py
Labels: backport/6.2, backport/2025.1, backport/2025.2

#24451 Fix for cassandra role gets recreated after DROP ROLE
  auth/common.cc
  auth/common.hh
  auth/ldap_role_manager.cc
  auth/password_authenticator.cc
  auth/password_authenticator.hh
  auth/service.cc
  auth/standard_role_manager.cc
  auth/standard_role_manager.hh
  test/cluster/auth_cluster/test_auth_after_reset.py
  test/cluster/auth_cluster/test_auth_default_superuser_replaced.py
  test/pylib/internal_types.py
  test/pylib/manager_client.py
  test/pylib/scylla_cluster.py
Labels: backport/6.2, backport/2025.1, backport/2025.2

#24583 docs: document the new recovery procedure
  docs/architecture/raft.rst
  docs/operating-scylla/procedures/cluster-management/_common/membership-change-failures-note.rst
  docs/operating-scylla/procedures/cluster-management/handling-membership-change-failures.rst
  docs/operating-scylla/procedures/cluster-management/index.rst
  docs/troubleshooting/_common/enable-consistent-topology.rst
  docs/troubleshooting/_common/enabling-consistent-topology-failure.rst
  docs/troubleshooting/handling-node-failures.rst
Labels: documentation, status/merge candidate, backport/2025.2

#24658 audit: introduce debug level logs on happy path
  audit/audit.cc
  test/cluster/dtest/audit_test.py
Labels: backport/none, status/merge candidate

#24677 test.py: enhance allure reporting
  test/pylib/cpp/facade.py
  test/pylib/manager_client.py
Labels: tests/test.py, backport/none

#24597 alternator: improve, document and test table/index name lengths
  alternator/executor.cc
  docs/alternator/compatibility.md
  test/alternator/test_gsi.py
  test/alternator/test_gsi_updatetable.py
  test/alternator/test_lsi.py
  test/alternator/test_streams.py
  test/alternator/test_table.py
  test/alternator/util.py
Labels: documentation, backport/none

#24497 mutation: check key of inserted rows
  compound.hh
  mutation/mutation_partition.cc
  mutation/mutation_partition.hh
  mutation/mutation_partition_v2.cc
  test/boost/mutation_test.cc
  test/boost/row_cache_test.cc
Labels: backport/2025.1, backport/2025.2
