Repository scylladb/scylladb, pull requests merged in 2025-05, with the labels that each got.

#23806 sstables: Fix quadratic space complexity in partitioned_sstable_set
  compaction/compaction.cc
  compaction/compaction_manager.cc
  compaction/compaction_strategy.cc
  compaction/compaction_strategy.hh
  compaction/compaction_strategy_impl.hh
  compaction/incremental_compaction_strategy.hh
  compaction/leveled_compaction_strategy.hh
  compaction/table_state.hh
  compaction/time_window_compaction_strategy.hh
  db/view/view_update_generator.cc
  dht/i_partitioner.cc
  dht/i_partitioner.hh
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  sstables/sstable_set.cc
  sstables/sstable_set.hh
  sstables/sstable_set_impl.hh
  sstables_loader.cc
  test/boost/compaction_group_test.cc
  test/boost/mutation_reader_test.cc
  test/boost/partitioner_test.cc
  test/boost/sstable_compaction_test.cc
  test/boost/sstable_datafile_test.cc
  test/boost/sstable_set_test.cc
  test/cluster/test_sstable_set.py
  test/lib/sstable_test_env.hh
  test/lib/test_services.cc
  test/perf/perf_sstable.hh
  tools/scylla-sstable.cc
  utils/error_injection.hh
Labels: area/memory footprint, symptom/out of memory, P1, backport/6.2, backport/2025.1

#23815 Simplify test/sstable_assertions class API
  test/boost/sstable_3_x_test.cc
Labels: type/code cleanup, backport/none, status/merge candidate

#23808 sstables_loader: fix the racing between get_progress() and release_resources()
  sstables_loader.cc
Labels: backport/none, status/merge candidate

#23783 test/boost/multishard_mutation_query_test: fix test_read_with_partition_row_limits
  test/boost/multishard_mutation_query_test.cc
Labels: tests/unitest, symptom/ci stability, backport/none

#23888 raft: make sure to retain the existing voters including the current leader (topology coordinator)
  service/raft/group0_voter_calculator.hh
  service/raft/group0_voter_handler.cc
  test/boost/group0_voter_calculator_test.cc
  test/cluster/test_raft_voters.py
Labels: backport/none

#23941 Alternator batch_write_item wcu
  alternator/consumed_capacity.cc
  alternator/consumed_capacity.hh
  alternator/executor.cc
  alternator/stats.cc
  alternator/stats.hh
  test/alternator/test_metrics.py
  test/alternator/test_returnconsumedcapacity.py
Labels: backport/2025.1

#23680 replica: Fix use-after-free with concurrent schema change and sstable set update
  replica/table.cc
  sstables/sstable_set.cc
  test/cluster/test_tablets2.py
Labels: bug, symptom/ci stability, symptom/crash, backport/6.2, backport/2025.1, backport/2025.2

#23156 transport: storage_proxy: release ERM when waiting for query timeout
  exceptions/coordinator_result.hh
  exceptions/exceptions.hh
  generic_server.cc
  generic_server.hh
  service/mapreduce_service.cc
  service/storage_proxy.cc
  test/cluster/test_long_query_timeout_erm.py
  test/pylib/manager_client.py
  transport/server.cc
  transport/server.hh
Labels: backport/none

#23590 compress: make sstable compression dictionaries NUMA-aware
  compress.cc
  compress.hh
  configure.py
  init.cc
  main.cc
  sstable_dict_autotrainer.cc
  sstables/sstable_compressor_factory.hh
  test/boost/CMakeLists.txt
  test/boost/mutation_test.cc
  test/boost/sstable_compaction_test.cc
  test/boost/sstable_compressor_factory_test.cc
  test/boost/sstable_datafile_test.cc
  test/boost/sstable_move_test.cc
  test/lib/cql_test_env.cc
  test/lib/sstable_test_env.hh
  test/lib/test_services.cc
  test/perf/perf_sstable.cc
  test/perf/perf_sstable.hh
  tools/load_system_tablets.cc
  tools/schema_loader.cc
  tools/scylla-sstable.cc
Labels: backport/none

#24000 Correctly skip updating node's own ip address due to oudated gossiper data
  service/storage_service.cc
  test/cluster/test_change_ip.py
Labels: symptom/ci stability, tests/flaky, backport/2025.1, backport/2025.2

#24030 logalloc_test: don't test performance in test background_reclaim
  test/boost/logalloc_test.cc
  utils/logalloc.cc
  utils/logalloc.hh
Labels: P2, symptom/ci stability, backport/2025.1, backport/2025.2

#23661 test/cluster: Adjust tests to RF-rack-valid keyspaces
  test/cluster/object_store/test_backup.py
  test/cluster/random_failures/cluster_events.py
  test/cluster/random_failures/test_random_failures.py
  test/cluster/suite.yaml
  test/cluster/test_change_ip.py
  test/cluster/test_change_rpc_address.py
  test/cluster/test_conflicting_keys_read_repair.py
  test/cluster/test_data_resurrection_in_memtable.py
  test/cluster/test_fencing.py
  test/cluster/test_global_ignore_nodes.py
  test/cluster/test_long_query_timeout_erm.py
  test/cluster/test_multidc.py
  test/cluster/test_not_enough_token_owners.py
  test/cluster/test_raft_recovery_user_data.py
  test/cluster/test_read_repair.py
  test/cluster/test_remove_rpc_client_with_pending_requests.py
  test/cluster/test_repair.py
  test/cluster/test_replace.py
  test/cluster/test_reversed_queries_during_simulated_upgrade_process.py
  test/cluster/test_rpc_compression.py
  test/cluster/test_select_from_mutation_fragments.py
  test/cluster/test_snapshot.py
  test/cluster/test_sstable_compression_dictionaries_autotrain.py
  test/cluster/test_sstable_compression_dictionaries_basic.py
  test/cluster/test_tablet_repair_scheduler.py
  test/cluster/test_tablets.py
  test/cluster/test_tablets2.py
  test/cluster/test_tablets_cql.py
  test/cluster/test_tablets_migration.py
  test/cluster/test_tablets_removenode.py
  test/cluster/test_tls.py
  test/cluster/test_tombstone_gc.py
  test/cluster/test_topology_ops.py
  test/cluster/test_topology_ops_encrypted.py
  test/cluster/test_topology_remove_decom.py
  test/cluster/test_topology_smp.py
  test/cluster/test_zero_token_nodes_multidc.py
  test/cluster/test_zero_token_nodes_no_replication.py
  test/cluster/test_zero_token_nodes_topology_ops.py
  test/pylib/repair.py
Labels: backport/2025.1, backport/2025.2

#23625 compress: fix an internal error when a specific debug log is enabled
  compress.cc
  test/cluster/test_sstable_compression_dictionaries_basic.py
Labels: backport/none, status/merge candidate

#24123 raft_sys_table_storage: avoid temp buffer when deserializing log_entry
  serializer_impl.hh
  service/raft/raft_sys_table_storage.cc
Labels: backport/none

#24139 Add ability to skip SSTables cleanup when loading them
  api/api-doc/storage_service.json
  api/storage_service.cc
  docs/operating-scylla/nodetool-commands/cleanup.rst
  docs/operating-scylla/nodetool-commands/refresh.rst
  replica/distributed_loader.cc
  replica/distributed_loader.hh
  sstables_loader.cc
  sstables_loader.hh
  test/nodetool/test_refresh.py
  tools/scylla-nodetool.cc
Labels: backport/none, area/backup and restore

#24105 Refactor out code from `test_restore_with_streaming_scopes`
  test/cluster/object_store/test_backup.py
Labels: backport/none

#24162 utils: chunked_vector: add some modifiers
  test/boost/chunked_vector_test.cc
  utils/chunked_vector.hh
Labels: backport/none

#21580 test.py: migrate alternator_tests.py from dtest suite
  test/cluster/dtest/alternator/__init__.py
  test/cluster/dtest/alternator/snapshot/scylla4.0.rc1/manifest.json
  test/cluster/dtest/alternator/snapshot/scylla4.0.rc1/mc-1-big-CompressionInfo.db
  test/cluster/dtest/alternator/snapshot/scylla4.0.rc1/mc-1-big-Data.db
  test/cluster/dtest/alternator/snapshot/scylla4.0.rc1/mc-1-big-Digest.crc32
  test/cluster/dtest/alternator/snapshot/scylla4.0.rc1/mc-1-big-Filter.db
  test/cluster/dtest/alternator/snapshot/scylla4.0.rc1/mc-1-big-Index.db
  test/cluster/dtest/alternator/snapshot/scylla4.0.rc1/mc-1-big-Scylla.db
  test/cluster/dtest/alternator/snapshot/scylla4.0.rc1/mc-1-big-Statistics.db
  test/cluster/dtest/alternator/snapshot/scylla4.0.rc1/mc-1-big-Summary.db
  test/cluster/dtest/alternator/snapshot/scylla4.0.rc1/mc-1-big-TOC.txt
  test/cluster/dtest/alternator/snapshot/scylla4.0.rc1/schema.cql
  test/cluster/dtest/alternator/utils/__init__.py
  test/cluster/dtest/alternator/utils/data_generator.py
  test/cluster/dtest/alternator/utils/schemas.py
  test/cluster/dtest/alternator_tests.py
  test/cluster/dtest/alternator_utils.py
  test/cluster/dtest/ccmlib/__init__.py
  test/cluster/dtest/ccmlib/common.py
  test/cluster/dtest/ccmlib/scylla_cluster.py
  test/cluster/dtest/ccmlib/scylla_node.py
  test/cluster/dtest/conftest.py
  test/cluster/dtest/dtest_class.py
  test/cluster/dtest/dtest_config.py
  test/cluster/dtest/dtest_setup.py
  test/cluster/dtest/dtest_setup_overrides.py
  test/cluster/dtest/error_example_test.py
  test/cluster/dtest/tools/__init__.py
  test/cluster/dtest/tools/cluster.py
  test/cluster/dtest/tools/context.py
  test/cluster/dtest/tools/env.py
  test/cluster/dtest/tools/log_utils.py
  test/cluster/dtest/tools/misc.py
  test/cluster/dtest/tools/retrying.py
  test/cluster/dtest/tools/sslkeygen.py
  test/cluster/random_failures/test_random_failures.py
  test/cluster/suite.yaml
  test/cluster/test_cdc_generation_clearing.py
  test/cluster/test_coordinator_queue_management.py
  test/cluster/test_hints.py
  test/cluster/test_major_compaction.py
  test/cluster/test_raft_voters.py
  test/cluster/test_replace.py
  test/cluster/test_tablets.py
  test/pylib/log_browsing.py
  test/pylib/manager_client.py
  test/pylib/rest_client.py
  test/pylib/scylla_cluster.py
  test/pylib/suite/python.py
  test/pytest.ini
Labels: area/test, tests/dtest, area/alternator, tests/test.py, backport/none

#23720 index: implement schema management layer for vector search indexes
  cql3/statements/create_index_statement.cc
  cql3/statements/index_prop_defs.cc
  index/secondary_index_manager.cc
  index/secondary_index_manager.hh
  replica/schema_describe_helper.hh
  schema/schema.cc
  schema/schema.hh
  test/boost/secondary_index_test.cc
  test/cqlpy/test_vector_index.py
Labels: area/cql, backport/none, area/vector

#21288 Extend compaction_history table with additional compaction statistics
  api/api-doc/compaction_manager.json
  api/compaction_manager.cc
  compaction/compaction.cc
  compaction/compaction.hh
  compaction/compaction_garbage_collector.hh
  compaction/compaction_manager.cc
  compaction/compaction_manager.hh
  db/compaction_history_entry.hh
  db/read_context.hh
  db/system_keyspace.cc
  db/system_keyspace.hh
  docs/operating-scylla/nodetool-commands/compactionhistory.rst
  gms/feature_service.hh
  mutation/mutation_compactor.hh
  mutation/mutation_partition.cc
  mutation/mutation_tombstone_stats.hh
  readers/compacting.hh
  readers/mutation_readers.cc
  replica/table.cc
  sstables/basic_info.hh
  test/boost/mutation_test.cc
  test/boost/sstable_compaction_test.cc
  test/cqlpy/test_compaction.py
  test/cqlpy/util.py
  test/nodetool/test_compactionhistory.py
  test/rest_api/test_compactionhistory.py
  tools/scylla-nodetool.cc
Labels: enhancement, area/diagnostics, Field-Tier2, area/compaction, good first issue, P2, backport/none, technical debt, status/merge candidate

#24159 Remove req_params facility from API
  api/api.cc
  api/api.hh
  api/column_family.cc
  api/storage_service.cc
  api/storage_service.hh
  api/tasks.cc
  test/rest_api/test_storage_service.py
Labels: backport/none, status/merge candidate

#24205 token_range_vector: fragment
  dht/i_partitioner_fwd.hh
  idl/streaming.idl.hh
  message/messaging_service.hh
  partition_range_compat.hh
  streaming/stream_request.hh
Labels: symptom/latency, Field-Tier2, backport/none

#24287 tablets: fix missing data after tablet merge
  replica/table.cc
  replica/tablets.cc
  sstables/sstable_set.cc
  test/boost/sstable_set_test.cc
  test/cluster/test_tablets_merge.py
Labels: area/rolling upgrades, P1, status/release blocker, backport/2025.1, backport/2025.2
