Repository scylladb/scylladb, pull requests merged in 2025-02, with the labels that each got.

#22372 service: add child for tablet repair virtual task
  repair/repair.cc
  repair/row_level.hh
  repair/task_manager_module.hh
  service/storage_service.cc
  service/task_manager_module.cc
  test/topology_tasks/test_tablet_tasks.py
Labels: backport/none

#22516 cql: clean the code validating replication strategy options
  data_dictionary/data_dictionary.cc
  locator/abstract_replication_strategy.cc
  locator/abstract_replication_strategy.hh
  locator/everywhere_replication_strategy.cc
  locator/everywhere_replication_strategy.hh
  locator/local_strategy.cc
  locator/local_strategy.hh
  locator/network_topology_strategy.cc
  locator/network_topology_strategy.hh
  locator/simple_strategy.cc
  locator/simple_strategy.hh
  locator/tablet_replication_strategy.hh
  locator/tablets.cc
  test/cql/locator_test.result
  test/cqlpy/cassandra_tests/validation/operations/alter_test.py
  test/cqlpy/test_keyspace.py
Labels: backport/none, status/merge candidate

#22655 config: prevent SIGHUP from changing non-liveupdatable parameters
  test/pylib/rest_client.py
  test/topology_custom/test_config.py
  utils/config_file.cc
  utils/config_file.hh
  utils/config_file_impl.hh
Labels: backport/none

#21830 s3 client: add aws credentials providers
  configure.py
  docs/dev/object_storage.md
  docs/operating-scylla/admin.rst
  main.cc
  sstables/sstables_manager.cc
  sstables/sstables_manager.hh
  test/boost/aws_error_injection_test.cc
  test/boost/s3_test.cc
  test/lib/test_services.cc
  test/perf/perf_s3_client.cc
  test/pylib/s3_server_mock.py
  utils/CMakeLists.txt
  utils/s3/client.cc
  utils/s3/client.hh
  utils/s3/credentials_providers/aws_credentials_provider.cc
  utils/s3/credentials_providers/aws_credentials_provider.hh
  utils/s3/credentials_providers/aws_credentials_provider_chain.cc
  utils/s3/credentials_providers/aws_credentials_provider_chain.hh
  utils/s3/credentials_providers/config_file_aws_credentials_provider.cc
  utils/s3/credentials_providers/config_file_aws_credentials_provider.hh
  utils/s3/credentials_providers/environment_aws_credentials_provider.cc
  utils/s3/credentials_providers/environment_aws_credentials_provider.hh
  utils/s3/credentials_providers/instance_profile_credentials_provider.cc
  utils/s3/credentials_providers/instance_profile_credentials_provider.hh
  utils/s3/credentials_providers/sts_assume_role_credentials_provider.cc
  utils/s3/credentials_providers/sts_assume_role_credentials_provider.hh
  utils/s3/creds.hh
Labels: area/object storage, backport/none

#21533 De-duplicate validation of tables in some column_family API endpoints
  api/column_family.cc
  api/column_family.hh
  api/compaction_manager.cc
  api/storage_service.cc
  api/storage_service.hh
Labels: backport/none

#22488 vector: add support for vector type
  concrete_types.hh
  cql3/Cql.g
  cql3/cql3_type.cc
  cql3/cql3_type.hh
  cql3/expr/expr-utils.hh
  cql3/expr/expression.cc
  cql3/expr/expression.hh
  cql3/expr/prepare_expr.cc
  cql3/type_json.cc
  db/marshal/type_parser.cc
  db/marshal/type_parser.hh
  docs/architecture/sstable/sstable3/sstables-3-statistics.rst
  docs/cql/appendices.rst
  docs/cql/definitions.rst
  docs/cql/json.rst
  docs/cql/non-reserved-keywords.rst
  docs/cql/types.rst
  docs/dev/cql3-type-mapping.md
  docs/dev/lua-type-mapping.md
  docs/reference/limits.rst
  lang/lua.cc
  test/boost/cql_functions_test.cc
  test/boost/cql_query_test.cc
  test/boost/expr_test.cc
  test/boost/json_cql_query_test.cc
  test/boost/types_test.cc
  test/boost/user_function_test.cc
  test/boost/user_types_test.cc
  test/boost/view_schema_test.cc
  test/cqlpy/cassandra_tests/validation/entities/vectors_test.py
  test/cqlpy/cassandra_tests/validation/operations/cql_vector_test.py
  test/lib/expr_test_utils.cc
  test/lib/expr_test_utils.hh
  transport/server.cc
  types/types.cc
  types/types.hh
  types/vector.hh
Labels: backport/none

#22532 auth: ensure default superuser password is set before serving CQL
  auth/allow_all_authenticator.hh
  auth/authenticator.hh
  auth/certificate_authenticator.hh
  auth/password_authenticator.cc
  auth/password_authenticator.hh
  auth/saslauthd_authenticator.hh
  auth/service.cc
  auth/transitional.cc
  test/auth_cluster/test_auth_password_ensured.py
  test/pylib/manager_client.py
Labels: backport/none, status/merge candidate

#22736 .github: improve license header check workflow
  .github/workflows/check-license-header.yaml
Labels: area/build, backport/none

#22090 Add per-table tablet options in schema
  configure.py
  cql3/statements/cf_prop_defs.cc
  cql3/statements/cf_prop_defs.hh
  cql3/statements/create_keyspace_statement.cc
  data_dictionary/data_dictionary.cc
  data_dictionary/data_dictionary.hh
  data_dictionary/keyspace_metadata.hh
  db/CMakeLists.txt
  db/schema_features.hh
  db/schema_tables.cc
  db/tablet_options.cc
  db/tablet_options.hh
  docs/cql/ddl.rst
  docs/dev/describe_schema.md
  gms/feature_service.cc
  gms/feature_service.hh
  locator/network_topology_strategy.cc
  locator/network_topology_strategy.hh
  locator/tablet_replication_strategy.hh
  locator/tablets.cc
  locator/tablets.hh
  schema/schema.cc
  schema/schema.hh
  schema/schema_builder.hh
  service/tablet_allocator.cc
  service/tablet_allocator.hh
  test/boost/network_topology_strategy_test.cc
  test/boost/schema_change_test.cc
  test/boost/tablets_test.cc
  test/cqlpy/test_describe.py
  test/cqlpy/test_tablets.py
  test/perf/tablet_load_balancing.cc
Labels: status/release blocker, area/tablets, backport/none

#22701 reader_concurrency_semaphore: set_notify_handler(): disable timeout
  reader_concurrency_semaphore.cc
  reader_permit.hh
  test/boost/querier_cache_test.cc
Labels: symptom/performance, backport/6.1, backport/6.2, backport/2025.1

#20940 scylla-gdb.py: introduce scylla tablet-metadata command
  scylla-gdb.py
  test/scylla_gdb/test_misc.py
Labels: area/diagnostics, backport/none, status/merge candidate

#22487 tasks: use host_id in task manager
  api/api.cc
  api/api_init.hh
  api/task_manager.cc
  api/task_manager.hh
  configure.py
  idl/CMakeLists.txt
  idl/tasks.idl.hh
  main.cc
  message/messaging_service.cc
  message/messaging_service.hh
  node_ops/task_manager_module.cc
  node_ops/task_manager_module.hh
  service/task_manager_module.cc
  service/task_manager_module.hh
  tasks/task_handler.cc
  tasks/task_handler.hh
  tasks/task_manager.cc
  tasks/task_manager.hh
  test/lib/cql_test_env.cc
Labels: backport/none

#22650 Fix a regression that sometimes causes an internal error and demote barrier_and_drain rpc error log to a warning
  service/storage_service.cc
  service/storage_service.hh
  service/topology_coordinator.cc
Labels: backport/2025.1

#22788 tree: migrate from boost::remove_if() to the standard library based alternatives
  compaction/leveled_compaction_strategy.cc
  compaction/size_tiered_compaction_strategy.cc
  compaction/time_window_compaction_strategy.cc
  locator/abstract_replication_strategy.cc
  replica/table.cc
  service/mapreduce_service.cc
  sstables/sstable_set.cc
Labels: type/code cleanup, backport/none

#22791 sstable_loader: fix cross-shard resource cleanup in download_task_impl
  compaction/compaction_manager.cc
  repair/repair.cc
  repair/task_manager_module.hh
  sstables_loader.cc
  sstables_loader.hh
  tasks/task_manager.cc
  tasks/task_manager.hh
Labels: area/backup and restore, backport/2025.1

#22816 test.py: suport subfolders
  test.py
  test/topology_custom/mv/__init__.py
  test/topology_custom/mv/tablets/__init__.py
  test/topology_custom/mv/tablets/test_mv_tablets.py
  test/topology_custom/mv/tablets/test_mv_tablets_empty_ip.py
  test/topology_custom/mv/tablets/test_mv_tablets_replace.py
  test/topology_custom/mv/test_mv_admission_control.py
  test/topology_custom/mv/test_mv_backlog.py
  test/topology_custom/mv/test_mv_building.py
  test/topology_custom/mv/test_mv_delete_partitions.py
  test/topology_custom/mv/test_mv_fail_building.py
  test/topology_custom/mv/test_mv_read_concurrency.py
  test/topology_custom/mv/test_mv_topology_change.py
Labels: backport/none, status/merge candidate

#22621 repair: Introduce Host and DC filter support
  api/api-doc/storage_service.json
  api/storage_service.cc
  docs/dev/system_keyspace.md
  locator/tablets.cc
  locator/tablets.hh
  repair/repair.cc
  replica/tablets.cc
  service/storage_service.cc
  service/storage_service.hh
  service/topology_coordinator.cc
  test/boost/tablets_test.cc
  test/pylib/repair.py
  test/pylib/rest_client.py
  test/topology_custom/test_tablet_repair_scheduler.py
Labels: area/repair, P2, area/tablets, backport/none

#22676 Fix view-builder vs (repair and streaming) initialization order
  main.cc
  repair/row_level.cc
  repair/row_level.hh
  streaming/consumer.cc
  streaming/consumer.hh
  streaming/stream_manager.cc
  streaming/stream_manager.hh
  streaming/stream_session.cc
  test/lib/cql_test_env.cc
Labels: backport/none

#22725 sstables_manager: trigger reclaim/reload on `components_memory_reclaim_threshold` update
  sstables/sstables.cc
  sstables/sstables_manager.cc
  sstables/sstables_manager.hh
  test/boost/bloom_filter_test.cc
  test/lib/sstable_test_env.hh
Labels: backport/none

#22810 encryption_at_rest_test/encryption: Add some verbosity etc to help diagnose test run issues
  ent/encryption/encryption.cc
  ent/encryption/encryption_exceptions.hh
  ent/encryption/gcp_host.cc
  ent/encryption/kms_host.cc
  test/boost/encryption_at_rest_test.cc
Labels: backport/none, status/ci in progress

#22835 raft_rpc::send_append_entries: limit memory usage
  raft/fsm.cc
  raft/raft.cc
  raft/raft.hh
  service/raft/raft_rpc.cc
  service/raft/raft_rpc.hh
Labels: backport/none

#22371 truncate: don't fail on already waiting truncate for the same table
  service/storage_proxy.cc
  test/topology_custom/test_truncate_with_tablets.py
Labels: area/tablets, backport/none

#22399 test/topology: use standard new_test_keyspace functions
  test/pylib/repair.py
  test/topology/test_aggregation.py
  test/topology/test_mv.py
  test/topology/test_tls.py
  test/topology/util.py
  test/topology_custom/mv/tablets/test_mv_tablets.py
  test/topology_custom/mv/tablets/test_mv_tablets_empty_ip.py
  test/topology_custom/mv/tablets/test_mv_tablets_replace.py
  test/topology_custom/mv/test_mv_admission_control.py
  test/topology_custom/mv/test_mv_backlog.py
  test/topology_custom/mv/test_mv_building.py
  test/topology_custom/mv/test_mv_delete_partitions.py
  test/topology_custom/mv/test_mv_fail_building.py
  test/topology_custom/mv/test_mv_read_concurrency.py
  test/topology_custom/mv/test_mv_topology_change.py
  test/topology_custom/test_change_replication_factor_1_to_0.py
  test/topology_custom/test_commitlog_segment_data_resurrection.py
  test/topology_custom/test_compacting_reader_tombstone_gc.py
  test/topology_custom/test_conflicting_keys_read_repair.py
  test/topology_custom/test_data_resurrection_after_cleanup.py
  test/topology_custom/test_group0_schema_versioning.py
  test/topology_custom/test_hints.py
  test/topology_custom/test_ip_mappings.py
  test/topology_custom/test_lwt_semaphore.py
  test/topology_custom/test_maintenance_mode.py
  test/topology_custom/test_major_compaction.py
  test/topology_custom/test_node_isolation.py
  test/topology_custom/test_node_shutdown_waits_for_pending_requests.py
  test/topology_custom/test_not_enough_token_owners.py
  test/topology_custom/test_query_rebounce.py
  test/topology_custom/test_raft_fix_broken_snapshot.py
  test/topology_custom/test_raft_no_quorum.py
  test/topology_custom/test_raft_snapshot_truncation.py
  test/topology_custom/test_read_repair.py
  test/topology_custom/test_reversed_queries_during_simulated_upgrade_process.py
  test/topology_custom/test_rpc_compression.py
  test/topology_custom/test_select_from_mutation_fragments.py
  test/topology_custom/test_shutdown_hang.py
  test/topology_custom/test_table_desc_read_barrier.py
  test/topology_custom/test_tablet_repair_scheduler.py
  test/topology_custom/test_tablets.py
  test/topology_custom/test_tablets2.py
  test/topology_custom/test_tablets_cql.py
  test/topology_custom/test_tablets_intranode.py
  test/topology_custom/test_tablets_merge.py
  test/topology_custom/test_tablets_migration.py
  test/topology_custom/test_tablets_removenode.py
  test/topology_custom/test_tombstone_gc.py
  test/topology_custom/test_topology_failure_recovery.py
  test/topology_custom/test_truncate_with_tablets.py
  test/topology_custom/test_view_build_status.py
  test/topology_custom/test_zero_token_nodes_multidc.py
  test/topology_custom/test_zero_token_nodes_no_replication.py
  test/topology_tasks/test_node_ops_tasks.py
  test/topology_tasks/test_tablet_tasks.py
Labels: area/test, backport/none, status/merge candidate

#22879 Merge topology_tasks and topology_random_failures into topology_custom
  test/topology_custom/random_failures/__init__.py
  test/topology_custom/random_failures/cluster_events.py
  test/topology_custom/random_failures/error_injections.py
  test/topology_custom/random_failures/test_random_failures.py
  test/topology_custom/suite.yaml
  test/topology_custom/tasks/__init__.py
  test/topology_custom/tasks/task_manager_client.py
  test/topology_custom/tasks/task_manager_types.py
  test/topology_custom/tasks/test_node_ops_tasks.py
  test/topology_custom/tasks/test_tablet_tasks.py
  test/topology_random_failures/conftest.py
  test/topology_random_failures/suite.yaml
  test/topology_tasks/__init__.py
  test/topology_tasks/conftest.py
  test/topology_tasks/suite.yaml
Labels: backport/none, status/merge candidate

#22484 raft topology: Add support for raft topology init to happen before group0 initialization
  db/system_keyspace.cc
  db/system_keyspace.hh
  service/migration_manager.hh
  service/qos/service_level_controller.cc
  service/raft/group0_state_machine.cc
  service/raft/group0_state_machine.hh
  service/raft/raft_group0.cc
  service/raft/raft_group0.hh
  service/raft/raft_group0_client.cc
  service/raft/raft_group0_client.hh
  service/storage_service.cc
  service/storage_service.hh
Labels: backport/2025.1

#22823 Untangle sstable-directory vs sstable in pending log creation code
  sstables/sstable_directory.cc
  sstables/sstable_directory.hh
  sstables/sstables.hh
  sstables/storage.cc
  sstables/storage.hh
Labels: backport/none

#22522 Respect per-shard tablet goal and 10x default per-shard tablet count
  db/config.cc
  db/config.hh
  locator/network_topology_strategy.cc
  locator/network_topology_strategy.hh
  locator/tablet_replication_strategy.hh
  locator/tablets.cc
  locator/tablets.hh
  main.cc
  service/tablet_allocator.cc
  service/tablet_allocator.hh
  test.py
  test/boost/network_topology_strategy_test.cc
  test/boost/tablets_test.cc
  test/cqlpy/suite.yaml
  test/lib/cql_test_env.cc
  test/lib/cql_test_env.hh
  test/perf/tablet_load_balancing.cc
  test/rest_api/suite.yaml
  test/topology_custom/test_major_compaction.py
  test/topology_custom/test_tablets.py
Labels: P1, status/release blocker, area/tablets, backport/none, status/merge candidate, area/elastic cloud
