Repository scylladb/scylladb, pull requests merged in 2025-03, with the labels that each got.

#23101 tablets: repair: fix hosts and dcs filters behavior for tablet repair
  locator/tablets.cc
  locator/tablets.hh
  repair/repair.cc
  service/topology_coordinator.cc
  test/topology_custom/test_tablet_repair_scheduler.py
Labels: area/repair, area/tablets, backport/2025.1

#22975 replica: Prepare full keyspace config in make_keyspace_config()
  replica/database.cc
  replica/database.hh
Labels: backport/none

#22742 De-duplicate API's table name to table ID conversion
  api/column_family.cc
  api/storage_service.cc
  api/storage_service.hh
Labels: backport/none

#12246 Label basic metrics
  alternator/stats.cc
  alternator/ttl.cc
  cdc/log.cc
  compaction/compaction_manager.cc
  configure.py
  cql3/query_processor.cc
  db/commitlog/commitlog.cc
  db/row_cache.cc
  db/view/view.cc
  gms/gossiper.cc
  main.cc
  repair/repair.cc
  replica/database.cc
  service/storage_proxy.cc
  service/storage_service.cc
  sstables/sstables.cc
  streaming/stream_manager.cc
  transport/server.cc
  utils/CMakeLists.txt
  utils/labels.cc
  utils/labels.hh
  utils/logalloc.cc
Labels: backport/none

#23044 reader_concurrency_semaphore: register_inactive_read(): handle aborted permit
  reader_concurrency_semaphore.cc
  test/boost/reader_concurrency_semaphore_test.cc
Labels: backport/6.2, backport/2025.1

#22847 raft topology: drop changing the raft voters config via storage_service
  service/raft/raft_group0.cc
  service/raft/raft_group0.hh
  service/storage_service.cc
  service/topology_coordinator.cc
  test/topology_custom/test_tablets_migration.py
Labels: backport/none

#23103 main: safely check stop_signal in-between starting services
  main.cc
Labels: backport/2025.1

#22910 dist/docker: switch to UBI9
  dist/common/scripts/scylla_cpuset_setup
  dist/common/scripts/scylla_dev_mode_setup
  dist/common/scripts/scylla_io_setup
  dist/common/scripts/scylla_util.py
  dist/docker/etc/supervisord.conf
  dist/docker/redhat/README.md
  dist/docker/redhat/build_docker.sh
Labels: backport/none, ci/requires artifact tests

#22868 streaming: fix the way a reason of streaming failure is determined
  configure.py
  repair/CMakeLists.txt
  repair/repair.cc
  streaming/CMakeLists.txt
  streaming/stream_session.cc
  streaming/stream_transfer_task.cc
  streaming/table_check.cc
  streaming/table_check.hh
Labels: area/schema changes, backport/6.2, backport/2025.1

#23113 Main: stop system_keyspace
  compaction/compaction_manager.cc
  compaction/compaction_manager.hh
  configure.py
  db/large_data_handler.cc
  db/large_data_handler.hh
  db/system_keyspace.cc
  db/system_keyspace.hh
  main.cc
  replica/database.cc
  replica/database.hh
  test/boost/CMakeLists.txt
  test/boost/pluggable_test.cc
  test/lib/cql_test_env.cc
  utils/pluggable.hh
Labels: backport/none

#22321 scylla-sstable: add native S3 support
  configure.py
  data_dictionary/storage_options.hh
  docs/operating-scylla/admin-tools/scylla-sstable.rst
  docs/operating-scylla/admin.rst
  init.cc
  init.hh
  main.cc
  test/boost/s3_test.cc
  test/cqlpy/conftest.py
  test/cqlpy/run
  test/cqlpy/test_tools.py
  tools/scylla-sstable.cc
  utils/CMakeLists.txt
  utils/s3/utils/manip_s3.cc
  utils/s3/utils/manip_s3.hh
Labels: area/object storage, area/scylla tools, backport/none

#22682 Apply hard limit to partition range vectors in secondary index queries
  cql3/statements/select_statement.cc
  cql3/untyped_result_set.hh
  test/boost/secondary_index_test.cc
Labels: area/sec index, symptom/stalls, backport/none

#23216 Remove some excessive ks:cf -> table_id conversions in API and schema_tables
  api/storage_service.cc
  db/legacy_schema_migrator.cc
  db/schema_tables.cc
  db/schema_tables.hh
  replica/database.cc
  replica/database.hh
  service/client_state.cc
Labels: backport/none

#23253 perf/perf_sstable: stop using at_exit()
  test/perf/perf_sstable.cc
Labels: type/code cleanup, backport/none

#23150 commitlog: Serialize file deletion and distribute replayed segments
  db/commitlog/commitlog.cc
  main.cc
  test/boost/commitlog_test.cc
Labels: backport/none

#22286 introduce the new Raft-based recovery procedure for group 0 majority loss
  db/config.cc
  db/config.hh
  gms/gossiper.cc
  gms/gossiper.hh
  main.cc
  service/raft/raft_group0.cc
  service/raft/raft_group0.hh
  service/storage_service.cc
  test/cluster/auth_cluster/test_auth_v2_migration.py
  test/cluster/auth_cluster/test_raft_service_levels.py
  test/cluster/test_group0_schema_versioning.py
  test/cluster/test_raft_fix_broken_snapshot.py
  test/cluster/test_raft_recovery_basic.py
  test/cluster/test_raft_recovery_during_join.py
  test/cluster/test_raft_recovery_entry_loss.py
  test/cluster/test_raft_recovery_majority_loss.py
  test/cluster/test_raft_recovery_stuck.py
  test/cluster/test_raft_recovery_user_data.py
  test/cluster/test_topology_recovery_basic.py
  test/cluster/util.py
Labels: backport/2025.1

#22842 repair: allow concurrent repair and migration of two different tablets
  idl/repair.idl.hh
  repair/repair.cc
  repair/row_level.cc
  repair/row_level.hh
  repair/task_manager_module.hh
  repair/writer.hh
  service/storage_service.cc
  test/cluster/test_tablets.py
Labels: area/repair, status/release blocker, area/tablets, backport/2025.1

#23138 cql3: Introduce RF-rack-valid keyspaces
  conf/scylla.yaml
  cql3/statements/alter_keyspace_statement.cc
  cql3/statements/create_keyspace_statement.cc
  db/config.cc
  db/config.hh
  docs/architecture/tablets.rst
  docs/architecture/zero-token-nodes.rst
  docs/cql/ddl.rst
  docs/reference/glossary.rst
  locator/tablets.cc
  locator/tablets.hh
  main.cc
  replica/database.cc
  replica/database.hh
  test/cluster/test_multidc.py
  test/lib/cql_test_env.cc
Labels: area/schema changes, status/release blocker, area/tablets, backport/2025.1

#22907 Introduce s3 data_source_impl for optimized object streaming
  test/boost/s3_test.cc
  test/perf/perf_s3_client.cc
  utils/s3/client.cc
  utils/s3/client.hh
Labels: area/object storage, backport/none, area/backup and restore

#23445 Improve scoped restore test
  test/cluster/object_store/test_backup.py
Labels: symptom/ci stability, tests/flaky, backport/none

#22960 test.py: topology: allow to run tests with bare pytest command
  test.py
  test/__init__.py
  test/boost/conftest.py
  test/cluster/conftest.py
  test/cluster/random_failures/conftest.py
  test/cluster/random_failures/test_random_failures.py
  test/conftest.py
  test/nodetool/conftest.py
  test/pylib/async_cql.py
  test/pylib/cpp/common_cpp_conftest.py
  test/pylib/manager_client.py
  test/pylib/resource_gather.py
  test/pylib/scylla_cluster.py
  test/pylib/suite/base.py
  test/pylib/suite/boost.py
  test/pylib/suite/cql_approval.py
  test/pylib/suite/python.py
  test/pylib/suite/run.py
  test/pylib/suite/tool.py
  test/pylib/suite/topology.py
  test/pylib/suite/unit.py
  test/pylib/util.py
  test/pytest.ini
Labels: tests/test.py, backport/none

#23472 Snapshot several tables at once in scrub API handler
  api/storage_service.cc
  db/snapshot-ctl.cc
  db/snapshot-ctl.hh
Labels: backport/none

#22148 Finalize tablet splits earlier
  service/tablet_allocator.cc
  service/topology_coordinator.cc
  test/cluster/test_tablets.py
Labels: symptom/performance, P1, area/tablets, backport/none, status/merge candidate, area/elastic cloud

#23482 test/database: Remove most of take_snapshot() helper overloads and re-use them more
  test/boost/database_test.cc
Labels: backport/none
