Repository scylladb/scylladb, pull requests merged in 2025-09, with the labels that each got.

#25674 Move "cache" API endpoints registration closer to column_family ones
  api/api.cc
  api/api_init.hh
  api/cache_service.cc
  api/cache_service.hh
  main.cc
Labels: backport/none

#25570 cql3: add default replication factor to `create_keyspace_statement`
  cql3/statements/ks_prop_defs.cc
  docs/cql/ddl.rst
  test/cluster/suite.yaml
  test/cluster/test_keyspace_rf.py
  test/cqlpy/cassandra_tests/validation/operations/create_test.py
  test/cqlpy/test_keyspace.py
Labels: enhancement, documentation, backport/none

#25797 Allow users to SELECT from CDC log tables they created.
  cql3/statements/select_statement.cc
  test/cqlpy/test_permissions.py
Labels: bug, area/cdc, area/role based access control, backport/none, status/merge_candidate

#25841 interval: specialize for trivially copyable types
  test/boost/nonwrapping_interval_test.cc
  utils/interval.hh
Labels: backport/none

#25698 test.py: add different levels of verbosity for output
  test.py
  test/pylib/runner.py
Labels: tests/test.py, backport/2025.3

#25583 test: fix race condition in test_long_join
  test/cluster/test_long_join.py
Labels: backport/none

#25690 replica: Fix split compaction when tablet boundaries change
  locator/tablets.cc
  locator/tablets.hh
  mutation_writer/token_group_based_splitting_writer.cc
  replica/table.cc
  test/cluster/test_tablets2.py
Labels: P1, area/tablets, status/merge_candidate, backport/2025.1, backport/2025.2, backport/2025.3, force_on_cloud

#25975 test: deflake test_restart_leaving_replica_during_cleanup
  test/cluster/test_tablets_migration.py
Labels: symptom/ci stability, backport/none

#25944 compaction: handle exception in expected_total_workload
  compaction/task_manager_module.cc
  tasks/task_manager.cc
Labels: area/compaction, symptom/ci stability, backport/none, area/task-manager

#25995 index, metrics: add per-index metrics
  cql3/statements/select_statement.cc
  cql3/statements/select_statement.hh
  index/secondary_index_manager.cc
  index/secondary_index_manager.hh
  test/cqlpy/test_secondary_index.py
Labels: backport/none

#26058 db/view/view_building_worker: split batch's data preparation and execution
  db/view/view_building_worker.cc
  db/view/view_building_worker.hh
Labels: area/materialized views, P0, symptom/ci stability, backport/none, force_on_cloud

#24558 Improve Encryption at Rest documentation
  docs/operating-scylla/security/encryption-at-rest.rst
Labels: documentation, backport/none, security/encryption at rest

#25369 service: pass current session_id to repair rpc
  idl/storage_service.idl.hh
  service/storage_service.cc
  service/storage_service.hh
  service/topology_coordinator.cc
  test/cluster/test_tablets.py
Labels: area/repair, area/tablets, backport/none

#26034 compaction/scrub: register sstables for compaction before validation
  compaction/compaction.cc
  compaction/compaction_manager.cc
  test/boost/sstable_compaction_test.cc
Labels: area/nodetool-scrub, P3, status/merge_candidate, backport/2025.1, backport/2025.2, backport/2025.3

#26053 db: cache: consider preempting after each partition
  db/row_cache.cc
Labels: backport/none

#26064 tools/scylla-sstable: extract json mutation stream parser into own hh,cc
  configure.py
  tools/json_mutation_stream_parser.cc
  tools/json_mutation_stream_parser.hh
  tools/scylla-sstable.cc
Labels: type/code cleanup, area/scylla tools, backport/none

#25412 transport: service_level_controller: create and use `driver` service level
  CMakeLists.txt
  configure.py
  db/system_keyspace.cc
  db/system_keyspace.hh
  docs/features/workload-prioritization.rst
  generic_server.cc
  generic_server.hh
  gms/feature_service.hh
  service/client_state.hh
  service/qos/raft_service_level_distributed_data_accessor.cc
  service/qos/raft_service_level_distributed_data_accessor.hh
  service/qos/service_level_controller.cc
  service/qos/service_level_controller.hh
  service/storage_service.cc
  service/topology_coordinator.cc
  service/topology_coordinator.hh
  test/boost/auth_test.cc
  test/boost/cql_query_test.cc
  test/boost/database_test.cc
  test/boost/generic_server_test.cc
  test/cluster/auth_cluster/test_raft_service_levels.py
  test/cluster/util.py
  test/cqlpy/test_describe.py
  test/cqlpy/test_service_levels.py
  test/perf/perf_generic_server.cc
  test/pylib/rest_client.py
  transport/server.cc
  transport/server.hh
Labels: area/drivers, area/authentication, backport/none, area/service levels

#25796 alternator: Store LSI keys in :attrs for newly created tables
  alternator/executor.cc
  test/alternator/test_lsi.py
Labels: backport/none, status/merge_candidate

#26144 topology_coordinator: abort view building a bit later in case of tablet migration
  service/topology_coordinator.cc
  test/cluster/test_view_building_coordinator.py
Labels: area/materialized views, P1, area/tablets, backport/none

#26155 cdc: fix create table with cdc if not exists
  service/migration_manager.cc
  test/cqlpy/test_cdc.py
Labels: bug, area/cdc, triage/master, area/tablets, backport/none

#26114 test/alternator: multiple fixes for tests so they would pass on DynamoDB
  test/alternator/conftest.py
  test/alternator/test_gsi.py
  test/alternator/test_health.py
  test/alternator/test_number.py
  test/alternator/test_tag.py
  test/alternator/util.py
Labels: backport/none

#26122 mv: run view building worker fibers in streaming group
  db/view/view_building_worker.cc
  db/view/view_building_worker.hh
  main.cc
Labels: area/materialized views, backport/none, status/merge_candidate

#26017 tablets: scheduler: Balance racks separately when rf_rack_valid_keyspaces is true
  service/tablet_allocator.cc
  test/cluster/test_not_enough_token_owners.py
  test/cluster/test_tablets.py
  test/cluster/test_tablets2.py
  test/perf/tablet_load_balancing.cc
Labels: symptom/performance, P1, area/tablets, backport/2025.2, backport/2025.3

#25776 streaming/stream_blob: generate view updates from staging sstables
  streaming/stream_blob.cc
  streaming/stream_blob.hh
  streaming/stream_session.cc
  test/cluster/test_view_building_coordinator.py
Labels: area/materialized views, P1, area/tablets, backport/none

#26055 vector_store_client: Add support for multiple IPs in DNS responses
  test/boost/vector_store_client_test.cc
  vector_search/dns.cc
  vector_search/dns.hh
  vector_search/vector_store_client.cc
  vector_search/vector_store_client.hh
Labels: backport/none, area/vector

#25979 test: fix test_one_big_mutation_corrupted_on_startup
  test/cluster/dtest/commitlog_test.py
  test/cluster/dtest/tools/files.py
Labels: backport/none

#26024 treewide: move away from accessing httpd::request::query_parameters
  api/column_family.cc
  api/raft.cc
  api/storage_service.cc
  api/task_manager.cc
  api/task_manager_test.cc
  test/boost/aws_error_injection_test.cc
  test/boost/encryption_at_rest_test.cc
  test/pylib/s3_server_mock.py
  tools/scylla-nodetool.cc
  utils/s3/client.cc
  utils/s3/credentials_providers/sts_assume_role_credentials_provider.cc
Labels: type/code cleanup, backport/none

#26178 alternator: update references to alternator streams issue
  alternator/executor.cc
  docs/alternator/new-apis.md
  test/alternator/test_metrics.py
  test/alternator/test_streams.py
  test/alternator/test_tablets.py
  test/cqlpy/test_permissions.py
Labels: backport/none

#26188 Coroutinize filesystem_storage::check_create_links_replay()
  sstables/storage.cc
Labels: backport/none

#26234 configure.py: fix passing of user linker flags to cmake
  configure.py
Labels: area/build, backport/none

#24187 sstable: add more complete schema to scylla component
  sstables/sstables.cc
  sstables/types.hh
  test/boost/schema_loader_test.cc
  test/lib/random_schema.hh
  tools/schema_loader.cc
  tools/scylla-sstable.cc
Labels: area/diagnostics, area/sstable, area/scylla tools, backport/none

#26283 Remove table::for_all_partitions_slow()
  replica/database.hh
  replica/table.cc
  test/boost/mutation_test.cc
Labels: backport/none

#26003 db/config: Add SSTable compression options for user tables
  configure.py
  cql3/statements/create_table_statement.cc
  db/config.cc
  db/config.hh
  main.cc
  sstables/compressor.cc
  sstables/compressor.hh
  test/boost/CMakeLists.txt
  test/boost/sstable_compression_config_test.cc
  test/cluster/test_sstable_compression_config.py
Labels: backport/2025.2, backport/2025.3

#26279 root,replica: mv multishard_mutation_query -> replica/multishard_query
  CMakeLists.txt
  configure.py
  docs/dev/paged-queries.md
  docs/operating-scylla/nodetool-commands/setlogginglevel.rst
  replica/CMakeLists.txt
  replica/database.cc
  replica/multishard_query.cc
  replica/multishard_query.hh
  replica/mutation_dump.cc
  service/storage_proxy.cc
  test/boost/CMakeLists.txt
  test/boost/database_test.cc
  test/boost/multishard_query_test.cc
  test/boost/test_config.yaml
Labels: type/code cleanup, backport/none

#25176 Alternator/cache expressions
  alternator/CMakeLists.txt
  alternator/executor.cc
  alternator/executor.hh
  alternator/expressions.g
  alternator/expressions.hh
  alternator/expressions_types.hh
  alternator/parsed_expression_cache.cc
  alternator/stats.cc
  alternator/stats.hh
  configure.py
  db/config.cc
  db/config.hh
  test/alternator/test_condition_expression.py
  test/alternator/test_expression_caching.py
  test/alternator/test_filter_expression.py
  test/alternator/test_key_condition_expression.py
  test/alternator/test_projection_expression.py
  test/alternator/test_update_expression.py
  test/boost/CMakeLists.txt
  test/boost/alternator_unit_test.cc
  test/boost/lru_string_map_test.cc
  utils/lru_string_map.hh
Labels: enhancement, area/alternator, backport/none, force_on_cloud

#25949 Fix for auth version change during node startup
  auth/password_authenticator.cc
  auth/roles-metadata.cc
  auth/roles-metadata.hh
  auth/standard_role_manager.cc
  auth/standard_role_manager.hh
Labels: P1, symptom/ci stability, backport/none, force_on_cloud

#26284 lwt: prohibit for tablet-based views and cdc logs
  locator/tablets.cc
  replica/database.cc
  service/storage_proxy.cc
  service/tablet_allocator.cc
  test/boost/tablets_test.cc
  test/cluster/test_tablets_lwt.py
  test/lib/cql_test_env.cc
Labels: area/materialized views, area/lwt, area/cdc, P1, area/tablets, backport/none, force_on_cloud

#26077 test: dtest: test_limits.py: migrate from dtest
  test/cluster/dtest/limits_test.py
  test/cluster/suite.yaml
Labels: backport/none
