Repository scylladb/scylladb, pull requests merged in 2025-04, with the labels that each got.

#23174 transport/server.cc: set default timestamp info in EXECUTE and BATCH tracing
  tracing/trace_state.hh
  transport/server.cc
Labels: backport/6.2, status/merge candidate, backport/2025.1

#23341 test/pylib: servers_add: support list of property_files
  test/cluster/auth_cluster/test_auth_no_quorum.py
  test/cluster/auth_cluster/test_auth_raft_command_split.py
  test/cluster/auth_cluster/test_auth_v2_migration.py
  test/cluster/auth_cluster/test_raft_service_levels.py
  test/cluster/conftest.py
  test/cluster/test_aggregation.py
  test/cluster/test_automatic_cleanup.py
  test/cluster/test_cluster_features.py
  test/cluster/test_concurrent_schema.py
  test/cluster/test_gossiper.py
  test/cluster/test_mutation_schema_change.py
  test/cluster/test_mv.py
  test/cluster/test_raft_cluster_features.py
  test/cluster/test_random_tables.py
  test/cluster/test_replace_alive_node.py
  test/cluster/test_topology_rejoin.py
  test/cluster/test_topology_schema.py
  test/pylib/internal_types.py
  test/pylib/manager_client.py
  test/pylib/scylla_cluster.py
  test/pytest.ini
Labels: backport/none, status/merge candidate

#23443 [Backport 2025.1] tablets: Make load balancing capacity-aware
  db/config.cc
  db/config.hh
  gms/feature_service.hh
  idl/storage_service.idl.hh
  locator/load_sketch.hh
  locator/tablets.cc
  locator/tablets.hh
  main.cc
  message/messaging_service.cc
  message/messaging_service.hh
  service/storage_service.cc
  service/storage_service.hh
  service/tablet_allocator.cc
  service/topology_coordinator.cc
  test/boost/database_test.cc
  test/boost/tablets_test.cc
  test/lib/cql_test_env.cc
  test/lib/cql_test_env.hh
  test/lib/topology_builder.hh
  test/perf/tablet_load_balancing.cc
  test/topology_custom/test_tablets_removenode.py
  utils/disk_space_monitor.cc
  utils/disk_space_monitor.hh
  utils/only_on_shard0.hh
Labels: backport/none

#22952 Remove object_storage.yaml and move the endpoints to scylla.yaml
  db/config.cc
  db/config.hh
  docs/dev/object_storage.md
  docs/operating-scylla/admin.rst
  init.cc
  init.hh
  main.cc
  sstables/sstables_manager.cc
  sstables/sstables_manager.hh
  test/boost/schema_change_test.cc
  test/cluster/object_store/conftest.py
  test/cluster/object_store/test_backup.py
  test/cluster/object_store/test_basic.py
  test/cqlpy/test_tools.py
  test/lib/test_services.cc
  test/pylib/minio_server.py
  tools/scylla-sstable.cc
Labels: backport/none

#22926 Unify http transport in EAR to use seastar http client
  configure.py
  ent/encryption/CMakeLists.txt
  ent/encryption/gcp_host.cc
  ent/encryption/kms_host.cc
  ent/encryption/utils.cc
  ent/encryption/utils.hh
Labels: backport/none, status/merge candidate

#23455 repair: release erm in repair_writer_impl::create_writer when possible
  repair/row_level.cc
  test/cluster/test_tablets.py
  test/pylib/repair.py
Labels: area/repair, status/release blocker, area/tablets, backport/2025.1

#22828 generic_server: throttle and shed incoming connections according to semaphore limit
  configure.py
  db/config.cc
  db/config.hh
  generic_server.cc
  generic_server.hh
  redis/controller.cc
  redis/controller.hh
  redis/server.cc
  redis/server.hh
  test/boost/generic_server_test.cc
  test/perf/CMakeLists.txt
  test/perf/perf.cc
  test/perf/perf.hh
  test/perf/perf_generic_server.cc
  transport/server.cc
  transport/server.hh
Labels: backport/none

#23241 [Out-of-space prevention] db: backup: prioritize sstables that were deleted from the table
  db/snapshot-ctl.cc
  db/snapshot-ctl.hh
  db/snapshot/backup_task.cc
  db/snapshot/backup_task.hh
  replica/database.cc
  replica/database.hh
  sstables/component_type.hh
  sstables/sstable_directory.hh
  sstables/sstables_manager.cc
  sstables/sstables_manager.hh
  sstables/sstables_manager_subscription.hh
  utils/s3/client_fwd.hh
Labels: backport/none, area/backup and restore, status/merge candidate

#23187 tablets: rebuild: use repair for tablet rebuild
  docs/dev/topology-over-raft.md
  gms/feature_service.hh
  locator/tablets.cc
  locator/tablets.hh
  repair/repair.cc
  repair/row_level.hh
  repair/task_manager_module.hh
  scripts/tablet-mon.py
  service/storage_service.cc
  service/tablet_allocator.cc
  service/topology_coordinator.cc
  test/cluster/test_tablets.py
Labels: symptom/performance, P1, area/tablets, backport/2025.1

#23379 Alternator batch count histograms
  alternator/executor.cc
  alternator/stats.cc
  alternator/stats.hh
  test/alternator/test_metrics.py
Labels: backport/2025.1

#21969 raft: implement the limited voters feature
  configure.py
  gms/feature_service.hh
  service/CMakeLists.txt
  service/raft/group0_voter_calculator.hh
  service/raft/group0_voter_handler.cc
  service/raft/group0_voter_handler.hh
  service/raft/raft_group0.cc
  service/topology_coordinator.cc
  test/boost/CMakeLists.txt
  test/boost/group0_voter_calculator_test.cc
  test/cluster/random_failures/test_random_failures.py
  test/cluster/test_raft_no_quorum.py
  test/cluster/test_raft_voters.py
  test/pylib/scylla_cluster.py
Labels: backport/none

#23075 scylla-gdb.py: improve scylla repairs command
  scylla-gdb.py
Labels: area/diagnostics, backport/none

#23584 Adjust tablet-mon.py for capacity-aware load balancing
  db/virtual_table.cc
  db/virtual_table.hh
  db/virtual_tables.cc
  db/virtual_tables.hh
  docs/dev/system_keyspace.md
  docs/dev/virtual-tables.md
  main.cc
  scripts/tablet-mon.py
  service/tablet_allocator.cc
  service/tablet_allocator.hh
  service/topology_coordinator.cc
  test/boost/virtual_table_mutation_source_test.cc
  test/cluster/test_tablet_stats.py
  test/lib/cql_test_env.cc
Labels: backport/none, status/merge candidate

#23489 test/cqlpy: Adjust tests to RF-rack-valid keyspaces
  test/cluster/test_tablets.py
  test/cqlpy/cassandra_tests/validation/operations/alter_test.py
  test/cqlpy/cassandra_tests/validation/operations/create_test.py
  test/cqlpy/suite.yaml
  test/cqlpy/test_guardrail_replication_strategy.py
  test/cqlpy/test_keyspace.py
  test/cqlpy/test_logs.py
  test/cqlpy/test_tablets.py
Labels: area/test, status/merge candidate, backport/2025.1

#22779 Ensure raft group0 RPCs use the gossip scheduling group.
  gms/feature_service.hh
  message/messaging_service.cc
  replica/database.hh
  service/storage_service.cc
  service/storage_service.hh
Labels: backport/6.2

#23751 storage_service: preserve state of busy topology when transiting tablet
  service/storage_service.cc
  service/topology_coordinator.cc
  test/cluster/test_tablets.py
Labels: bug, area/rest api, P2, area/tablets, backport/6.2

#23691 Alternator batch rcu
  alternator/consumed_capacity.cc
  alternator/consumed_capacity.hh
  alternator/executor.cc
  alternator/executor.hh
  test/alternator/test_returnconsumedcapacity.py
Labels: backport/2025.1

#17712 topology_coordinator: stop: await all background_action_holder:s
  service/topology_coordinator.cc
Labels: backport/6.2, status/merge candidate, backport/2025.1

#23167 test/cluster/test_read_repair: make incremental test work with tablets
  test/cluster/test_read_repair.py
Labels: symptom/ci stability, area/tablets, backport/none

#23782 managed_bytes: in the copy constructor, respect the target preferred allocation size
  test/boost/managed_bytes_test.cc
  utils/managed_bytes.hh
Labels: scale/large partitions, status/regression, tests/longevity, P1, symptom/crash, backport/6.2, backport/2025.1

#23727 backup: Optimize S3 throughput with shard-based upload
  db/snapshot-ctl.cc
  db/snapshot/backup_task.cc
  db/snapshot/backup_task.hh
  test/cluster/object_store/test_backup.py
  utils/s3/client_fwd.hh
Labels: P1, backport/none, area/backup and restore

#23779 Add CopyObject API implementation to S3 client
  test/boost/s3_test.cc
  utils/s3/client.cc
  utils/s3/client.hh
Labels: area/compaction-twcs, area/object storage, backport/none

#23800 main: make DC and rack immutable after bootstrap
  db/system_keyspace.cc
  db/system_keyspace.hh
  docs/operating-scylla/procedures/config-change/switch-snitch.rst
  main.cc
  service/storage_service.cc
  test/cluster/test_no_dc_rack_change.py
  test/cluster/test_snitch_change.py
  test/lib/cql_test_env.cc
Labels: backport/2025.1

#23708 tablets: Equalize per-table balance when allocating tablets for a new table
  locator/load_sketch.hh
  locator/network_topology_strategy.cc
  locator/tablets.cc
  locator/tablets.hh
  test/boost/tablets_test.cc
  test/lib/topology_builder.hh
Labels: area/tablets, status/merge candidate, backport/2025.1, area/balancer

#23828 Refactor and enhance s3_tests
  test/boost/s3_test.cc
Labels: area/object storage, backport/none

#23337 mv: make base_info in view schemas immutable
  alternator/executor.cc
  cql3/statements/alter_table_statement.cc
  cql3/statements/alter_table_statement.hh
  cql3/statements/create_view_statement.cc
  db/schema_applier.cc
  db/schema_tables.cc
  db/schema_tables.hh
  db/view/base_info.hh
  db/view/view.cc
  db/view/view.hh
  db/view/view_update_generator.cc
  db/view/view_update_generator.hh
  frozen_schema.cc
  frozen_schema.hh
  index/secondary_index_manager.cc
  replica/database.cc
  replica/table.cc
  schema/schema.cc
  schema/schema.hh
  schema/schema_builder.hh
  schema/schema_registry.cc
  schema/schema_registry.hh
  service/migration_manager.cc
  test/boost/cql_query_test.cc
  test/boost/schema_registry_test.cc
  test/cluster/mv/test_mv_building.py
  tools/schema_loader.cc
  view_info.hh
Labels: backport/2025.1

#23914 topology coordinator: do not proceed further on invalid boostrap tokens
  cdc/generation.cc
  service/topology_coordinator.cc
  test/cluster/test_bad_initial_token.py
Labels: backport/6.2, backport/2025.1
