Repository scylladb/scylladb, pull requests merged in 2025-01, with the labels that each got.

#22051 cql3: allow SELECT of specific collection element
  cql3/Cql.g
  cql3/expr/expression.cc
  cql3/expr/prepare_expr.cc
  cql3/selection/selectable.cc
  cql3/selection/selection.cc
  cql3/selection/selection.hh
  cql3/statements/select_statement.cc
  docs/cql/dml/select.rst
  docs/cql/types.rst
  service/mapreduce_service.cc
  service/pager/query_pagers.cc
  test/cqlpy/cassandra_tests/validation/entities/collections_test.py
  test/cqlpy/cassandra_tests/validation/operations/select_order_by_test.py
  test/cqlpy/test_select_collection_element.py
Labels: user request, area/cql, backport/6.1, backport/6.2

#22018 Phased barrier improvements
  replica/table.cc
  test/boost/serialized_action_test.cc
  utils/phased_barrier.hh
Labels: backport/none

#22163 test.py: check for existence of combined test with correct path
  test.py
Labels: tests/test.py, symptom/ci stability, backport/none, status/merge candidate

#22172 Clean up test/alternator mistakes that service levels introduced
  test/alternator/conftest.py
  test/alternator/run
  test/alternator/suite.yaml
  test/alternator/test_cql_rbac.py
  test/alternator/test_service_levels.py
Labels: area/test, type/code cleanup, area/alternator, backport/none

#21928 Fix edge case issues related to tablet draining
  service/tablet_allocator.cc
  service/topology_coordinator.cc
  test/boost/tablets_test.cc
  test/topology_custom/test_tablets.py
Labels: bug, area/raft, P2, area/tablets, backport/6.1, backport/6.2, status/merge candidate

#22009 node_ops: filter topology_requests entries shown by node_ops_virtual_task
  db/system_keyspace.cc
  db/system_keyspace.hh
  node_ops/task_manager_module.cc
  test/topology_tasks/test_node_ops_tasks.py
Labels: area/task-manager, backport/6.2

#21996 Fix possible data corruption due to token keys clashing in read repair.
  service/storage_proxy.cc
  service/storage_proxy.hh
  test/topology/util.py
  test/topology_custom/test_conflicting_keys_read_repair.py
Labels: backport/6.1, backport/6.2

#21752 docs: Update documentation on CREATE ROLE WITH HASHED PASSWORD
  docs/cql/describe-schema.rst
  docs/operating-scylla/security/authorization.rst
  test/boost/auth_test.cc
Labels: documentation, backport/none, area/backup and restore, status/ci in progress

#21877 Complete implementation of configuring IO bandwidth limits
  api/api.cc
  api/api_init.hh
  api/compaction_manager.cc
  api/config.cc
  api/config.hh
  api/storage_service.cc
  api/stream_manager.cc
  docs/operating-scylla/nodetool-commands/getcompactionthroughput.rst
  docs/operating-scylla/nodetool-commands/getstreamthroughput.rst
  docs/operating-scylla/nodetool-commands/setcompactionthroughput.rst
  docs/operating-scylla/nodetool-commands/setstreamthroughput.rst
  docs/operating-scylla/nodetool.rst
  streaming/stream_manager.hh
  test/nodetool/test_compaction_throughput.py
  test/nodetool/test_stream_throughput.py
  test/rest_api/test_system.py
  tools/scylla-nodetool.cc
  utils/config_file.hh
Labels: documentation, backport/none

#22066 test/pylib: two trivial cleanups
  test/pylib/scylla_cluster.py
Labels: type/code cleanup, tests/test.py, backport/none

#21909 main, view: Pair view builder drain with its start
  main.cc
  test/lib/cql_test_env.cc
  test/topology_custom/test_mv_building.py
Labels: backport/6.2

#22253 raft: Handle non-critical config update errors in when changing voter status.
  raft/server.cc
  service/raft/raft_group0.cc
  test/topology_custom/test_error_becoming_voter.py
Labels: P0, backport/6.1, status/ci in progress, backport/6.2

#22307 view_builder: write status to tables before starting to build
  db/view/view.cc
Labels: bug, area/materialized views, area/topology changes, P1, symptom/ci stability, backport/6.1, backport/6.2

#21891 tasks: add tablet resize virtual task
  api/api-doc/task_manager.json
  gms/feature_service.hh
  locator/tablets.cc
  locator/tablets.hh
  node_ops/task_manager_module.cc
  node_ops/task_manager_module.hh
  replica/compaction_group.hh
  replica/database.hh
  replica/table.cc
  replica/tablet_mutation_builder.hh
  replica/tablets.cc
  service/storage_service.cc
  service/storage_service.hh
  service/task_manager_module.cc
  service/task_manager_module.hh
  service/topology_coordinator.cc
  tasks/task_manager.cc
  tasks/task_manager.hh
  tasks/types.hh
  test/boost/sstable_set_test.cc
  test/boost/tablets_test.cc
  test/topology_tasks/task_manager_types.py
  test/topology_tasks/test_tablet_tasks.py
Labels: backport/none

#16403 Reject create table with compact storage
  conf/scylla.yaml
  cql3/statements/alter_table_statement.cc
  cql3/statements/create_table_statement.cc
  cql3/statements/prepared_statement.hh
  cql3/statements/raw/parsed_statement.cc
  db/config.cc
  db/config.hh
  docs/cql/ddl.rst
  test/boost/cql_query_test.cc
  test/cql/suite.yaml
  test/cqlpy/cassandra_tests/validation/operations/compact_storage_test.py
  test/cqlpy/cassandra_tests/validation/operations/compact_table_test.py
  test/cqlpy/conftest.py
  test/cqlpy/test_empty.py
  test/cqlpy/test_guardrail_compact_storage.py
Labels: documentation, backport/none

#21862 Cache base info for view schemas in the schema registry
  replica/database.cc
  replica/table.cc
  schema/schema.cc
  schema/schema_registry.cc
  schema/schema_registry.hh
  service/migration_manager.cc
  test/boost/schema_registry_test.cc
  test/cqlpy/test_materialized_view.py
Labels: area/materialized views, area/alternator, triage/oss, backport/6.1, backport/6.2

#21896 repair: Wire repair_time in system.tablets for tombstone gc
  idl/storage_service.idl.hh
  message/messaging_service.cc
  repair/repair.cc
  repair/row_level.cc
  repair/row_level.hh
  repair/task_manager_module.hh
  replica/tablets.cc
  replica/tablets.hh
  service/storage_service.cc
  service/storage_service.hh
  service/tablet_operation.hh
  service/topology_coordinator.cc
  test/boost/tablets_test.cc
  test/perf/perf_tablets.cc
  test/pylib/repair.py
  test/topology_custom/test_tablet_repair_scheduler.py
  tombstone_gc.cc
  tombstone_gc.hh
Labels: P2, status/release blocker, area/tablets, backport/none, area/elastic cloud

#22301 main, encryption: correct misspellings
  ent/encryption/encrypted_file_impl.cc
  ent/encryption/encryption.cc
  ent/encryption/encryption_config.cc
  ent/encryption/gcp_host.cc
  ent/encryption/kmip_host.cc
  main.cc
Labels: type/code cleanup, backport/none, status/merge candidate

#22393 cql3, test, utils: switch from boost::adaptors::uniqued to utils::views:unique
  configure.py
  cql3/statements/batch_statement.cc
  test/boost/CMakeLists.txt
  test/boost/cql_functions_test.cc
  test/boost/unique_view_test.cc
  utils/unique_view.hh
Labels: type/code cleanup, backport/none

#22416 main: rename `cql_sg_stats` metrics on scheduling group rename
  main.cc
  test/auth_cluster/test_raft_service_levels.py
Labels: symptom/ci stability, backport/none

#22483 Remove sharded<system_distributed_keyspace>& argument from storage_service::join_cluster()
  main.cc
  service/storage_service.cc
  service/storage_service.hh
  test/lib/cql_test_env.cc
Labels: type/code cleanup, backport/none

#22064 Simplify loading_cache_test and use manual_clock
  configure.py
  test/boost/bloom_filter_test.cc
  test/boost/loading_cache_test.cc
  test/boost/reader_concurrency_semaphore_test.cc
  test/boost/view_build_test.cc
  test/lib/CMakeLists.txt
  test/lib/eventually.cc
  test/lib/eventually.hh
  test/raft/replication.hh
  utils/loading_cache.hh
Labels: symptom/ci stability, tests/flaky, backport/6.1, backport/6.2, status/merge candidate

#22285 backup_task: remove a component once it is uploaded
  api/api-doc/storage_service.json
  api/storage_service.cc
  db/snapshot-ctl.cc
  db/snapshot-ctl.hh
  db/snapshot/backup_task.cc
  db/snapshot/backup_task.hh
  test/object_store/test_backup.py
  test/pylib/rest_client.py
Labels: P1, backport/none, area/backup and restore

#22330 split: run set_split_mode() on all storage groups during all_storage_groups_split()
  replica/database.cc
  replica/table.cc
  test/topology_custom/test_tablets.py
Labels: area/tablets, backport/6.1, backport/6.2, backport/2025.1

#22425 TLS: reduce inotify usage by sharing reloadability across shards
  alternator/server.cc
  alternator/server.hh
  generic_server.cc
  generic_server.hh
  message/messaging_service.cc
  redis/controller.cc
  transport/controller.cc
Labels: backport/none

#22452 truncate: trigger truncate logic from a transition state instead of global topology request
  service/storage_service.cc
  service/topology_coordinator.cc
  service/topology_state_machine.cc
  service/topology_state_machine.hh
Labels: area/tablets, backport/2025.1

#22473 repair: handle no_such_keyspace in repair preparation phase
  locator/abstract_replication_strategy.cc
  repair/repair.cc
  test/topology_custom/test_repair.py
Labels: area/schema changes, area/topology changes, P2, backport/6.1, backport/6.2, backport/2025.1

#22519 Do not update topology on address change
  service/storage_service.cc
  service/storage_service.hh
Labels: backport/2025.1

#22290 sstables: use std::variant instead of boost::variant
  scylla-gdb.py
  sstables/disk_types.hh
  sstables/sstables.cc
  tools/scylla-sstable.cc
Labels: type/code cleanup, backport/none

#22395 encrypted_file_impl: Check for reads on or past actual file length in transform
  ent/encryption/encrypted_file_impl.cc
  test/boost/encrypted_file_test.cc
Labels: bug, Backport candidate, tests/longevity, area/sstable, P1, status/release blocker, backport/6.1, security/encryption at rest

#22310 api: task_manager: do not unregister finish task when its status is queried
  api/api-doc/task_manager.json
  api/task_manager.cc
  docs/dev/task_manager.md
  docs/operating-scylla/admin-tools/task-manager.rst
  docs/operating-scylla/nodetool-commands/tasks/drain.rst
  docs/operating-scylla/nodetool-commands/tasks/index.rst
  docs/operating-scylla/nodetool-commands/tasks/status.rst
  docs/operating-scylla/nodetool-commands/tasks/tree.rst
  tasks/task_handler.cc
  test/nodetool/test_tasks.py
  test/rest_api/task_manager_utils.py
  test/rest_api/test_task_manager.py
  test/topology_tasks/task_manager_client.py
  tools/scylla-nodetool.cc
Labels: backport/6.1, backport/6.2, backport/2025.1

#22368 Fix repair vs storage services initialization order
  main.cc
  repair/row_level.cc
  repair/row_level.hh
  service/storage_service.cc
Labels: backport/none
