Repository scylladb/scylladb, pull requests merged in 2025-07, with the labels that each got.

#24633 encryption_at_rest_test: Fix some spurious errors
  ent/encryption/encryption.cc
  ent/encryption/gcp_host.cc
  ent/encryption/gcp_host.hh
  ent/encryption/kmip_host.cc
  ent/encryption/kms_host.cc
  ent/encryption/kms_host.hh
  test/boost/encryption_at_rest_test.cc
Labels: triage/master, security/encryption at rest, backport/2025.1, backport/2025.2, backport/2025.3

#22906 Co-locate tablets of different tables
  alternator/executor.cc
  docs/dev/system_keyspace.md
  docs/dev/topology-over-raft.md
  gms/feature_service.hh
  idl/storage_service.idl.hh
  locator/load_sketch.hh
  locator/tablets.cc
  locator/tablets.hh
  message/messaging_service.cc
  message/messaging_service.hh
  replica/database.cc
  replica/database.hh
  replica/tablet_mutation_builder.hh
  replica/tablets.cc
  replica/tablets.hh
  scripts/tablet-mon.py
  service/migration_listener.hh
  service/migration_manager.cc
  service/migration_manager.hh
  service/raft/raft_group0_client.cc
  service/raft/raft_group0_client.hh
  service/storage_service.cc
  service/storage_service.hh
  service/tablet_allocator.cc
  service/task_manager_module.cc
  service/topology_coordinator.cc
  test/boost/tablets_test.cc
  test/boost/view_schema_test.cc
  test/cluster/mv/tablets/test_mv_tablets.py
  test/cluster/test_tablets2.py
  test/cluster/test_tablets_colocation.py
  test/cluster/test_tablets_merge.py
  test/perf/tablet_load_balancing.cc
  test/pylib/manager_client.py
  test/pylib/tablets.py
Labels: area/materialized views, backport/none

#24202 repair: postpone repair until topology is not busy
  repair/repair.cc
  service/topology_coordinator.cc
  test/cluster/test_tablets.py
Labels: area/repair, area/tablets, backport/2025.1, backport/2025.2, backport/2025.3

#24151 cql3: Represent create_statement using managed_bytes
  auth/service.cc
  auth/standard_role_manager.cc
  cql3/description.cc
  cql3/description.hh
  cql3/functions/aggregate_fcts.cc
  cql3/functions/user_function.cc
  cql3/statements/describe_statement.cc
  cql3/statements/describe_statement.hh
  data_dictionary/data_dictionary.cc
  replica/table.cc
  schema/schema.cc
  schema/schema.hh
  service/qos/service_level_controller.cc
  test/boost/cql_query_test.cc
  test/cluster/test_describe.py
  test/lib/random_schema.cc
  tools/scylla-sstable.cc
  types/types.cc
  utils/managed_string.hh
Labels: area/backup and restore, backport/2025.1, backport/2025.2

#24657 S3 chunked download source bug fixes
  test/boost/s3_test.cc
  test/boost/test_config.yaml
  test/pylib/s3_proxy.py
  utils/s3/client.cc
  utils/s3/client.hh
Labels: area/object storage, backport/none

#24331 vector_store_client: implement vector_store_client service
  conf/scylla.yaml
  configure.py
  cql3/query_processor.cc
  cql3/query_processor.hh
  cql3/statements/select_statement.cc
  cql3/statements/select_statement.hh
  db/config.cc
  db/config.hh
  docs/dev/protocols.md
  main.cc
  service/CMakeLists.txt
  service/vector_store_client.cc
  service/vector_store_client.hh
  test/boost/CMakeLists.txt
  test/boost/vector_store_client_test.cc
  test/lib/cql_test_env.cc
  utils/sequential_producer.hh
Labels: backport/none, area/vector

#24438 vector_index: do not create a view when creating a vector index
  cql3/statements/describe_statement.cc
  cql3/statements/index_target.cc
  cql3/statements/index_target.hh
  db/schema_tables.cc
  index/secondary_index_manager.cc
  index/secondary_index_manager.hh
  index/vector_index.cc
  index/vector_index.hh
  test/cqlpy/test_describe.py
  test/cqlpy/test_vector_index.py
Labels: backport/none, status/merge candidate

#24480 alternator: avoid oversized allocation in Query/Scan
  alternator/executor.cc
  alternator/executor.hh
  alternator/server.cc
  alternator/streams.cc
  alternator/ttl.cc
  test/alternator/test_query.py
  utils/rjson.cc
  utils/rjson.hh
Labels: symptom/latency, area/alternator, P1, symptom/stalls, status/ci in progress, backport/2025.1, backport/2025.2

#24901 repair: Speed up ranges calculation when small table optimization is on
  repair/repair.cc
  test/cluster/test_boot_nodes.py
Labels: area/repair, P1, backport/none

#24929 streaming: Avoid deadlock by running view checks in a separate scheduling group
  service/migration_manager.cc
  streaming/consumer.cc
  test/cluster/test_streaming_deadlock.py
Labels: area/streaming, area/repair, area/repair-based operations, P0, backport/2025.1, backport/2025.2, backport/2025.3

#25000 sstables: put index_reader behind a virtual interface
  sstables/index_entry.hh
  sstables/index_reader.hh
  sstables/mx/partition_reversing_data_source.cc
  sstables/mx/partition_reversing_data_source.hh
  sstables/mx/reader.cc
  sstables/sstable_mutation_reader.hh
  sstables/sstables.cc
  sstables/sstables.hh
  sstables/types.hh
  test/boost/sstable_3_x_test.cc
  test/boost/sstable_datafile_test.cc
  test/boost/sstable_mutation_test.cc
  test/lib/index_reader_assertions.hh
  tools/scylla-sstable.cc
Labels: backport/none

#24918 test.py: print warning when no tests found
  test.py
Labels: tests/test.py, backport/none

#24714 storage_service: cancel all write requests after stopping transports
  service/storage_proxy.cc
  service/storage_proxy.hh
  service/storage_service.cc
  test/cluster/test_unfinished_writes_during_shutdown.py
Labels: backport/2025.1, backport/2025.2, backport/2025.3

#24838 test.py: skip cleaning testlog
  test.py
  test/conftest.py
  test/pylib/ldap_server.py
  test/pylib/suite/base.py
Labels: tests/test.py, backport/none

#24978 tablets: prevent accidental copy of tablets_map
  locator/tablets.cc
  locator/tablets.hh
  replica/tablets.cc
  service/topology_coordinator.cc
  test/boost/locator_topology_test.cc
  test/boost/network_topology_strategy_test.cc
  test/boost/tablets_test.cc
  test/perf/tablet_load_balancing.cc
Labels: backport/none

#24819 LWT: enable for tablet-based tables
  cql3/query_options.cc
  cql3/query_options.hh
  cql3/query_processor.cc
  cql3/query_processor.hh
  cql3/statements/create_keyspace_statement.cc
  cql3/statements/modification_statement.cc
  cql3/statements/select_statement.cc
  db/system_keyspace.cc
  db/system_keyspace.hh
  docs/alternator/new-apis.md
  docs/architecture/tablets.rst
  docs/features/lwt.rst
  gms/feature_service.hh
  inet_address_vectors.hh
  locator/abstract_replication_strategy.hh
  main.cc
  replica/database.cc
  service/client_state.cc
  service/client_state.hh
  service/migration_manager.cc
  service/migration_manager.hh
  service/pager/query_pagers.cc
  service/paxos/paxos_state.cc
  service/paxos/paxos_state.hh
  service/storage_proxy.cc
  service/storage_proxy.hh
  service/storage_proxy_fwd.hh
  test/alternator/test_tablets.py
  test/alternator/test_ttl.py
  test/cluster/random_failures/cluster_events.py
  test/cluster/test_tablets_lwt.py
  test/cqlpy/test_tablets.py
  test/lib/cql_test_env.cc
Labels: backport/none

#25118 Move feature-service config creation code out of feature-service itself
  gms/feature_service.cc
  gms/feature_service.hh
  init.cc
  init.hh
  main.cc
  test/boost/schema_registry_test.cc
  test/lib/cql_test_env.cc
  test/lib/test_services.cc
  test/manual/gossip.cc
  test/manual/message.cc
  tools/read_mutation.hh
  tools/schema_loader.cc
  tools/scylla-sstable.cc
Labels: backport/none

#25151 raft_group0: split shutdown into abort-and-drain and destroy
  main.cc
  service/raft/raft_group0.cc
  service/raft/raft_group0.hh
  service/raft/raft_group_registry.cc
  service/raft/raft_group_registry.hh
  service/storage_service.cc
  test/cluster/test_cdc_generation_data.py
  test/lib/cql_test_env.cc
Labels: backport/none

#24499 generic server: 2 step shutdown
  db/config.cc
  db/config.hh
  generic_server.cc
  generic_server.hh
  test/cluster/auth_cluster/test_raft_service_levels.py
  test/cluster/test_long_query_timeout_erm.py
  test/cluster/test_write_query_during_cql_server_shutdown.py
  test/pylib/manager_client.py
  test/pylib/scylla_cluster.py
  transport/controller.cc
  transport/server.cc
  transport/server.hh
Labels: backport/none, conflicts

#25188 qos: don't populate effective service level cache until auth is migrated to raft
  auth/standard_role_manager.cc
  service/qos/raft_service_level_distributed_data_accessor.cc
  service/qos/raft_service_level_distributed_data_accessor.hh
  service/qos/service_level_controller.cc
  service/qos/service_level_controller.hh
  service/qos/standard_service_level_distributed_data_accessor.cc
  service/qos/standard_service_level_distributed_data_accessor.hh
  test/boost/service_level_controller_test.cc
  test/cluster/auth_cluster/test_raft_service_levels.py
Labels: status/merge candidate, backport/2025.1, backport/2025.2, backport/2025.3
