Repository scylladb/scylladb, pull requests merged in 2025-10, with the labels that each got.

#26169 Fix getendpoints command for compound keys containing ':'
  api/api-doc/storage_service.json
  api/storage_service.cc
  docs/operating-scylla/nodetool-commands/getendpoints.rst
  keys/keys.cc
  keys/keys.hh
  service/storage_service.cc
  service/storage_service.hh
  test/nodetool/rest_api_mock.py
  test/nodetool/test_getendpoints.py
  test/rest_api/conftest.py
  test/rest_api/test_storage_service.py
  tools/scylla-nodetool.cc
Labels: area/rest api, good first issue, P2, backport/none

#26280 root,replica: mv querier to replica/
  CMakeLists.txt
  configure.py
  replica/CMakeLists.txt
  replica/database.cc
  replica/database.hh
  replica/multishard_query.cc
  replica/querier.cc
  replica/querier.hh
  replica/table.cc
  test/boost/database_test.cc
  test/boost/multishard_query_test.cc
  test/boost/mutation_query_test.cc
  test/boost/querier_cache_test.cc
  test/perf/perf_row_cache_reads.cc
Labels: type/code cleanup, backport/none

#26394 sstables/sstable_directory: don't forget to delete other components when deleting TemporaryHashes.db
  sstables/sstable_directory.cc
  test/boost/database_test.cc
  test/lib/cql_test_env.hh
Labels: backport/2025.4
